### ISSUE TITLE
The noSuchMethod method can now be inherited

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/co19#10]
The wording in the specification has changed in (I think) 3 places to allow the noSuchMethod method to be inherited rather than requiring it to be implemented in every class. That causes two tests to be wrong:

Language/07_Classes/4_Abstract_Instance_Members_A02_t03
Language/07_Classes/4_Abstract_Instance_Members_A02_t04

**Comment by sgrekhov** [comment]
At which places specification was changed? These tests are in accordance with the latest specification available at https://www.dartlang.org/docs/spec/ (3-rd Edition / June 2015)

**Comment by alsemenov** [comment]
Please, clarify what is wrong with mentioned tests.

The test https://github.com/dart-lang/co19/blob/3237579f024abad4d862c8207e69378ab33f2622/Language/07_Classes/4_Abstract_Instance_Members_A02_t03.dart declares single class C. There is no inheritance. How the changes  in the specification, related to inheritance of noSuchMethod, make it wrong

The test https://github.com/dart-lang/co19/blob/3237579f024abad4d862c8207e69378ab33f2622/Language/07_Classes/4_Abstract_Instance_Members_A02_t04.dart actually rely on the fact that noSuchMethod method is inherited.

**Comment by bwilkerson** [comment]
> At which places specification was changed?

I'm looking at the version of the specification available at http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf. I don't know which version you're suppose to be looking at.

> https://github.com/dart-lang/co19/blob/3237579f024abad4d862c8207e69378ab33f2622/Language/07_Classes/4_Abstract_Instance_Members_A02_t03.dart
> https://github.com/dart-lang/co19/blob/3237579f024abad4d862c8207e69378ab33f2622/Language/07_Classes/4_Abstract_Instance_Members_A02_t04.dart

The specification (section 10.4) now states:

It is a static warning if an abstract member m is declared or inherited in a concrete class C unless:
• m overrides a concrete member, or
• C has a noSuchMethod() method distinct from the one declared in class Object.

There shouldn't be a static warning in either of these cases.

Other sections that mention noSuchMethod have similarly been changed to allow noSuchMethod to be inherited rather than requiring it to be implemented at every level.

**Comment by sgrekhov** [comment]
Fixed. See https://github.com/dart-lang/co19/commit/1f5eb18cdd263a085c189813996a3dc073b7a293
