### ISSUE TITLE
spawn tests need to have spawned method fixed so it doesn't exit prematurely, breaking test

### ISSUE THREAD

**Issue by aam** [dart-lang/co19#1003]
A fix simliar to https://github.com/dart-lang/co19/commit/a825e7eb8486dee8390fc678d43c1576662f344c is needed for  src/LibTest/isolate/Isolate/spawnUri_A05_t04_isolate.dart
src/LibTest/isolate/Isolate/spawn_A04_t04.dart

See failures on https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8854419269721535376/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0 for example

cc @sgrekhov

**Comment by sgrekhov** [comment]
Fixed in both `co19` and `co19_2` repositories
