### ISSUE TITLE
Have a test that would confirm tight-looped isolate won't get killed with Isolate.beforeNextEvent priority 

### ISSUE THREAD

**Issue by aam** [dart-lang/co19#1004]
https://github.com/dart-lang/co19/blob/master/LibTest/isolate/Isolate/kill_A01_t01.dart confirms that isolate will get killed even if it runs tight loop.
Complementary test that would confirm that tight-looped isolate won't get killed if killed with beforeNextEvent priority would be useful as there seems to be (an erroneous) possibility for such an isolate to still get killed.

**Comment by sgrekhov** [comment]
@aam do you have any ideas how the requested test should do? I wrote the following but it doesn't work

```dart
import "dart:isolate";
import "dart:async";
import "../../../Utils/expect.dart";

entryPoint(SendPort sendPort) async {
  sendPort.send("first");
  await Future.delayed(Duration(milliseconds: 100));
  sendPort.send("second");
}

test() async {
  final receivePort = new ReceivePort();
  final si = StreamIterator(receivePort);
  final onExit = new ReceivePort();
  Isolate isolate = await Isolate.spawn(entryPoint, receivePort.sendPort,
      onExit: onExit.sendPort, errorsAreFatal: true);
  Expect.isTrue(await si.moveNext());
  Expect.equals("first", si.current);
  isolate.kill(priority: Isolate.beforeNextEvent);

  Expect.isTrue(await si.moveNext()); // hangs here. Isolate gets killed, no message in `receivePort`
  Expect.equals("second", si.current);
  receivePort.close();
  await onExit.first;
  asyncEnd();
}

main() {
  asyncStart();
  test();
}
```

What must an isolate state to at the moment of `isolate.kill(priority: Isolate.beforeNextEvent);` call to make sure that it works as expected?

**Comment by aam** [comment]
I envisioned a test very similar to https://github.com/dart-lang/co19/blob/master/LibTest/isolate/Isolate/kill_A01_t01.dart but with `priority: Isolate.beforeNextEvent` for the kill.
Basically the idea is that child isolate should never get "to the next event" since it runs tight loop.

I think this test might not work reliably due to https://github.com/dart-lang/sdk/issues/45111, which makes having such a test really good thing.

**Comment by sgrekhov** [comment]
@aam does https://github.com/dart-lang/co19/blob/master/LibTest/isolate/Isolate/kill_A01_t03.dart  do what you want?

**Comment by aam** [comment]
@sgrekhov , I don't think so.
If I understand correctly kill_A01_t03 confirms that isolate waiting for events does get killed.
The test I think we are missing is the one that confirms that isolate _running_a_tight_loop_ won't get killed.

**Comment by sgrekhov** [comment]
@aam please review https://github.com/dart-lang/co19/pull/1079
