### ISSUE TITLE
co19_2/Language/Expressions/Numbers/syntax_t06 should take JS compilation into account

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1014]
Said test contains several integer literals whose value is such that there is no precise representation using JavaScript numbers (IEEE 754, 64 bit), which is now a compile-time error.

The test should probably be split in two:

- One is the current test, and it should be marked `SkipByDesign` for all configurations where the compilation target language is JavaScript.
- The other one is a minimal test, just confirming for each configuration where the compilation target language is JavaScript that said large integer literals are flagged as a compile-time error. This test should be `SkipByDesign` for all configurations except the ones where the target language is JavaScript.

**Comment by sgrekhov** [comment]
@eernstg is there a way to specify that we expect error on dart2js?
```dart
  9223372036854775807;
//^^^^^^^^^^^^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
```
How in the code above specify that we are expecting error not on analyzer and cfe but on dart2js?

**Comment by eernstg** [comment]
I think we'll need to have a test for configurations where the compilation produces JavaScript code, and another test for other configuratons, and use `SkipByDesign` to enable each of them in the right cases.

**Comment by sgrekhov** [comment]
@eernstg yes, that's exactly what I'm going to do. The question is how to expect a compile error on the test which will be enabled in JavaScript configurations only? Do we have somethong like

```
// [dart2js] unspecified
```

**Comment by eernstg** [comment]
I think you can use `// [web] ...`.
