### ISSUE TITLE
co19/Language/Generics/parameter_A01_t03/none missing nonfunction-type-aliases experiment

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#1016]
`co19/Language/Generics/parameter_A01_t03/none` uses nonfunction-type-aliases but isn't annotated to enable the experiment

**Comment by johnniwinther** [comment]
This is also the case for `co19/Language/Generics/typedef_A06_t04`.

**Comment by sgrekhov** [comment]
This was fixed by 3e7185e296a3a0fcc84f383fe285b9d323a8ed12. Fix will be activated after the next roll of co19 tests.
