### ISSUE TITLE
Internal changes to SplayTreeMap makes tests fail.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/co19#1023]
There are new test failures on [Add efficient `entries` and `keys.contains` to `SplayTreeMap`.](https://dart-review.googlesource.com/c/sdk/+/190883).

The change is that rather than checking simply for `key == null`, we check that the key is comparable to at least one other key using the provided or default `compare` function. If the map is empty, that wasn't checked before, so now the code calls `compare(key, key)` to check that it doesn't throw.
That allows a `null` key to be used when the `compare` function understands it, and fails immediately, on the first element/key, if it's not compatible with the `compare` fuinction.

The tests
```
co19/LibTest/collection/SplayTreeMap/SplayTreeMap_class_A02_t01 RuntimeError (expected Pass)
co19/LibTest/collection/SplayTreeMap/SplayTreeMap_class_A04_t04 RuntimeError (expected Pass)
co19_2/LibTest/collection/SplayTreeMap/SplayTreeMap_class_A02_t01 RuntimeError (expected Pass)
co19_2/LibTest/collection/SplayTreeMap/SplayTreeMap_class_A04_t04 RuntimeError (expected Pass)
co19/LibTest/collection/SplayTreeSet/SplayTreeSet_A03_t01
co19/LibTest/collection/SplayTreeSet/SplayTreeSet_A04_t02
co19_2/LibTest/collection/SplayTreeSet/SplayTreeSet_A03_t01
co19_2/LibTest/collection/SplayTreeSet/SplayTreeSet_A04_t02
```
are failing.

The `A02_t01` map test checks whether the `compare` function is actually called. It assumed that it wouldn't be called when inserting into an empty map, but that's no longer the case.

The `A04_t04` map test checks that using an incomparable key throws, but it assumed that wouldn't happen until the first lookup, now it happens in the initial insert (which is much better!)

The set tests both adds elements incompatible with the compare function (the former a non-comparable object with the default compare function, the latter an argument which makes the compare function throw), and expect the first `add` operation to succeed, which it non longer does.

**Comment by sgrekhov** [comment]
I'll change the tests after the change is landed
