### ISSUE TITLE
Failures on [tests] Remove triple shift test skips from status files

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#1025]
There are new test failures on [[tests] Remove triple shift test skips from status files](https://dart-review.googlesource.com/c/sdk/+/191482).

The test
```
co19/Language/Expressions/Shift/integer_t03 RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-x64
```

cc @alexmarkov

**Comment by sgrekhov** [comment]
Thanx! Fixed by 2a09bd3
