### ISSUE TITLE
co19/LanguageFeatures/Generic-functions-as-type-args/typedef2_A01_t01.dart et al.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1030]
Said test contains the following:

```dart
typedef void TEST<T extends void Function<TT>()>();
void testme<T extends void Function<TT>()>() {}

main() {
  TEST t = testme;
  Expect.isTrue(testme is TEST);
}
```

The expectation that `testme is TEST` should be changed: `TEST` denotes the type `void Function()`, and so does `TEST<T>` for any `T`, and it is not true that `testme` has a subtype of that.

Alternatively, it seems likely that the type alias should have been declared as follows:

```dart
typedef TEST = void Function<T extends void Function<TT>()>();
```

This would mean that `TEST` denotes a generic function type (an old-style type alias can never denote a generic function type), and also that `testme is TEST` should evaluate to true.

The same directory contains 42 occurrences of old-style type alias declarations, and it seems likely that at least some of them are intended to denote a generic function type. In the cases where that is true, they must be changed to use the new style (that style that includes `=`):

```
typedef1_A03_t01.dart
typedef2_A01_t01.dart
typedef2_A01_t02.dart
typedef2_A01_t03.dart
typedef2_A01_t04.dart
typedef2_A01_t05.dart
typedef2_A01_t06.dart
typedef2_A01_t07.dart
typedef2_A01_t08.dart
typedef2_A01_t09.dart
typedef2_A01_t10.dart
typedef2_A01_t11.dart
typedef2_A01_t12.dart
typedef2_A01_t13.dart
typedef2_A01_t14.dart
typedef2_A01_t15.dart
typedef2_A01_t16.dart
typedef2_A02_t01.dart
typedef2_A02_t02.dart
typedef2_A02_t03.dart
typedef2_A02_t04.dart
typedef2_A03_t01.dart
typedef3_A01_t01.dart
```

**Comment by iarkh** [comment]
Tests corrected.
Testcases for the new style typedefs are already covered by typedef1_* tests.
