### ISSUE TITLE
co19/Language/Metadata/syntax_t10 uses mirrors

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1031]
Does this test need an opt out for platforms that do not support mirrors?  cc @athomas @eernstg

**Comment by eernstg** [comment]
I think the test, and the fact that it uses mirrors, makes sense: We have no other way to ensure that the run-time representation of metadata (now aka annotations) is as expected.

I'm not sure how to say in a status file that we want exactly the configurations where mirrors are supported, but it should be possible to use the same approach as the one taken for lib/mirrors. A grep yields 3 obviously promising entries and one which may not be relevant:

```
lib/lib_dart2js.status:mirrors/*: SkipByDesign # Mirrors not supported on web in Dart 2.0.
lib/lib_dartdevc.status:mirrors/*: SkipByDesign # Mirrors not supported on web in Dart 2.0.
lib/lib_kernel.status:mirrors/*: SkipByDesign # Mirrors are not supported in AOT mode.
lib/lib_app_jit.status:mirrors/*: Skip # Issue 27929: Triage
```

**Comment by sgrekhov** [comment]
https://dart-review.googlesource.com/c/sdk/+/192744
