### ISSUE TITLE
Span for analyzer's use_of_nullable_value error to change

### ISSUE THREAD

**Issue by srawlins** [dart-lang/co19#1032]
In https://dart-review.googlesource.com/c/sdk/+/188680, I'm changing the span which is reported for use_of_nullable_value from the _receiver_ of the "use" to the "use" itself (property access, method call, operator call, ...). For example, in `tests/co19/src/LanguageFeatures/Spread-collections/StaticSemantic_A06_t01.dart`, line 75, `[analyzer]`'s error span will change from:

```
  var m7  = <dynamic, dynamic>{...?list[0]};
  //                               ^^^^
```

to:

```
  var m7  = <dynamic, dynamic>{...?list[0]};
  //                                   ^
```

This is the same span in the `[cfe]` error.

This causes co19 failures in the sdk repository. See here: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8853279437984702016/+/steps/test_results/0/logs/new_test_failures__logs_/0

How should we go about updating these? Can co19 make a change to this repo, and then a roll happens which introduces test failures, and then I land my change, or backwards? Either way, a big new test failure has to get introduced, right?

**Comment by sgrekhov** [comment]
I changed the test to expect a new behaviour. There must be a new co19 roll today so the fix will be enabled soon (cc. @athomas )

**Comment by srawlins** [comment]
Excellent, thanks much! There are more tests, seen at https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8853279437984702016/+/steps/test_results/0/logs/new_test_failures__logs_/0 that would need to be changed. I can enumerate them in a new issue if you like.

**Comment by sgrekhov** [comment]
@srawlins please see https://dart-review.googlesource.com/c/sdk/+/192746
