### ISSUE TITLE
co19_2/Language/Mixins/Mixin_Application/deferred_t01 uses nonfunction type aliases

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1037]
The nonfunction type aliases feature is not available in the co19_2 tests (since they run in a previous language version), but the feature is used as part of this test.  

cc @eernstg @athomas

**Comment by sgrekhov** [comment]
@leafpetersen thank you for pointing. Tests that use nonfunction type aliases were removed from co19_2 repository as part of #1028. This one was missed. A double checked and found two more places where nonfunction type aliases were still used in co19_2. Removed all of them now. @athomas does it makes sense to do another co19_2 roll?
