### ISSUE TITLE
Missing SharedOptions

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1040]
The following tests:

./src/Language/Metadata/places_t02.dart://--enable-experiment=generic-metadata
./src/Language/Metadata/syntax_t09.dart://--enable-experiment=generic-metadata
./src/Language/Metadata/syntax_t10.dart://--enable-experiment=generic-metadata
./src/Language/Metadata/syntax_t11.dart://--enable-experiment=generic-metadata

use an experiment flag without the SharedOptions prefix.

cc @eernstg @athomas

**Comment by sgrekhov** [comment]
Already fixed by f9b85b813a43ecc83e5855152641cac63cae15c8
