### ISSUE TITLE
Incorrect expectation in co19/Language/Types/Type_Aliases/built-in_types_t11

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1042]
The referenced tests contains the following expectation:

```
  IntAlias i = 1;
  Expect.equals(1, i >>> 64);
```

@eernstg @lrhn this doesn't seem to be correct to me, I think the expectation should be 0 (and this is what the implementations report).  Am I missing something or does this need fixing?

**Comment by sgrekhov** [comment]
This test was wrong. Fixed to expect correct results
