### ISSUE TITLE
co19/Language/Generics/Superbounded_types/typedef3_A01_t06/02 is not an error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1045]
`B<A<A<A<B>>>>` means `B<A<A<A<B<A<dynamic>>>>>>`, which is correctly super-bounded, because `A<A<A<B<A<Never>>>>> <: A<A<A<A<B<A<Never>>>>>>`.

**Comment by iarkh** [comment]
This is already fixed with 53e0547db14b1c49c55637ac65036cd0a52776e6
