### ISSUE TITLE
co19/Language/Types/Type_Aliases/self_reference_t23 should be re-branded

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1048]
The comment in said test implies that there is a cyclic dependency for the type alias, but that is not the case (`CAlias` does not depend on any other type alias, and dependencies via classes do not count; by the way, `C` does not refer to `CAlias`, but it wouldn't be a problem even if it did say something like `class C<X extends CAlias> {}`).

However, it uses `mixin CM on C, CAlias {}`, and [that is an error](https://github.com/dart-lang/language/blob/3500b68861bca9200339921dac35d8d8f55d1873/specification/dartLangSpec.tex#L5322), because the class declaration corresponding to `CM` that defines the interface would be an error.

So the description (and name) ought to be changed to reflect what it is actually testing.

**Comment by sgrekhov** [comment]
@eernstg  thank you! Please also see https://github.com/dart-lang/sdk/issues/45505
