### ISSUE TITLE
nonfunction_typedef_l1_t03 and several other tests use `A` which is malformed

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1050]
Consider the following declarations:

```dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A a = throw 0;
}
```

The raw `A` by i2b means `A<G<C<dynamic>>>`. However, that type is not well-bounded:

If it is regular-bounded then `G<C<dynamic>> <: G<C<G<C<dynamic>>>>`, but that does not hold:

```dart
G<C<dynamic>> == C<dynamic> Function(C<dynamic>)

G<C<G<C<dynamic>>>> == C<G<C<dynamic>>> Function(C<G<C<dynamic>>>) ==
    C<C<dynamic> Function(C<dynamic>)>
        Function(C<C<dynamic> Function(C<dynamic>)>)

// and `dynamic` isn't a subtype of _ Function(_).
```

If it is super-bounded then `A<G<C<Never>>>` must be regular-bounded and we must have `G<C<Never>> <: G<C<G<C<Never>>>>`, but that isn't true:

```dart
G<C<Never>> == C<Never> Function(C<Never>)

G<C<G<C<Never>>>> == C<G<C<Never>>> Function(C<G<C<Never>>>) ==
    C<C<Never> Function(C<Never>)>
        Function(C<C<Never> Function(C<Never>)>)

// But `C<C<Never> Function(C<Never>)>` is not a subtype of `C<Never>`.
```

So `A` cannot be used raw, because that's not a well-bounded type. This (and variants thereof) affects the following tests:

```
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/dynamic/nonfunction_typedef_l1_t03
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/dynamic/nonfunction_typedef_l2_t03
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/dynamic/nonfunction_typedef_l2_t07
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_typedef_l1_t03
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_typedef_l2_t03
co19/LanguageFeatures/Instantiate-to-bound/nonfunction_typedef/static/nonfunction_typedef_l2_t07
```

In some cases type arguments are given explicitly (like `A<dynamic, dynamic>` in `nonfunction_typedef_l2_t07`), but such types can of course be malbounded as well.

The tests should be revised such that they don't expect a malformed type to be a non-error.

**Comment by iarkh** [comment]
Source code example above  throws a runtime error with dart and a compile error with analyzer.

I've just filed [45519](https://github.com/dart-lang/sdk/issues/45519) regarding this.

Tests updated according the described above.

Now I see that the following test case does not throw any error both with analyzer and dart:

Now I see that the following code does not throw any error both with dart and analyzer:
``` dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A();
}
```
Still A is not well-bounded here, so should I file another bug regarding the analyzer and update the tests accordingly?

**Comment by eernstg** [comment]
Yes, the type obtained from i2b counts just as much as any manually written type, so when it is an error to do `A<G<C<dynamic>>>()` then it is also an error to do `A()`. The following error is detected by the analyzer, but not by the CFE:

```dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

main() {
  A<G<C<dynamic>>>();
}
```

**Comment by iarkh** [comment]
OK! 

@eernstg, One more (hopefully last) question - is the following code allowed:

``` dart
class C<X> {}
typedef G<X> = X Function(X);
typedef A<X extends G<C<X>>> = C<X>;

testme(A a) {}

main() {}
```
?

Now it passes with dart and throws a compile time error with analyzer on the `testme` function declaration, so is dart wrong here?

**Comment by eernstg** [comment]
The front end should report an error as well: The raw `A` means `A<G<C<dynamic>>>` and it's not well-bounded.
