### ISSUE TITLE
Skip is hard to maintain

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1058]
It would be helpful if all `Skip` directives in status files were triaged, and as many as possible were eliminated. Some of them can be changed:

- `Skip` can be changed to `SkipByDesign` in some cases. If the skip was introduced because of `int` semantics differences on web/non-web then we should ensure that there is both a web variant and a non-web variant of the test (that could be one test expecting compile-time errors, and another one which is executed).
-  `Skip # times out` should be `SkipSlow`.
- There may be other cases where `Skip` can systematically be eliminated by using something else.

This would bring us to a state where we can take another look at the remaining `Skip`s, and then see how we can get rid of them.

**Comment by sgrekhov** [comment]
https://dart-review.googlesource.com/c/sdk/+/194400
