### ISSUE TITLE
co19_2/Language/Mixins/Mixin_Application/deferred_t01 isn't testing the right thing

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1063]
This test is intended to test that there is a compile time error in certain situations with respect to deferred imports.  However, it contains an invalid use of a nonfunction type alias in the deferred library which is what is causing the actual compile time error (since nonfunction type aliases are not enabled in pre 2.13 Dart).

cc @eernstg

**Comment by sgrekhov** [comment]
This was fixed by 3642f24e2e6273c6fb65a8f60cd0edc95153942e. Now this test should work well
