### ISSUE TITLE
Possible issue with co19/Language/Mixins/Mixin_Application/deferred_t01

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1064]
This test is intended to test that certain uses of deferred types is an error.  Pre Dart 2.13 it was correctly issuing a compile time error, but only because it made use of nonfunction type aliases without passing the experiment flag.  With nonfunction  type aliases enabled, it seems to not cause an error.

@eernstg is this a bug in the CFE, or does the test need to be changed?

**Comment by sgrekhov** [comment]
Now this test produces an error in Analyzer and no errors in CFE.  What must be an expected result here?

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/sdk/issues/30273, the CFE needs to implement error reporting for cases where a deferred type is used in any of several ways where it is an error.

**Comment by sgrekhov** [comment]
Closing this issue as we agreed that this is a CFE issue
