### ISSUE TITLE
co19_2/Language/Classes/Getters/syntax_t08 use nonfunction type aliases

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1065]
Tests in co19_2 can't use nonfunction type aliases.  This test is expected to have a compile time error, but is doing so for the wrong reason.

**Comment by sgrekhov** [comment]
This test has been deleted already by  3642f24e2e6273c6fb65a8f60cd0edc95153942e. It's simply new co19_2 roll needed
