### ISSUE TITLE
co19 test shadowdom event failure

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#107]
Chrome 50 has changed which (if any) events are stopped at the shadow dom boundary.  co19 test

WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-004_t01

now fails the change event now bubbles form inside the shadow dom and up (outside of the shadow dom).  Use to be that only mouse, click, etc. could bubble up (the below JS code) behaves differently in Chrome 45 vs Chrome 50 (or Dartium 50).  The second event listener will fire and print to the console "change outside of shadow dom SHOULD NOT FIRE" in Chrome and Dartium 50 but will not print in Chrome 45.  Please change the test.

Javascript code:

    var d = document;
    var host = d.createElement('div');
    host.setAttribute('style', 'height:50%; width:100%');
    host.setAttribute('id', 'host');
    d.body.appendChild(host);

   var s = host.createShadowRoot();

    var inp1 = d.createElement('input');
    inp1.setAttribute('id', 'inp1');
    inp1.setAttribute('type', 'text');
    inp1.setAttribute('value', '12345');
    s.appendChild(inp1);

    var eventName = 'change';

    s.addEventListener(eventName, function(event) {
      console.log(eventName + ' in ' + event.target.getAttribute('id'));
    }, false);
    
    d.body.addEventListener(eventName, function(event) {
      console.log(eventName + " outside of shadow dom SHOULD NOT FIRE");
    }, false);

    var event = document.createEvent('UIEvents');
    event.initEvent(eventName, true, false);
    inp1.dispatchEvent(event);

**Comment by terrylucas** [comment]
All of these tests fail as well (abort, error, select, etc) all bubble up outside of the shadow dom.

WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-001_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-002_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-003_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-004_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-005_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-006_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-007_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-008_t01
WebPlatformTest/shadow-dom/events/events-that-are-always-stopped/test-009_t01

**Comment by sgrekhov** [comment]
Fixed in both master and strong-mode branches
