### ISSUE TITLE
co19/Language/Mixins/declaration_t01 has too many expectations

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/co19#1072]
The test in the subject line has both an @compile-error annotation and a static error expectation:

```
//             ^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
```

This confuses the test runner and causes spurious failures.

cc @eernstg @athomas

**Comment by eernstg** [comment]
Ah, that was the reason! I didn't notice that. ;-)
