### ISSUE TITLE
Incorrect LibTest/isolate/Isolate/pause_A01_t01.dart

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#1073]
The `LibTest/isolate/Isolate/pause_A01_t01.dart` test look like this
```dart
entryPoint(SendPort sendPort){
  Random random = new Random();
  int s = 0;
  while (true){
    s = -s + random.nextInt(100);
    sendPort.send(s);
  }
}

test() async {
  ReceivePort receivePort = new ReceivePort();
  ReceivePort onExit = new ReceivePort();
  Isolate isolate = await Isolate.spawn(
      entryPoint,
      receivePort.sendPort, // message
      onExit:onExit.sendPort,
      errorsAreFatal:true
  );
  isolate.pause();
  // check that messages are received from paused isolate
  int count = 0;
  await for (var _ in receivePort){
    if (count++==1000000){
      break;
    }
  }
```

This test spawns and pauses an isolate and then expects to have already received messages.

This flakily times out, because the isolate might be paused even before the `entrypoint` is invoked, therefore not allowing it to send any messages, therefor making the main isolate wait forever to receive messages.

**Comment by mkustermann** [comment]
There might be similar tests (not sure)

**Comment by sgrekhov** [comment]
@mkustermann thank you for pointing. Fixed test should check that isolate started producing events before pause it. But is there a reliable way to check that isolate started its work? I'm unable to find it

**Comment by mkustermann** [comment]
@sgrekhov The only way to see is to let the isolate send a message on a port that another side can listen to, then you know it has started the work

**Comment by sgrekhov** [comment]
@mkustermann please review https://github.com/dart-lang/co19/pull/1074
