### ISSUE TITLE
co19 test  fails under checked mode in Dartium

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#108]
WebPlatformTest/html/semantics/forms/textfieldselection/selection_t01 is wrong especially in checked mode.

Usage of assert_in_array the first arg el.selectionDirection is a String not a List .

    assert_in_array(el.selectionDirection, dirs, "SelectionDirection");

void assert_in_array(List actual, var expected, String description) {
   Expect.isTrue(expected.indexOf(actual) != -1, description);
}

**Comment by sgrekhov** [comment]
Fixed in master branch. No fix needed in strong-mode
