### ISSUE TITLE
co19/LanguageFeatures/Generic-functions-as-type-args/typedef2_A01_t14 needs parameter name

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1080]
Said test contains a declaration like this:

```dart
T Function<T>() testme1(T Function<T>()) => throw "Hello";
//                                     ^ Here
```

It is not expected to be an error, but there is no parameter name, so the parameter name should be added.

**Comment by eernstg** [comment]
typedef2_A01_t12 has the same problem.

**Comment by iarkh** [comment]
Parameter name issue has been fixed.
Seems like these tests need more changes according the [Issue 45718](https://github.com/dart-lang/sdk/issues/45718) evaluation.
