### ISSUE TITLE
Replace obsolete @compile-error expectations by static errors

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#1086]
Replace obsolete `@compile-error` and `@static-warning` expectations by static error expectations in all co19 tests

**Comment by sgrekhov** [comment]
@athomas should this issue affect `co19_2` as well?

**Comment by athomas** [comment]
Depends on how much work it is. If we can do this easily co19_2 as well, we should do this.

**Comment by sgrekhov** [comment]
@athomas I replaced all @compile-error and @static-warning by static errors in a master branch. Note that there are a few dozens a new test failures caused by https://github.com/dart-lang/sdk/issues/44990. 

If we want to update co19_2 as well then, I expect, It'll take me about one week to acomplish it. Most part of the work is done by the script but there are some corner cases that should be done manually. There are also a good portion of multitests that must be changed manually as well. Please confirm that I should update co19_2 tests as well
