### ISSUE TITLE
Expecting a process kill to fail is racy - e.g. co19_2/src/LibTest/io/Process/kill_A01_t02 

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#1089]
The test `co19_2/src/LibTest/io/Process/kill_A01_t02` (version we currently use in dart sdk), looks like:
```dart
void setCommand() {
  if (Platform.isLinux) {
    command = 'echo';
    args = ['-start'];
  }
  if (Platform.isWindows) {
    command = Platform.resolvedExecutable;
    args = ['--version'];
  }
}

main() {
  setCommand();
  asyncStart();
  Process.start(command, args).then((Process process) {
    bool pKill = process.kill();
    Expect.isFalse(pKill);

    process.exitCode.then((int value) {
      Expect.equals(0, value);
      if (Platform.isWindows) {
        asyncEnd();
      }   
    }); 
```

Since the process got actually started (the returned `Future<Process>` completed with a valid `Process`), killing it might or might not work, depending on how fast the subprocess dies. If it's still alive, the `kill` will be successfully returning `true`.

=> This makes this test flaky.

If at all, one should first wait for the exit code of the child process and only when the subprocess exited ensure killing it returns `false`.

**Comment by liamappelbe** [comment]
This test is still flaky: https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=co19_2/LibTest/io/Process/kill_A01_t02&configurations=dartkp-linux-release-x64

**Comment by sgrekhov** [comment]
@athomas please do co19_2 roll to enable the fix

**Comment by athomas** [comment]
Roll: https://dart-review.googlesource.com/c/sdk/+/200860
