### ISSUE TITLE
co19 test combining-marks-position_t01 can be off by exactly 2 pixels on Mac

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#109]
Change LayoutTests/fast/text/international/combining-marks-position_t01

change line

    Expect.isTrue(diff1 < 2 && diff2 < 2, '''

to

    Expect.isTrue(diff1 < 3 && diff2 < 3, '''

**Comment by sgrekhov** [comment]
Fixed in both master and strong-mode branches
