### ISSUE TITLE
Flaky `LibTest/isolate/Isolate/ping_A03_t02.dart` test.

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#1095]
This test looks as follows:
```dart
entryPoint(message) {
  Random random = new Random();
  int s = 0;
  while (true) {
    s = -s + random.nextInt(100);
  }
}

Future test(List<Object?> values) async {
  ReceivePort onExit = new ReceivePort();
  Isolate isolate = await Isolate.spawn(entryPoint, null, // message
      onExit: onExit.sendPort,
      errorsAreFatal: true);
  // check
  List<Future> pingResponses = [];
  for (Object? value in values) {
    ReceivePort pingPort = new ReceivePort();
    isolate.ping(pingPort.sendPort,
        response: value, priority: Isolate.beforeNextEvent);
    Future pingResponse =
        pingPort.first.timeout(TWO_SECONDS, onTimeout: () {
      pingPort.close();
      return "timeout";
    });
    pingResponses.add(pingResponse);
  }
  for (var response in await Future.wait(pingResponses)) {
    Expect.equals("timeout", response);
  }
  // clean up
  isolate.kill(priority: Isolate.immediate);
  await onExit.first;
  asyncEnd();
}
```

Sometimes one of the pings doesn't result in a timeout, the reason for that is that this test is racy: `await Isolate.spawn()` returns when the isolate was created, not when the isolate's `entrypoint` function has been invoked. Therefore there is a small time window when the isolate is created, receives a ping, responds to the ping and then invokes the `entrypoint`, which can  make this test fail.

A more robust test would make the `entrypoint` send a message inside it's main function that it's ready to do the synchronous loop, then the main isolate can expect `ping`s to timeout. Since the isolate is in an infinite synchronous loop.

**Comment by aam** [comment]
see https://github.com/dart-lang/sdk/issues/45111.
I raised it with assumption that vm isolate message processing is racy, not that there is anything wrong the test.
