### ISSUE TITLE
AppendHtml sanitizes its contents, making many tests fail

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#11]
This is a copy of issue 747 from the old co19 issue tracker.
Many many tests are failing because of this.

Many co19 tests rely on appendHtml not sanitizing	‹ Prev 24 of 24
1 person starred this issue and may be notified of changes.	Back to list
Status: 	New
Owner: 	----
Type-Defect
Priority-Medium

 	
Reported by alanknight@google.com, May 5, 2015
AppendHtml now sanitizes, and as a result these tests fail. Possibly the simplest thing would be to define a utility function that passes a null sanitizer and change all these tests to call that instead.

Affected tests:

Many things under the following categories. See the suppressions files. Note that this includes test that spuriously pass because the content they try to add is sanitized away, and the tests don't exercise anything.

co19/LayoutTests/fast/multicol/
co19/LayoutTests/fast/media/
co19/LayoutTests/fast/loader/
co19/LayoutTests/fast/lists/
co19/LayoutTests/fast/innerHTML/
co19/LayoutTests/fast/inline
co19/LayoutTests/fast/text
co19/LayoutTests/fast/text/international/
co19/LayoutTests/fast/url
co19/LayoutTests/fast/writing-mode
co19/LayoutTests/fast/text-autosizing
co19/LayoutTests/fast/html/adjacent-html-context-element_t01

Details: (please list relevant API changes or quote specification)

https://code.google.com/p/dart/issues/detail?id=23235

**Comment by sgrekhov** [comment]
Fixed. See f6d34cbdeab09a696dac615bd1b733bba2f573c5, 457002d487ac7e9942cbafb51757b20815e20e88, f2e1b62721ab5016e6a1c68bd2c669443254e8f0 and 40990b1ad50ed1fb31fc6cda6a6186c8d8f2db0e
