### ISSUE TITLE
co19[_2]/src/LibTest/io/Link/watch_A01_t01 tests seems to be invalid 

### ISSUE THREAD

**Issue by aam** [dart-lang/co19#1100]
The tests are written with assumption that retargeting watched link triggers file watch notification when watcher is set up on the link itself(https://github.com/dart-lang/co19/blob/master/LibTest/io/Link/watch_A01_t01.dart#L31) , which it doesn't. So the tests is failing on all platforms.

**Comment by aam** [comment]
left few comments on https://github.com/dart-lang/co19/commit/8c5ac5e82f8610fd5a3043e0e33618d569ec7ebf regarding issues that might be responsible for further flakiness of the tests.

cc @a-siva

**Comment by sgrekhov** [comment]
@aam thank you. I updated the test in both co19 and co19_2 branches. Feel free to reopen it if still there are any issues with the test.
