### ISSUE TITLE
LibTest/io/FileStat/stat_A02_t01.dart uses wrong type for onError

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/co19#1104]
https://github.com/dart-lang/co19/blob/bd1a423957e5e46c0262b1a382f77e58265ebcd1/LibTest/io/FileStat/stat_A02_t01.dart#L36-L38

```
Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a value of the returned future's type: Closure: (FileStat) => Null
#0      Future.then (dart:async/future_impl.dart:341:9)
#1      _main (.../LibTest/io/FileStat/stat_A02_t01.dart:28:34)
#2      inSandbox (.../LibTest/io/file_utils.dart:22:22)
#3      main (.../LibTest/io/FileStat/stat_A02_t01.dart:21:9)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by sgrekhov** [comment]
@cskau-g @eernstg I've fixed this issue, but... Why, before the fix, it was an error in CFE and only hint in analyzer?
```
Analyzing stat_A02_t01.dart...
hint - The argument type 'Null Function(FileStat)' can't be assigned to the parameter type 'void Function(Object)' or 'void Function(Object, StackTrace)'. - stat_A02_t01.dart:36:6 - argument_type_not_assignable_to_error_handler
1 hint found. 
```
Is there an appropriate issue for the analyzer?

**Comment by eernstg** [comment]
The error message which is emitted at run-time is most likely from [here](https://github.com/dart-lang/sdk/blob/866157762ca810e0ff2ae63998e768fa1b83d7da/sdk/lib/async/future_impl.dart#L341), and it's created based on manually written code (so it's not a type check which is specified as part of the language, it is a type check which was designed by the author of those few lines of code).

So the vm error has nothing to do with the CFE type check, and there are no compile-time errors at all.

We would then expect that there are no diagnostic messages from the analyzer at all, we're passing a function to a parameter of type `Function?`, and that's fine.

However, the analyzer seems to give this particular situation (passing an `onError` to `then` of a `Future`) a very special treatment: It "knows" that the body of this particular method (at least when it's the platform type `_Future`) will perform that particular "manual type check", and it is then doing a similar thing at compile-time, checking whether the static type of the argument is statically known to pass this test.

So it's a very special case, and it is no problem that the analyzer emits this very special-cased hint, and it is also no problem that the CFE doesn't. The run-time error is a completely separate thing, and there is no reason to think that it works incorrectly.

**Comment by sgrekhov** [comment]
Thank you for the explanation.
