### ISSUE TITLE
Invalid function tearoff tests

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#1105]
The tests `co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t02`/`t04`/`t06`/`t08`/`t10` have a pattern that doesn't give the intended result.

For instance `function_tearoffs_A02_t02`:
```Dart
class C {
  var x;
  C() {
    x = instanceMethod<int>;
  }
  T instanceMethod<T>(T t) => t;
}

main() {
  C c = new C();
  c.x(3.14);
//    ^^^^
// [analyzer] unspecified
// [cfe] unspecified
  c.x<double>(42);
//   ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
}
```
Here the test attempts to check that the type of `C.x` is `int Function(int)`, as indicated by the expected errors.

Alas, the declaration `var x;` without a direct initializer results in the inferred type for `x` being `dynamic`, meaning that no error occurs on the expected lines.

Instead, the tests could rewritten to use this pattern:
```Dart
class C {
  C() {
    var x = instanceMethod<int>;
    x(3.14);
//    ^^^^
// [analyzer] unspecified
// [cfe] unspecified
    x<double>(42);
//   ^^^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
  }
  T instanceMethod<T>(T t) => t;
}

main() {
  new C();
}
```
which will result in `x` being inferred to have the intended type and therefore creating the expecting errors, while still, as intended, testing explicit instantiation of instance methods.

@lrhn Do you agree with the assessment?

**Comment by lrhn** [comment]
I agree. You won't get static errors from calling `dynamic x;`. The rewrite looks fine. 
It retains that the unqualified instantiated instance method tear-off is tested. Doesn't have to happen in the constructor, but it saves adding another method.
