### ISSUE TITLE
Need to get rid from old-style compile error comments in pre-nnbd and master

### ISSUE THREAD

**Issue by iarkh** [dart-lang/co19#1107]
We need to get rid from old-style comments in pre-nnbd and master, like the following:

`  A<Object>  a4;      //# 01: compile-time error
`

**Comment by sgrekhov** [comment]
Fixed in master branch. As for co19_2 (pre-nnbd branch) it was agreed that it doesn't make sense to spend efforts on replacing of multitests in this branch. @athomas, please let us know if it isn't so
