### ISSUE TITLE
Test the intended property in co19/Language/Classes/Getters/static_getter_t03.dart

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1114]
Cf. https://github.com/dart-lang/co19/issues/1093#issuecomment-852846513, it would be good if this test could be adjusted (changing `int v = 42;` to `set v(_) {}`) such that we're actually testing 'It is a compile error if a class declares a static getter named v and also has a non-static setter named v =.'

**Comment by iarkh** [comment]
There is already such a test - this is [co19/Language/Classes/Getters/static_getter_t01.dart](https://github.com/dart-lang/co19/blob/master/Language/Classes/Getters/static_getter_t01.dart).

Should we just remove static_getter_t03.dart?

**Comment by sgrekhov** [comment]
[co19/Language/Classes/Getters/static_getter_t01.dart](https://github.com/dart-lang/co19/blob/master/Language/Classes/Getters/static_getter_t01.dart) tests exactly what is requested. This tests, tests that the case when instance setter is declared implicitly. I believe, this issue can be closed. Feel free to reopen it
