### ISSUE TITLE
Updates for Constructor Tear Offs tests are required

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/co19#1124]
It seems some tests for the Constructor Tear Offs feature need to be updated. I investigated the tests, and my observations are in the following table.

<google-sheets-html-origin>

test name | test status | test file
-- | -- | --
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t02 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t04 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t04.dart
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t06 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t06.dart
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t08 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t08.dart
co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t10 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A02_t10.dart
co19/LanguageFeatures/Constructor-tear-offs/goal_A01_t02 | error in test: the test contains reportable compile-time errors, but doesn't expect it. NOTE: It seems that it's an typo: lines 60 and 63 should say constr2 instead of constr1. | tests/co19/src/LanguageFeatures/Constructor-tear-offs/goal_A01_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/goal_A01_t03 | error in test: the test contains reportable compile-time errors, but doesn't expect it. NOTE: It seems that it's a typo: some lines should say constr2 instead of constr1. Also, some lines pass dynamic as type argument where the bound is num. | tests/co19/src/LanguageFeatures/Constructor-tear-offs/goal_A01_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A01_t03 | error in test: an instance getter is called on the class instead of the object of the class. Typo? | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A01_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02 | error in test: the form C.constr< int > is used instead of C< int >.constr | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t02 | error in test: static getter is invoked on an instance object | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t03 | errors in test: static getter is invoked onan instance object; attempt to tear off a constructor from a type literal | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t03 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t15 | errorr in test: a string passed where int was expected | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t15.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A07_t03 | the test passes, but I believe some lines should reference constr2 instead of constr1. Otherwise, constr2 case isn't tested at all. | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A07_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01 | error in test: invocation of a tear-off of a const constructor is assumed to be a const expression | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02 | error in test: invocation of a tear-off of a const constructor is assumed to be a const expression | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t03 | error in test: call a torn off constructor with wrong number of arguments | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t04 | error in test: call a torn off constructor with wrong number of arguments | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t04.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_t09_A03 | error in test: the form C.new< int > instead of C< int >.new is used | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_t09_A03.dart
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_t10_A01 | error in test: the form C.new< int > instead of C< int >.new is used | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_t10_A01.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t01 | error in test: typo: MytList instead of MyList | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t01.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t02 | error in test: typo: MytList instead of MyList | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A02_t02.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t05 | error in test: it is statically ok, but will fail at run time because it compares a List< int > with List< num > for equality | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t05.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t06 | error in test: passing a string where an int is expected. The test doesn't expect that compile-time error. | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t06.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t07 | error in test: attempt to tear a constructor off a type literal | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t07.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t01 | error in test: typo: MytList instead of MyList | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A04_t01.dart
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A06_t01 | error in test: missing SharedOptions=--enable-experiment=constructor-tearoffs | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A06_t01.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A02_t01 | error in test: typo: Expect.Equals is used instead of Expect.equals | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A02_t01.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t03 | the test passes statically, but will fail at run time: the expected values will most likely mismatch | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t03.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t04 | error in test: the form A.new< int >(...) is used instead of A< int >.new(...) | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t04.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t05 | error in test: the form A.new< int >(...) is used instead of A< int >.new(...) | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t05.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t06 | error in test: the form A.new< int >(...) is used instead of A< int >.new(...) | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t06.dart
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A05_t02 | error in test: the form C.new< int > is used instead of C< int >.new | tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A05_t02.dart

**Comment by sgrekhov** [comment]
@stefantsov thank you for pointing at these issues. Some of them were already fixed, some I've just fixed. But, please, clarify the following failures

test name | test status | test file | Question
-- | -- | -- | --
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t03 | error in test: it expects compile-time errors where they shouldn't be reported | tests/co19/src/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t03.dart | Where exactly excessive errors are expected? 
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t05 |	error in test: it is statically ok, but will fail at run time because it compares a List< int > with List< num > for equality | tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t05.dart | I believe it was about tearing_off_from_typedef_A03_t04.dart. At least I fixed this test instead :) 
co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t07 |	error in test: attempt to tear a constructor off a type literal |	tests/co19/src/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t07.dart | I don't see it. Where exactly in the test we are tearing off from a type literal?
co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t03 |	the test passes statically, but will fail at run time: the expected values will most likely mismatch |	tests/co19/src/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t03.dart | I don't see anything that may produce a runtime error here. Is there an error log?

**Comment by stefantsov** [comment]
Thanks for fixing the tests, @sgrekhov! Here are my comments.

### co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A04_t03

The following line should not result in a compile-time error.

```dart
  C Function(Never) v8 = C.constr;
```

### co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t05

Yes, you are right, it was about tearing_off_from_typedef_A03_t04.dart :)

### co19/LanguageFeatures/Constructor-tear-offs/tearing_off_from_typedef_A03_t07

In the following line `(MyList<num>)` is treated as a type literal by the compiler because of parentheses.

```dart
  var v3 = (MyList<num>).filled;
```

### co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A03_t03

You are right. The test is ok. Sorry for the false signal!

**Comment by sgrekhov** [comment]
@stefantsov thank you!
