### ISSUE TITLE
Weird line endings in many co19 tests

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/co19#113]
I've noticed a number of co19 tests with weird line endings.

For example, `Language/Expressions/Identifier_Reference/built_in_not_dynamic_t01.dart`.

This is very confusing. When I `cat` this file, I see this:

```
main() {
} abstract foo;
```

However, the content of the file is really:

```
main() {
abstract foo;\r}
```

**Comment by sgrekhov** [comment]
Fixed by 0a0b3a4ef2a9f6d1765e1bdfe579af9db0bc961e
