### ISSUE TITLE
Some LibTest/io/Process tests now fail on Windows due to `--version` outputting to `stdout` instead of `stderr`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/co19#1134]
As of https://github.com/dart-lang/sdk/commit/cccc0293c540ebee7116d98ef6cb24c1caf9512e, `dart --version` now prints the Dart VM version to `stdout` instead of `stderr`. Some tests under LibTest/io/Process on Windows execute `dart --version` to test process spawning and check that `stderr` is not empty, which is now incorrect.

**Tests that are failing on Windows:**
LibTest/io/Process/runSync_A01_t01 RuntimeError (expected Pass)
LibTest/io/Process/runSync_A02_t01 RuntimeError (expected Pass)
LibTest/io/Process/runSync_A02_t02 RuntimeError (expected Pass)
LibTest/io/Process/run_A01_t01 RuntimeError (expected Pass)
LibTest/io/Process/run_A02_t01 RuntimeError (expected Pass)
LibTest/io/Process/run_A02_t02 RuntimeError (expected Pass)
LibTest/io/Process/start_A04_t01 RuntimeError (expected Pass)
LibTest/io/Process/start_A06_t01 RuntimeError (expected Pass)

See https://github.com/dart-lang/sdk/issues/46845.

**Comment by sgrekhov** [comment]
Fixed in both `co19` and `co19_2`
