### ISSUE TITLE
Language/Libraries_and_Scripts/Scripts/top_level_main_t01.dart is a fork bomb on AOT

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1137]
The test used `Platform.resolvedExecutable` with the intention of finding the `dart` executable but on AOT configurations this will be `out.snapshot` (the test as AOT compiled executable), so the test starts a process of itself which starts a process of itself...

This causes Windows bots to run out of memory when running the test and Linux bots to timeout the test.

**Comment by athomas** [comment]
https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/Scripts/top_level_main_t06.dart follows a similar pattern.

**Comment by athomas** [comment]
simarm64 is also affected by the fork bomb somehow.

**Comment by sgrekhov** [comment]
Problem here was not in use of `Platform.resolvedExecutable` on AOT configuration but in test itself. `Platform.resolvedExecutable`  in case of AOT is `.../sdk/out/ReleaseX64/dart_precompiled_runtime`.  But the tests tries to run the script in another file `top_level_main_t01_lib.dart`. To do that it did 
```
String eScript = Platform.script.toString().replaceAll(".dart", "_lib.dart");
```
And then tried to run `eScript`. But in case of AOT `Platform.script` == `.../sdk/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/tests_co19_src_Language_Libraries_and_Scripts_Scripts_top_level_main_t01/out.aotsnapshot`, so replacement didn't work and the test run itself once again. And again, and again...

To fix added '// OtherResource=top_level_main_t01_lib.dart' flag and check for the executable name. If it is not a `dart` then this is a case of AOT configuration and script and executable names must be adjusted
