### ISSUE TITLE
Incorrect expectations in co19/LanguageFeatures/Constructor-tear-offs/summary_A01_t01

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/co19#1141]
The test verifies that constructor tear-offs have the certain function types:

https://github.com/dart-lang/co19/blob/ef018b98d489249b9f79d1d7ddbfefb8cf1580ff/LanguageFeatures/Constructor-tear-offs/summary_A01_t01.dart#L26-L29

https://github.com/dart-lang/co19/blob/ef018b98d489249b9f79d1d7ddbfefb8cf1580ff/LanguageFeatures/Constructor-tear-offs/summary_A01_t01.dart#L32-L39

There are a couple of problems with these typedefs:

1. `Func1` and `Func3` declare generic type aliases to non-generic function types. For example, declaration of `Func1` in the new syntax is equivalent to
```dart
typedef Func1<T> = List<T> Function(int i, T t);
```
As a result, `is Func1` instantiates type parameter of generic `Func1` with default `dynamic`, and the type check is actually testing `is List<dynamic> Function(int i, dynamic t)`. Constructor tear-off is a generic function, and it doesn't pass type test against non-generic function type.

Instead, `Func1` should be declared as a non-generic alias to a generic function type:
```dart
typedef Func1 = List<T> Function<T>(int i, T t);
```

2. `Func3` and `Func4` are used to test types of `ListList.filled` and `ListList<int>.filled`, where 
https://github.com/dart-lang/co19/blob/ef018b98d489249b9f79d1d7ddbfefb8cf1580ff/LanguageFeatures/Constructor-tear-offs/summary_A01_t01.dart#L24

However, they do not properly substitute type parameter `E` of List  to `List<T>` or `List<int>` for the 2nd argument (`E fill`) of List.filled. They use `T` or `int` which is not correct.

These type aliases can be corrected in the following way:
```dart
typedef Func3 = List<List<T>> Function<T>(int i, List<T> t);
typedef List<List<int>> Func4(int i1, List<int> i2);
```

**Comment by sgrekhov** [comment]
@alexmarkov thank you for the explanation!
