### ISSUE TITLE
Static members should not be visible on the type object

### ISSUE THREAD

**Issue by floitschG** [dart-lang/co19#115]
As discussed in https://github.com/dart-lang/sdk/issues/23721, static members of a class should not be accessible through its `Type` object.

The SDK issue stays open until the spec explains this in a better (less convoluted) way, however the tests should get updated.

Affected tests:
```
Language/Classes/Getters/type_object_t01
Language/Classes/Getters/type_object_t02
Language/Classes/Setters/type_object_t01
Language/Classes/Setters/type_object_t02
Language/Classes/Static_Methods/type_object_t01
Language/Classes/Static_Methods/type_object_t02
```

**Comment by sgrekhov** [comment]
Thank you. Fixed
