### ISSUE TITLE
named_constructor_A02_t02.dart has incorrect expectations

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#1159]
`LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart` is currently failing due to https://github.com/dart-lang/sdk/issues/46888.  Once that issue is fixed, some additional changes will need to be made to the test itself to get it to pass.  Here are the changes I believe are needed:

```
diff --git a/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart b/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart
index 0409602cce..20683888e8 100644
--- a/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart
+++ b/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02.dart
@@ -22,7 +22,7 @@ class C<T> {
 }
 
 main() {
-  Expect.isTrue(C.constr is C Function<X extends dynamic>(X));
-  Expect.isTrue(C<int>.constr is C Function<X extends int>(X));
-  Expect.isTrue((C.constr)<int> is C Function<T extends int>(T));
+  Expect.isTrue(C.constr is C<X> Function<X extends dynamic>(X));
+  Expect.isTrue(C<int>.constr is C<int> Function(int));
+  Expect.isTrue((C.constr)<int> is C<int> Function(int));
 }
```
Rationale: `C<int>.constr` is a tearoff of the `constr` constructor from the class `C<int>`, therefore it is a non-generic function that accepts an `int` and returns an instance of `C<int>`.

Similarly, `(C.constr)<int>` is an instantiation of the generic tear-off `C.constr` (which has type `C<X> Function<X extends dynamic>(X)`).  Therefore it is a non-generic function that accepts an `int` and returns an instance of `C<int>`.

In the diff above I also took the liberty of making the return type for `C.constr` more specific, changing it from `C` to `C<X>`.  The test would pass without changing this line, but would be a less stringent test so it seems like it's worth improving it.

**Comment by sgrekhov** [comment]
@stereotype441 thank you!
