### ISSUE TITLE
Fix co19 test on timing test.

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#116]
See Issue from https://github.com/dart-lang/sdk/issues/289

I think I've seen it at least once before but here is the latest failure log. It seems like an issue could be in a too strict timeout expectation.

FAILED: none-dartium-checked release_x64 co19/LayoutTests/fast/css/max-device-aspect-ratio_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[dartium]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.135
        },
        {
              type: print
              value: unittest-suite-wait-for-done
              timestamp: 0.136
        },
        {
              type: print
              value: dart-main-done
              timestamp: 0.371
        },
        {
              type: message_received
              value: dart-calling-main
              timestamp: 0.372
        },
        {
              type: message_received
              value: unittest-suite-wait-for-done
              timestamp: 0.372
        },
        {
              type: message_received
              value: dart-main-done
              timestamp: 0.373
        },
        {
              type: window_onerror
              value: window.onerror called: 
                    
                    http://127.0.0.1:49934/root_build/generated_tests/none-dartium-checked/short8953_ss_max-device-aspect-ratio_t01/test.html?crossOriginPort=49936:1:
                    Uncaught Unhandled exception:
                    Expect.fail('Stylesheet did not load in 1.0 second(s).')
                    #0      _fail (http://127.0.0.1:49934/root_dart/tests/co19/src/Utils/expect.dart:17:5)
                    #1      Expect.fail (http://127.0.0.1:49934/root_dart/tests/co19/src/Utils/expect_common.dart:79:5)
                    #2      testFailed (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/testcommon.dart:102:31)
                    #3      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:31:7)
                    #4      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #5      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #6      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #7      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #8      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #9      main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #10     main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #11     main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #12     main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #13     main.waitForStylesheetLoad (http://127.0.0.1:49934/root_dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart:35:37)
                    #14     Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
                    #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
                    #16     _Timer._Timer.<anonymous closure> (dart:html:49221)
                    
                    
              timestamp: 0.583
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 0.583
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /E:/b/build/slave/dartium-win-ia32-inc-be/build/src/dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    <link rel="stylesheet" media="screen and (max-device-aspect-ratio: 100/1)" href="/root_dart/tests/co19/src/LayoutTests/fast/css/resources/device-aspect-ratio.css"></head>
                    <body><p id="description"><span><p>This text is green if the max-device-aspect-ratio media query works properly.</p></span></p><div id="console"></div>
                      <h1> Running /E:/b/build/slave/dartium-win-ia32-inc-be/build/src/dart/tests/co19/src/LayoutTests/fast/css/max-device-aspect-ratio_t01.dart </h1>
                      <script type="text/javascript" src="/root_dart/tools/testing/dart/test_controller.js">
                      </script>
                      <script type="application/dart" src="/root_build/generated_tests/none-dartium-checked/short8953_ss_max-device-aspect-ratio_t01/test.dart" onerror="scriptTagOnErrorCallback(null)" defer="">
                      </script>
                      <script type="text/javascript" src="/root_dart/pkg/browser/lib/dart.js"></script>
                    
                    </body>
              timestamp: 0.583
        },
  ]
  

stderr:

BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  

To retest, run:  E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\sdks\win\dart-sdk\bin\dart.exe E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\testing\dart\http_server.dart -p 49934 -c 49936 --build-directory=E:\b\build\slave\dartium-win-ia32-inc-be\build\src\out\Release\ --runtime=dartium --packages=E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\.packages

Command[dartium]: E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\sdks\win\dart-sdk\bin\dart.exe tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:49934/root_build/generated_tests/none-dartium-checked/short8953_ss_max-device-aspect-ratio_t01/test.html?crossOriginPort=49936
Took 0:00:00.601067

Short reproduction command (experimental):
    python tools/test.py -mrelease -rdartium --checked -t60 co19/LayoutTests/fast/css/max-device-aspect-ratio_t01

**Comment by sgrekhov** [comment]
Fixed in master and strong-mode branches
