### ISSUE TITLE
Function invocation is not a constant

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1166]
The tests `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01` and `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02` contain expressions of the form `v(...)` where `v` is a constant variable whose value is a constructor tearoff, and these expressions are used to initialize a constant variable.

This is an error, because invocation of a function (tearoff or not) is never a constant expression. (Exception: `identical(_, _)` can be constant), so several declarations named `c1 .. c6` need to be changed to non-constant.

**Comment by iarkh** [comment]
[Spec proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) reads:
> An instantiated tear-off is constant and canonicalized if the instantiating types are constant, and not even equal if the types are not constant.

Doesn't it mean that `v1`, `v2`, etc. can be declared as `const` in the test? @eernstg, could you please clarify?
If this is not so - which test should be written to test the assertion above?

**Comment by eernstg** [comment]
Yes, `v1` can be declared as a constant variable, but `v1(3, 14)` is not a constant expression, so `c1` cannot be declared as a constant variable.
