### ISSUE TITLE
Syntax error isn't marked as an error in a test for Constructor Tear Offs feature

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/co19#1168]
The following line in the test has type arguments coming after the constructor name which should be treated as an error.

https://github.com/dart-lang/co19/blob/6cb0670b42ddd2a74d65f7d69213af76ef5f8ac9/LanguageFeatures/Constructor-tear-offs/syntax_t01.dart#L29

/cc @eernstg

**Comment by eernstg** [comment]
Agreed, this is an error. However, it is not a syntax error:

```ebnf
<expression> ->* <postfixExpression> -> <primary> <selector>*.
<primary> -> <constructorTearoff> -> <typename> '.' 'new' ->* 'C' '.' 'new'.
<selector>* -> <selector> -> <typeArguments> ->* '<' 'int' '>'.
```

So we can't reject the term based on the grammar rules, but we can reject `C.new<int>` when we have parsed it, because `C.new` is a constructor tearoff, and they don't admit a `<typeArguments>` selector.
