### ISSUE TITLE
Various errors in constructor tear-off tests

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#1175]
Various errors in constructor tear-off tests:

In `co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A08_t03` line 54 `a<b, c>.toString()` is expected to be a call to `toString()` on the type literal `a<b, c>`, but as with https://github.com/dart-lang/co19/issues/1153 this should be interpreted as constructor invocation.

In `co19/LanguageFeatures/Constructor-tear-offs/callable_objects_instantiation_A02_t01` line 27 and `co19/LanguageFeatures/Constructor-tear-offs/callable_objects_instantiation_A02_t02` line 25 `C.call<int>` is expected to be either the explicit instantiation of the non-generic `C.call` instance method or a constructor tear off of the `call` method. Neither is valid, since `call` is neither a static member nor a constructor and therefore cannot be accessed by `C.call`.

In multiple lines in  `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t02` and `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t03`, the named constructor `C.constr` is attempted to be torn off with the syntax `(C<dynamic>).constr`. This, though, is the access off the member `constr` on the type literal `C<dynamic>`.

In `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A07_t07` line 21, the constructor `C.name1` is declared with reference to a type variable `T`. The class doesn't have a type variable `T` but instead has type variables `T1`, `T2`, and `T3`.

In `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01` and `co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02` constants are attempt to be created through invocation of constructor tear offs, like `const c1 = v1(3, 14)`. Invocation of a constructor tear off is not a constant expression, even if the constructor is constant.

In `co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A05_t02` line 27 a function type `C Function<T extends int>(int i, X d)` accidentally declares its own type variable as `T` and not `X`, leading to undefined types `X`.

In `co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A07_t02` line 26 and `co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A07_t04` line 26 a redirecting factory is attempt to be defined through a top level variable `Dnew` which is an alias of a constructor tear off. This declaration is not valid. Only typedefs can be used as aliases in redirecting factory constructors.

Also in `co19/LanguageFeatures/Constructor-tear-offs/unnamed_constructor_A07_t04`, but in line 18, there is a missing argument in the super constructor call `super.new()`.

**Comment by sgrekhov** [comment]
These issues are mainly already fixed. Only the first issue was not fixed yet. Now let's wait for the roll https://dart-review.googlesource.com/c/sdk/+/211581
