### ISSUE TITLE
Failures on [co19] Roll co19 to 9d2a922a9cdb3b200427e5fac9fbaa739a67aa65

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#1176]
There are new test failures on [[co19] Roll co19 to 9d2a922a9cdb3b200427e5fac9fbaa739a67aa65](https://dart-review.googlesource.com/c/sdk/+/211581).

The tests
```
co19/Language/Generics/syntax_t34 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A09_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t02 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t03 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t01 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A21_t01 MissingCompileTimeError (expected Pass)
    and 32 more tests
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-strong-mac
analyzer-asserts-strong-win
analyzer-asserts-weak-linux
analyzer-asserts-weak-mac
analyzer-asserts-weak-win
cfe-strong-linux
cfe-strong-mac
cfe-strong-win
cfe-weak-linux
cfe-weak-mac
cfe-weak-win
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-weak-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartdevk-weak-linux-release-chrome
dartk-strong-linux-debug-ia32
dartk-strong-linux-debug-x64
dartk-strong-linux-release-ia32
dartk-strong-linux-release-simarm
dartk-strong-linux-release-simarm64
dartk-strong-linux-release-x64
dartk-strong-mac-debug-arm64
dartk-strong-mac-debug-x64
dartk-strong-mac-release-arm64
dartk-strong-mac-release-x64
dartk-strong-win-debug-x64
dartk-strong-win-release-ia32
dartk-strong-win-release-x64
dartk-weak-asserts-linux-debug-ia32
dartk-weak-asserts-linux-debug-x64
dartk-weak-asserts-linux-release-ia32
dartk-weak-asserts-linux-release-simarm
dartk-weak-asserts-linux-release-simarm64
dartk-weak-asserts-linux-release-x64
dartk-weak-asserts-mac-debug-arm64
dartk-weak-asserts-mac-debug-x64
dartk-weak-asserts-mac-release-arm64
dartk-weak-asserts-mac-release-x64
dartk-weak-asserts-win-debug-x64
dartk-weak-asserts-win-release-ia32
dartk-weak-asserts-win-release-x64
dartkp-strong-linux-debug-x64
dartkp-strong-linux-release-simarm64
dartkp-strong-linux-release-x64
dartkp-strong-mac-release-simarm64
dartkp-strong-win-release-x64
dartkp-weak-asserts-linux-debug-x64
dartkp-weak-asserts-linux-release-simarm64
dartkp-weak-asserts-linux-release-x64
dartkp-weak-asserts-mac-release-simarm64
dartkp-weak-asserts-win-release-x64
```

**Comment by whesse** [comment]
I think Unipro will take a first stab at triaging these issues and investigating, but others may want to take a look as well.

@sgrekhov @eernstg @leafpetersen @devoncarew

**Comment by eernstg** [comment]
@sgrekhov, I can see that you're triaging these failures&mdash;thanks! Then we can take a look at the tricky corner cases as needed, based on separate issues.

**Comment by sgrekhov** [comment]
@whesse  Failures triaged

analyzer... |  
-- | --
new test -> MissingCompileTimeError (expected Pass) |  
co19/Language/Generics/syntax_t34 | Fixed
analyzer...cfe... |  
new test -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/regression/34741_t01 | Fixed
analyzer...cfe...dart2js...dartdevk...dartk...dartkp... |  
new test -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/regression/34482_t01 | Fixed
co19/LanguageFeatures/regression/35114_35115_t01 | Issues 35114, 35115
analyzer... |  
Pass -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t02 | Fixed
analyzer...cfe... |  
Pass -> MissingCompileTimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A09_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A13_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A14_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A15_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A21_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A22_t01 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A23_t01 | Fixed
analyzer...cfe...dartk...dartkp... |  
Pass -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A12_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A16_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A17_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A18_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A19_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A20_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A21_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A21_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A22_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A22_t03 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A23_t02 | Fixed
co19/LanguageFeatures/Constructor-tear-offs/ambiguities_A23_t03 | Fixed
cfe... |  
Pass -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02 | Fixed
dart2js... |  
CompileTimeError -> Crash (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/goal_A01_t03 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t02 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t03 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A07_t07 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/summary_A02_t01 | Works on the edge version of SDK
co19/LanguageFeatures/Constructor-tear-offs/syntax_t01/none | Works on the edge version of SDK
CompileTimeError -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/summary_A03_t04 | Fixed
dartdevk... |  
CompileTimeError -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/goal_A01_t03 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t02 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A03_t03 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A07_t07 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t02 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/summary_A02_t01 | UnimplementedError
co19/LanguageFeatures/Constructor-tear-offs/syntax_t01/none | UnimplementedError
new test -> RuntimeError (expected Pass) |  
co19/LanguageFeatures/regression/33786_t01 | Issue 33786
dartk... |  
new test -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/regression/33786_t01 | Issue 33786
dartk...dartkp... |  
RuntimeError -> CompileTimeError (expected Pass) |  
co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A02_t02 | Fixed
