### ISSUE TITLE
Test adjustments connected to https://github.com/dart-lang/sdk/issues/35114

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1178]
In dart-lang/sdk#35114, an example program has one fault without null safety (it should expect an error on line 11) and two faults with null safety (it should expect an error on line 10 and on line 11).

It seems likely that some co19 and/or co19_2 tests need adjustment to expect those errors.

**Comment by eernstg** [comment]
Here's one: co19/LanguageFeatures/regression/35114_35115_t01.

**Comment by iarkh** [comment]
Fixed in master branch.
In pre-nnbd the test is already OK and expect one compile error.
