### ISSUE TITLE
Use of int vs double for runtime check

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#1181]
The test `co19/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A01_t04` tries to use the distinction between `int` and `double` at runtime. This doesn't work for web-backends because they use JavaScript number semantics.

The test has 
```Dart
T id<T>(T value) => value;
var idInt = id<int>;

main() {
  dynamic v = 42;
  var i = idInt(v);
  Expect.isTrue(i is int);
  Expect.isFalse(i is double); // to check that i is not dynamic
}
```
The last test fails on web-backends because all integers are also doubles.

Also, the test doesn't really test anything, because the runtime type of the value `42` never changes. A better test might be to call `idInt` with something non-`int`, like `idInt("")` to check that it create a type error that `""` is not an `int`.

**Comment by sgrekhov** [comment]
Fixed. 
The following tests does call `idInt("String")` and expects an error
https://github.com/dart-lang/co19/blob/9c8c4d9bb61a52e1d12a09a531a246b0ad418a31/LanguageFeatures/Constructor-tear-offs/function_tearoffs_A01_t03.dart#L37-L40
