### ISSUE TITLE
Errors in tests after enabling bounds checks in type literals

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1189]
I'm working on a CL that enables bounds checks in type literals: https://dart-review.googlesource.com/c/sdk/+/212290. Running the tests shows some co19 tests failing as having type literals with bound errors. For example, test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t01.dart has type literal `G`.

https://github.com/dart-lang/co19/blob/a4f77a02a3676b1c2e7390c860cb0486c8515d3f/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t01.dart#L52-L58

The type literal is expanded into `G<A<dynamic>, A<Never>>` which isn't well-bounded. After I enable the check in my CL, `G` becomes a compile-time error.

Here's the list of tests that fail after enabling the check.

/cc @eernstg 

tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t01.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t02.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t04.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t10.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t12.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t13.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t14.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_02_t01.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_02_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_02_t10.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_02_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_02_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_03_t02.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_03_t04.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_03_t12.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_03_t13.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_03_t14.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t01.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t02.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t04.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t10.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t12.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t13.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t14.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_04_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t01.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t02.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t04.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t10.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t12.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t13.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t14.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_05_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t01.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t02.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t04.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t10.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t12.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t13.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t14.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_06_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_typedef_l1_t03.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_typedef_l1_t07.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_typedef_l1_t11.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_typedef_l1_t15.dart
tests/co19/src/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_typedef_l1_t19.dart

**Comment by eernstg** [comment]
Thanks @stefantsov!

@sgrekhov and @iarkh, what do you think is the best way ahead? It would be good to have coverage of the fact that the not-well-bounded types are detected, but I guess it is more useful in almost all of these tests to adjust them such. that the types are well-bounded (and they can test whatever they were originally intended to test).

**Comment by sgrekhov** [comment]
@eernstg I'm afraid we'll have to make most part of these tests to expect compile time errors. For example, let's take a look at the test from the example.

https://github.com/dart-lang/co19/blob/a4f77a02a3676b1c2e7390c860cb0486c8515d3f/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t01.dart#L52-L58

How to make it well bounded? I'd suggest the following

```dart
import "../../../../Utils/expect.dart";

class A<X> {}
typedef G<X extends A<X>, Y extends A<Y>> = void Function(X, Y);
typedef G_expected = void Function(A<Never>, A<Never>);

main() {
  Expect.equals(G_expected, G);
}
```
But it is exactly what another test does
https://github.com/dart-lang/co19/blob/5f4d97099224c4507946f7eb55d2f2eb0a7a9022/LanguageFeatures/Instantiate-to-bound/typedef/dynamic/typedef_l2_01_t05.dart#L50-L58

May be you have a better ideas how to rewrite these tests to make them well bounded?
