### ISSUE TITLE
please clean up webgl tests

### ISSUE THREAD

**Issue by efortuna** [dart-lang/co19#119]
The tests in LayoutTests/fast/canvas/webgl are rather convoluted, and don't use much of the standard dart testing framework. These a number of these tests are flaking frequently on our bots. (see dart2js-linux column: https://uberchromegw.corp.google.com/i/client.dart/console) 

It is extremely difficult to figure out what the source of these flakes are, wasting many engineers' time debugging.

**Comment by efortuna** [comment]
See also earlier bug in the dart repo: https://github.com/dart-lang/sdk/issues/26725

**Comment by sgrekhov** [comment]
Done. 8e58b7608bc35deae7e15d9a012d5b48af1eeec5 for strong-mode and 3a300ceb26d079ef0e721683b0b2c6cf9f0a3479  for master

**Comment by alan-knight** [comment]
It looks like this just deletes all of them. Now we have no coverage at all of WebGL.

**Comment by sgrekhov** [comment]
Ok, I can return WebGL tests back. But what was intention of this issue then?

**Comment by efortuna** [comment]
The intention was asking to refactor them/ add more comments so they are easier to understand/follow. We're seeing these tests flake a lot on the buildbots, but having a hard time understanding why given the current state of the code.

**Comment by sgrekhov** [comment]
Webgl tests restored. @efortuna, https://uberchromegw.corp.google.com/i/client.dart/console is unavailable for me. Can you attach the list of the tests that are flacking?

**Comment by sgrekhov** [comment]
LayoutTests (and WebGL tests as part of LayoutTests) removed as obsolete.
