### ISSUE TITLE
co19/LanguageFeatures/Constructor-tear-offs/call_method* tests need adjustment

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1191]
It used to be a compile-time error to perform a generic method instantiation on the `call` method of a function object, but this is now supported (as part of the change where we now support generic function instantiation of existing function objects, https://github.com/dart-lang/language/pull/1812).

As a consequence, some co19 tests need some adjustments. In particular, [this line](https://github.com/dart-lang/co19/blob/a4f77a02a3676b1c2e7390c860cb0486c8515d3f/LanguageFeatures/Constructor-tear-offs/call_method_A02_t01.dart#L28) is no longer an error.

Note that [this line](https://github.com/dart-lang/co19/blob/a4f77a02a3676b1c2e7390c860cb0486c8515d3f/LanguageFeatures/Constructor-tear-offs/call_method_A02_t01.dart#L35) was not an error already before the change (and is still not an error): It has been supported to tear off the call method of a function object all the time (it isn't hard to support: `myFunctionObject.call` can evaluate to `myFunctionObject` when there is no generic function instantiation).

It may be useful to consider the distinction in terms of the upcoming explicit instantiation mechanism: Assume that the context type is `Object` (that is, we can ignore it), then `myFunctionObject.call` has been allowed all the time, but `myFunctionObject.call<Some, Type, Arguments>` was an error, and is now allowed.

All tests matched by the wildcard in the title are likely to need a revisit with this in mind, and possibly some others. Searching for `.call` should give a good hint.

**Comment by sgrekhov** [comment]
More test cases needs to be added
