### ISSUE TITLE
co19/LanguageFeatures/Constructor-tear-offs/call_method_A03_t01 adjustment

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1192]
[This log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8836773780550621185/+/u/test_results/new_test_failures__logs_) shows that the static error expectations in co19/LanguageFeatures/Constructor-tear-offs/call_method_A03_t01 have a wrong location.

However, the test seems to rely on language rules that are no longer in the specification (in this case that's the constructor-tearoffs feature spec): Lines 5-9 state that generic method instantiation on the `call` method of an expression whose static type is a generic function type is an error. However, this is no longer true, it is now allowed.

The test doesn't actually perform a generic function instantiation on any expression, so the '@assertion' part is misleading relative to the actual code (so the assertion part or the code could be adjusted such that it they match up).

It is also confusing that the test uses `funcValue{1,2}?.call`, because that gives rise to a warning (because `funcValue1` and `funcValue2` can't be null), and this doesn't have any obvious connection to the stated purpose of the test.

The minimal fix which is needed would be to adjust the location of the error message such that it matches the actual behavior of the tools today, but it would also be useful to do something about the mismatch between the assertion part and the actual contents of the test.

**Comment by sgrekhov** [comment]
@eernstg thank you for pointing. 

As for the wrong assertion - I'm waiting for the Constructor tear-off spec change to copy new assertion from there.  Like it was with [ambiguities tests](https://github.com/dart-lang/co19/commit/4aae571b0358e2f063ab68f2eb92857e31deb0b9)

**Comment by sgrekhov** [comment]
Missed that constructor tear off the spec was updated. Reopened
