### ISSUE TITLE
With constructor-tearoffs, test that type arguments can determine whether or not an expression is constant

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1193]
As far as I can see, the following kind of situation is not tested in the current set of co19 tests: An expression is constant if it is an explicit generic type instantiation of a constant function object where the type argument 

```dart
void f<X>(X x) {}

void main() {
  const c1 = f<int>; // OK: `f` is constant, `int` is a constant type expression.

  void g<Y>() {
    const c2 = f<Y>; // Error: `Y` is not a constant type expression.
  }

  const c3 = g<int>; // Error: `g` is not a constant expression, so `g<T>` is not constant, for any `T`.
}
```

Did I just overlook something? Otherwise, please add some tests for this kind of situation.

**Comment by sgrekhov** [comment]
@eernstg I'm adding appropriate tests now. Why the following is an error? Is this intended?
```dart
class C {
  const C();
  void foo<X>(X x) {}
}

void main() {
  const c = const C();
  const c1 = c.foo<int>; // Error: Not a constant expression.
}
```

**Comment by eernstg** [comment]
`c.foo<int>` is not a constant expression because an instance method closurization is never a constant expression (and then the explicit generic instantiation is also not constant). I believe you could say that this is because we never allow a constant expression to inspect the internal structure of a given constant object. We have exceptions like `myString.length`, but they are specified one by one (perhaps that's the only one, by the way ;-).
