### ISSUE TITLE
WebPlatformTest/shadow-dom/events/retargeting-focus-events/test-002_t01 flaky

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#12]
WebPlatformTest/shadow-dom/events/retargeting-focus-events/test-002_t01 is flaky on Dartium, all platforms.

Looking at the test, it seems to rely on a race condition.

**Comment by alsemenov** [comment]
fixed in https://github.com/dart-lang/co19/commit/9e4dfe8d0a0bf6a99ec42c76707aef6a1a6446b8
