### ISSUE TITLE
Tests check that allowed use of `void` is an error

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#120]
With https://github.com/dart-lang/sdk/issues/30176, the treatment of `void` in Dart programs is updated such that several usages that used to be compile-time errors/warnings are now allowed. In particular, `void` can be an actual type argument and it can be the type annotation of a variable/parameter and the return type of a getter.

This calls for changes to the following co19 tests:
- `Language/Types/Type_Void/syntax_t01`: No longer an error.
- `Language/Types/Type_Void/syntax_t02`: No longer an error.
- `Language/Types/Type_Void/syntax_t04`: No longer an error.
- `Language/Types/Type_Void/syntax_t09`: The declaration `void v` is no longer an error, so the documentation should be updated, but `print(v)` is a compile-time error.
- `Language/Classes/Getters/void_return_type_t01`: No longer a static warning.

**Comment by sgrekhov** [comment]
Fixed in master and strong-mode branches

**Comment by eernstg** [comment]
Thanks! There are a couple of little things to think about here, though:

- The `@assertion` part and the `@description` part of these tests are now contradicting each other in some cases (e.g., in void_return_type_t01: 'It is a static warning..' vs. 'Check that no static warning is produced..'). We could change the description to say 'With generalized void, it is allowed..', which would indicate to readers how the extended language works, and also give a hint to readers who are unaware of the update.

- For syntax_t09.dart, it makes a subtle difference that `print(v)` is replaced by `var x = v; print(x);`. In Dart 1.x extended with generalized void, it is a compile-time error to evaluate `v`, hence `var x = v;` is a compile-time error, but `print(x)` is ok at compile-time because `x` has static type `dynamic`. However, in strong mode the type of `x` will be inferred, and with the static type `void` for `x` we will also have a static error at `print(x)`. I'd suggest going back to `print(v)`, and expecting that to be a compile-time error (1: that removes one little bump in the transition to strong-mode-only, and 2: the new form does not add anything of interest (Dart 1.x with generalized void: `print(aDynamicValue)` is tested elsewhere, strong mode: we just test twice that it is an error to use a void value)).

**Comment by sgrekhov** [comment]
Thank you! Fixed again according your notes in both branches
