### ISSUE TITLE
Possible incorrect `stat` tests for `Links`

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/co19#1232]
If I understand the [`Link/stat_A01_t01.dart`](https://github.com/dart-lang/co19/blob/master/LibTest/io/Link/stat_A01_t01.dart) test correctly, the test is:

1. creating a symlink to a directory
2. calling `.stat()` on that symlink
3. expecting the result to be for the **symlink** (not the underlying directory)

Since every `FileSystemEntity` relies on `FileStat` for their `.stat()` call and since `FileStat` is documented to call the POSIX `stat()` function, it seems like the results for the directory should be returned.

This test also fails on my Mac OS X machine:
```
$ dart --version
Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "macos_x64"
$ uname -v
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
$ dart tests/co19_2/src/LibTest/io/Link/stat_A01_t01.dart
unittest-suite-wait-for-done
Unhandled exception:
Expect.equals(expected: <link>, actual: <directory>) fails.
#0      _fail (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/Utils/expect.dart:22:5)
#1      Expect.equals (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/Utils/expect_common.dart:31:5)
#2      _main.<anonymous closure> (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/LibTest/io/Link/stat_A01_t01.dart:32:12)
<asynchronous suspension>
#3      _main (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/LibTest/io/Link/stat_A01_t01.dart:31:3)
<asynchronous suspension>
#4      inSandbox (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/LibTest/io/file_utils.dart:24:12)
<asynchronous suspension>
#5      main (file:///Users/bquinlan/dart/dart-sdk1/sdk/tests/co19_2/src/LibTest/io/Link/stat_A01_t01.dart:25:3)
<asynchronous suspension>
```

There are some other tests that also verify similar behavior.

**Comment by brianquinlan** [comment]
BTW, I'm happy to submit a fix if we agree on semantics.

**Comment by sgrekhov** [comment]
@brianquinlan thank you. The actual behaviour depends on operation system. I fixed this tests to not to fail on Win, Lunux and Mac. Feel free to reopen the issue if you believe that issue is not fixed completely

**Comment by brianquinlan** [comment]
I actually fixed the Windows behavior in https://github.com/dart-lang/sdk/commit/5e990591b9504c168d94de964560765633608ced. 

There are a few more tests like this. I can send you something to review tomorrow.

**Comment by sgrekhov** [comment]
Please do

**Comment by brianquinlan** [comment]
I have a proposed change at https://github.com/dart-lang/co19/pull/1233

**Comment by sgrekhov** [comment]
Merged that PR. Thank you
