### ISSUE TITLE
Language/Errors_and_Warnings/compile_error_t06 is meanto to run only against the analyzer and cfe

### ISSUE THREAD

**Issue by a-siva** [dart-lang/co19#1235]
All these compilation error tests under `Language/Errors_and_Warnings `appear to have been written to only run against the analyzer and cfe and verify that the correct compilation error is reported by the tool.

This appears to be done using the comment lines
```
//        
// [analyzer] unspecified
// [cfe] unspecified
```
in the test.

However for the test `compile_error_t06 `these comment lines are included in the file `Language/Errors_and_Warnings/compile_error_lib.dart`
as a result of which the test harness does not appear to correctly skip `compile_error_t06` when running the VM tests.

These comment lines should probably be moved into the file `Language/Errors_and_Warnings/compile_error_t06.dart` for
this test to be correctly skipped when running the VM tests.

**Comment by sgrekhov** [comment]
The described problem is a SDK issue https://github.com/dart-lang/sdk/issues/44990.  Hopefully one day it will be resolved and all of the tests that are failing now because of this issue became Ok. Closing this issue
