### ISSUE TITLE
io/Directory/renameSync_A02_t01.dart should not expect an existing directory to be replaced

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/co19#1236]
I'd change the test to put a file in the target directory and verify that an error is generated.

**Comment by sgrekhov** [comment]
@brianquinlan I updated rename() and renameSync() tests according to the new behavior. But I didn't find information if `Fuchsia` is POSIX system or not. Do you have any information about it?
https://github.com/dart-lang/co19/blob/baa3a8712024b449889a3cb6276c07e884beee67/LibTest/io/Directory/renameSync_A02_t04.dart#L32-L35

**Comment by brianquinlan** [comment]
I suspect that Fushia has the POSIX behavior but I'm not sure.
