### ISSUE TITLE
no_such_method_t01 test is outdated

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/co19#127]
`Language/Expressions/Property_Extraction/Super_Getter_Access_and_Method_Closurization/no_such_method_t01.dart` is outdated. It requires that `im.positionalArguments` and `im.namedArguments` be exactly `const[]` and `const{}`, whereas the spec. was changed in Sep. 2017 to only require that these fields be set to an immutable/unmodifiable list/map.

I've uploaded a fix in the branch `issue-197`.

**Comment by sgrekhov** [comment]
Fix merged into master branch.
