### ISSUE TITLE
Language/Classes/definition_t23 is incorrect

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/co19#129]
The spec in the repository (https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex) currently has:

> It is a compile-time error if the superclass of a class $C$ is specified as a superinterface of $C$.

The named test checks that we can compile classes like:

```dart
@A() abstract class I3<T> = A1 with B1 implements A1;
abstract class J3<T> = A1 with B1 implements A1;

@A() abstract class I4 = A1 with B1 implements A1;
abstract class J4 = A1 with B1 implements A1;
@B() class X4 = A1 with B1 implements A1;
class Y4 = A1 with B1 implements A1;
```

which should all be a compile-time error.  See https://github.com/dart-lang/sdk/issues/31624.

**Comment by sgrekhov** [comment]
Fixed
