### ISSUE TITLE
WeakReference / Finalizer / NativeFinalizer tests when not using triggerGC

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/co19#1299]
By using `dart:ffi` to trigger the GC, we can test the behavior of these new language features when the GC is run.

However, we don't support `dart:ffi` on the simulated architectures yet.

* https://github.com/dart-lang/sdk/issues/48365

And the Dart API (used in the triggerG function) cannot be called on windows precompiled from our testing dynamic library.

* https://github.com/dart-lang/sdk/issues/40579

This means we cannot run the tests in simarm, simarm64, and windows precompiled.

Can we split the tests so that a subset of the tests does not run the triggerGC function?

For example:

* a WeakReference with a target that stays in scope returning that same target can be tested without forcing the GC.
* trying to assign a non-Expando value in a WeakReference and getting an Exception can be tested without forcing the GC.

**Comment by sgrekhov** [comment]
Fixed by 4c0118fd4c1bc77b347ad186358a3e9a46bf9c12
