### ISSUE TITLE
Some cascading errors aren't reported by the CFE anymore and should be removed from tests

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1305]
The CLs https://dart-review.googlesource.com/c/sdk/+/233363 and https://dart-review.googlesource.com/c/sdk/+/233382 prevent certain errors from being reported in some of the cases where that was caused by a recovery from another error. The error reporting in those cases is now in agreement to Analyzer. The following tests should be updated to reflect the changes.

### Language/Functions/Formal_Parameters/Optional_Formals/syntax_t12.dart

This test should be updated in branches `master` and `pre-nnbd`. The following expectations of an error from the CFE should be removed.

https://github.com/dart-lang/co19/blob/42d638c1b6683da6c65347eff1f0b954a11f44e0/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t12.dart#L22-L24

https://github.com/dart-lang/co19/blob/1b9f593ca2f4a57b700afb1f81c3db341569d5ed/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t12.dart#L25-L27

### Language/Functions/Formal_Parameters/Optional_Formals/syntax_t13.dart

This test should be updated in branch `pre-nnbd`. The following expectation of an error from the CFE should be removed.

https://github.com/dart-lang/co19/blob/1b9f593ca2f4a57b700afb1f81c3db341569d5ed/Language/Functions/Formal_Parameters/Optional_Formals/syntax_t13.dart#L26-L27

### Language/Functions/Formal_Parameters/Required_Formals/syntax_t03.dart

This test should be updated in branches `master` and `pre-nnbd`. The following expectations of an error from the CFE should be removed.

https://github.com/dart-lang/co19/blob/42d638c1b6683da6c65347eff1f0b954a11f44e0/Language/Functions/Formal_Parameters/Required_Formals/syntax_t03.dart#L35-L37

https://github.com/dart-lang/co19/blob/1b9f593ca2f4a57b700afb1f81c3db341569d5ed/Language/Functions/Formal_Parameters/Required_Formals/syntax_t03.dart#L39-L41

### Language/Enums/syntax_t08.dart

This test should be updated in branches `master` and `pre-nnbd`. The following expectations of an error from the CFE should be removed.

https://github.com/dart-lang/co19/blob/42d638c1b6683da6c65347eff1f0b954a11f44e0/Language/Enums/syntax_t08.dart#L22-L24

https://github.com/dart-lang/co19/blob/1b9f593ca2f4a57b700afb1f81c3db341569d5ed/Language/Enums/syntax_t08.dart#L22-L24

### Language/Enums/syntax_t09.dart

This test should be updated in branches `master` and `pre-nnbd`. The following expectations of an error from the CFE should be removed.

https://github.com/dart-lang/co19/blob/42d638c1b6683da6c65347eff1f0b954a11f44e0/Language/Enums/syntax_t09.dart#L21-L23

https://github.com/dart-lang/co19/blob/1b9f593ca2f4a57b700afb1f81c3db341569d5ed/Language/Enums/syntax_t09.dart#L22-L24

**Comment by sgrekhov** [comment]
Fixed in both `master` and `pre-nnbd` branches
