### ISSUE TITLE
A number of co19 tests need to be updated for the new fixed size integers specification

### ISSUE THREAD

**Issue by a-siva** [dart-lang/co19#131]
Please see the informal specifications to the new fixed size integers specifications
https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md

A number of co19 tests need to be fixed to account for the new specification.

**Comment by whesse** [comment]
This also affects the co19 strong mode branch, and should be fixed there as well.

**Comment by sgrekhov** [comment]
Fixed-size integers fixed in a strong-mode branch (Dart 2.x). I believe, no work required for master branch (dart 1.x)
