### ISSUE TITLE
`Finalizer` detach argument is allowed to be null

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/co19#1311]
LanguageFeatures/FinalizationRegistry/no_ffi/Finalizer/attach_A04_t11.dart

```dart
  Expect.throws(() {
    finalizer.attach(object, "Finalization token", detach: null);
  });
```

The `detach` is nullable, passing `null` or omitting it does not throw

cc @iarkh

**Comment by dcharkes** [comment]
@sgrekhov

**Comment by sgrekhov** [comment]
@dcharkes this test was deleted in https://github.com/dart-lang/co19/commit/6d915d86c0ed7fd5173778d74b9b0e9b31996126
This issue can be closed
