### ISSUE TITLE
LibTest/io/InternetAddress/lookup_A02_t02 needs to use `InternetAddressType.any`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#1315]
We will soon be deprecating the old "SCREAMING_CAPS" style constants from `dart:io` in favor of the corresponding "camelCase" constants.  To avoid a test breakage when we do this, the test `LibTest/io/InternetAddress/lookup_A02_t02` needs to be updated so that it uses `InternetAddressType.any` instead of `InternetAddressType.ANY`.

This change needs to be made to both the `master` and `pre-nnbd` branches.

**Comment by sgrekhov** [comment]
Please see https://github.com/dart-lang/co19/pull/1317 ana https://github.com/dart-lang/co19/pull/1318

cc @athomas
