### ISSUE TITLE
KeygenElement has been removed from Chrome

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#133]
All of the custom-elements tests that use custom.dart are broken because one of the customer elements extends KeygenElement.  Please remove this.

tests/co19/src/WebPlatformTest/custom-elements/custom.dart:213:26:
Warning: Cannot resolve type 'KeygenElement'.
class Foo_keygen extends KeygenElement {
                         ^^^^^^^^^^^^^

All of the tests that are failing are marked failing with this issue # in tests/co19/co19-dart2js.status.  When this is committed please remove these entries in the status file.

**Comment by sgrekhov** [comment]
*.status files updated. Please see https://github.com/dart-lang/sdk/pull/32385
