### ISSUE TITLE
Update expected results on a number of font-face tests

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#136]
Many of these tests some of the metrics have changed by a pixel or two.  Please update the expected results.

LayoutTests/fast/css/font-face-cache-bug_t01
LayoutTests/fast/css/font-face-insert-link_t01
LayoutTests/fast/css/font-face-unicode-range-load_t01
LayoutTests/fast/css/font-face-unicode-range-monospace_t01
LayoutTests/fast/css/font-family-trailing-bracket-gunk_t01
LayoutTests/fast/css/font-shorthand-from-longhands_t01

**Comment by sgrekhov** [comment]
Status file update https://github.com/dart-lang/sdk/pull/32385
