### ISSUE TITLE
co19_2 tests failures

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#1376]
Triage failures of co19_2 tests

https://ci.chromium.org/p/dart/builders/ci.sandbox/dart2js-strong-linux-x64-chrome

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8807646386557525441/+/u/test_results/ignored_flaky_test_failure_logs

**Comment by sgrekhov** [comment]
All of the failed flaky tests works well for me locally on the edge version of SDK on `dart2js-linux-chrome` configuration.

**Comment by eernstg** [comment]
Thanks! I think we can close this, and return to the topic if further concerns are raised.
