### ISSUE TITLE
Fix co19/LayoutTests/fast/css/padding-no-renderer_t01

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#139]
change
 shouldBeEqualToString(getComputedStyle(test5, null).paddingTop, "10px");

to
 shouldBeEqualToString(getComputedStyle(test5, null).paddingTop, "10%");

**Comment by sgrekhov** [comment]
This test fails in IE only and there is no problem with the test5. Problem in the string `shouldBeEqualToString(getComputedStyle(test3, null).paddingTop, "10px");`
For IE returned value is '1px'
So, the cross-platform solution, I believe, is simply skip this check for IE

**Comment by sgrekhov** [comment]
Fixed in master and strong-mode branches
