### ISSUE TITLE
[Records] Co19 tests - add tests 

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/co19#1399]

**Comment by itsjustkevin** [comment]
@sgrekhov can you add your issue to the project instead of closing it out as a duplicate?  We would still like to track the work being done.

**Comment by sgrekhov** [comment]
@itsjustkevin sorry. I'll go on the work using this issue and close the previous one

**Comment by eernstg** [comment]
@sgrekhov, please give me a heads up here when you've completed writing these tests.

**Comment by sgrekhov** [comment]
If this PR https://github.com/dart-lang/co19/pull/1418 is Ok, then, I believe, I completed with the tests for records

**Comment by eernstg** [comment]
Thanks!

**Comment by sgrekhov** [comment]
Reopened. Records specification was updated, need to update the tests accordingly

**Comment by sgrekhov** [comment]
Records tests updated according too the current specification. Closing this issue

**Comment by sgrekhov** [comment]
Spec changed, `Record.empty` removed. Need to update the tests accordingly

**Comment by sgrekhov** [comment]
Need to add tests for  the new section "Interactions with libraries using older language versions"

**Comment by sgrekhov** [comment]
Spec was changed (Ambiguity with metadata annotations added), need to update tests accordingly
