### ISSUE TITLE
[Patterns] Co19 tests - add tests

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/co19#1401]

**Comment by sgrekhov** [comment]
@itsjustkevin @eernstg is this a right feature specification link for Patterns? https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md

**Comment by eernstg** [comment]
Yes!

**Comment by sgrekhov** [comment]
Completed

**Comment by sgrekhov** [comment]
Reopened. Spec for [exaustiveness](https://github.com/dart-lang/language/pull/2948) is ready for testing. Need to add appropriate tests

**Comment by sgrekhov** [comment]
Completed

**Comment by eernstg** [comment]
Thump! says the big door as it is closed. Thanks for the great work on creating all those tests!
