### ISSUE TITLE
Why do we not have test failures on using deprecated entities?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1405]
Consider the occurrence of `@proxy` [here](https://github.com/dart-lang/co19/blob/master/LibTest/core/Invocation/isAccessor_A01_t01.dart#L13). This metadata ought to be tested, because the test isn't skipped by status any files.

Still, it counts as a successful test run in all 52 configurations according to https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LibTest/core/Invocation&showAll.

So perhaps the problem is that this failure is a 'hint', and they are ignored?

Perhaps the easiest way to find these tests is to run `dart analyze` on all of co19. But if that yields too much noise then grepping for `@[dD]eprecated` in `$SDK/sdk/**/*.dart` and then grepping for each deprecated thing might be more convenient.

In any case, it would be very useful if all co19 tests are checked for code which is using deprecated entitiea, and such usages are removed before the actual declarations are removed from the SDK.

**Comment by eernstg** [comment]
@mit-mit, do you have any further comments on what we need to do here?

**Comment by mit-mit** [comment]
We should remove all co19 tests of `@deprecated` core library APIs, as they are about to be removed: https://github.com/dart-lang/sdk/issues/49529

**Comment by mit-mit** [comment]
I think the easiest thing might be to configure the analysis options for co19 to upgrade the info `deprecated_member_use` to be an error?

```
   info • fyz.dart:1:2 • 'proxy' is deprecated and shouldn't be used. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
```

**Comment by mit-mit** [comment]
I ran `dart analyze` with this `analysis_options.yaml` placed at the root of this repo:

```
analyzer:
  errors:
    deprecated_member_use: error
```

Running `dart analyze .` from the root produces several thousand errors:
https://gist.github.com/mit-mit/b5a1372c06140eab5e3aac3fe1e9ec74

It looks like the vast majority are in generated files, so perhaps we can fix those in some templates?

**Comment by eernstg** [comment]
The behavior of our tools when they encounter usages of deprecated declarations should of course be tested somehow, but it should not be a problem that co19 doesn't test this behavior, because it isn't a language-defined behavior. So it should be ok to simply change the code in every single case where it uses a deprecated declaration.

**Comment by sgrekhov** [comment]
@mit-mit thank you. I'll update the test shortly

**Comment by sgrekhov** [comment]
@eernstg @mit-mit should the deprecated API be removed from `co19_2` tests as well?

**Comment by eernstg** [comment]
@mit-mit?

**Comment by mit-mit** [comment]
Yes, please migrate `co19_2` too. While it will be removed at some point, that will very likely be after we need to remove the deprecated APIs.

**Comment by sgrekhov** [comment]
@mit-mit @eernstg should we use the same list of the deprecated API in `co19_2`? These tests marked as `// @dart = 2.9`. Some API which is deprecated in `2.19` may be not deprecated in `2.9`

**Comment by mit-mit** [comment]
Yes, given we're using these tests to test new Dart SDK releases, and the deprecated APIs are about to be removed, we can use the same list of deprecations.

**Comment by sgrekhov** [comment]
@eernstg @mit-mit please clarify if  `BitesBuilder` tests should be moved from `dart:io` to `dart:typed_data`? Now we have `BytesBuilder` classes in both packages, but seems that in fact it is one class placed in `typed_data`. Documentation [link](https://api.dart.dev/dev/2.19.0-126.0.dev/dart-io/dart-io-library.html) from `io` leads to `typed_data`.

For the code
```dart
import "dart:io";

main() {
  BytesBuilder builder = new BytesBuilder();
  print(builder);
}
```
it produces
```
dart analyze test.dart 

   info • test.dart:20:3 • The ability to import 'BytesBuilder' indirectly has been deprecated. Try importing 'BytesBuilder' directly. •                deprecated_export_use 
```
Interesting, that running `dart analyze --enable-experiment=records,inference-update-2 test.dart` produces no any hints.

If, in the example above, to replace `import "dart:io";` by `import "dart:typed_data";` then no `deprecated_export_use` hint is shown.

So, I guess, that `BytesBuilder` should be imported via `dart:typed_data` and the existing co19 tests should be moved from `io` to `typed_data`. Please confirm.

Also I'm wonder, why run of `dart analyze --enable-experiment=records,inference-update-2 test.dart` produces no `deprecated_export_use`. Is this an issue that should be reported?

**Comment by eernstg** [comment]
> So, I guess, that `BytesBuilder` should be imported via `dart:typed_data` and the existing
> co19 tests should be moved from `io` to `typed_data`.

Yes, please do that.

> should be reported?

Yes, please. I think it might be useful for the analyzer team to take a look at this behavior. If it is a surprise to them then it might be worth exploring why it happens.

**Comment by mit-mit** [comment]
Thanks @sgrekhov !
