### ISSUE TITLE
Fix all co19 tests that use query and queryAll

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#143]
The depreciated calls query and queryAll have been removed.  Use querySelector or querySelectorAll.

List of tests to fix:

LayoutTests/fast/borders/border-color-visited_t01: RuntimeError # See 
LayoutTests/fast/canvas/fillText-shadow_t01
LayoutTests/fast/css/misplaced-charset_t01
LayoutTests/fast/css/pseudo-empty-dynamic-empty_t01
LayoutTests/fast/css/remove-class-name_t01
LayoutTests/fast/dom/clone-node-style_t01
LayoutTests/fast/dom/HTMLTableElement/createCaption_t01
LayoutTests/fast/dom/HTMLTableElement/early-acid3-66-excerpt_t01
LayoutTests/fast/dom/HTMLTableRowElement/insertCell_t01
LayoutTests/fast/dom/icon-url-change_t01
LayoutTests/fast/dom/icon-url-list_t01
LayoutTests/fast/dom/Range/create-contextual-fragment-script-unmark-already-started_t01
LayoutTests/fast/dom/shared-inline-style-after-node-removal_t01
LayoutTests/fast/events/form-onchange_t01
LayoutTests/fast/events/onerror-bubbling_t01
LayoutTests/fast/forms/autofocus-attribute_t01
LayoutTests/fast/forms/autofocus-opera-004_t01
LayoutTests/fast/forms/autofocus-opera-005_t01
LayoutTests/fast/forms/autofocus-opera-008_t01
LayoutTests/fast/forms/interactive-validation-attach-assertion_t01
LayoutTests/fast/forms/select-namedItem_t01
LayoutTests/fast/forms/select-reset-multiple-selections-4-single-selection_t01
LayoutTests/fast/table/resize-table-binding-cell_t01
LayoutTests/fast/table/resize-table-binding-cell_t01
LayoutTests/fast/xpath/4XPath/Core/test_location_path_t01
LayoutTests/fast/xpath/4XPath/Core/test_step_t01
LibTest/html/Element/query_A01_t01
WebPlatformTest/custom-elements/instantiating/isAttribute_A01_t01
WebPlatformTest/custom-elements/instantiating/isAttribute_A01_t02
WebPlatformTest/custom-elements/instantiating/isAttribute_A02_t01
WebPlatformTest/custom-elements/instantiating/isAttribute_A03_t01
WebPlatformTest/custom-elements/instantiating/localName_A01_t01
WebPlatformTest/html/dom/elements/global-attributes/classlist-nonstring_t01
WebPlatformTest/html/semantics/forms/the-textarea-element/textarea-type_t01
WebPlatformTest/html/semantics/tabular-data/the-table-element/insertRow-method_t01
WebPlatformTest/html/semantics/tabular-data/the-table-element/insertRow-method_t02
WebPlatformTest/html/semantics/tabular-data/the-table-element/tBodies_t01
WebPlatformTest/html/semantics/text-level-semantics/the-a-element/a.text-getter_t01
WebPlatformTest/html/semantics/text-level-semantics/the-a-element/a.text-setter_t01

**Comment by sgrekhov** [comment]
Fixed in a strong-mode branch
