### ISSUE TITLE
Wrong record literal with named fields

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#1443]
`co19/LanguageFeatures/Records/record_type_annotations_A03_t01` - similar to already fixed.

```dart
  dynamic d = ({i: 1, s: "Lily was here"});
```

**Comment by sgrekhov** [comment]
@scheglov sorry for these typos. I noticed a couple more of them. It's really hard to catch them when you have no compiler. Please see https://github.com/dart-lang/co19/pull/1445

**Comment by bwilkerson** [comment]
While I'm certain that it has bugs (I'm working on fixing one right now), the analyzer is able to parse and report errors for records. If it helps to have a compiler the analyzer might be of some use to you.

**Comment by scheglov** [comment]
No problem at all.
I'm happy that we have these tests! :-)
