### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1468]
Just updated the spec parser to include support for record literals and record types. Some issues came up during testing. (I know that at least some of these have been fixed already, but I'll only see that when it is rolled, but you probably know immediately if any of these are new):

co19/LanguageFeatures/Records/record_type_annotations_A02_t12, line 45: Missing parameter name (it's an old-style typedef); line 49: missing parameter name (function declaration).

co19/LanguageFeatures/Records/record_type_annotations_A04_t06, line 35, 39: Missing parameter name.

co19/LanguageFeatures/Records/record_type_annotations_A04_t02, line 35: Missing parameter name.

co19/LanguageFeatures/Records/record_type_annotations_A05_t05, line 38, 44: Missing parameter name.

co19/LanguageFeatures/Records/record_expressions_A02_t03, line 60: Missing ')'.

co19/LanguageFeatures/Records/record_type_annotations_A02_t09, line 49, 53: Missing parameter name; 

co19/LanguageFeatures/Records/record_type_annotations_A06_t02, line 35, 39: Missing parameter name.

co19/LanguageFeatures/Records/record_type_annotations_A04_t03, line 34: Missing parameter name; line 75: Missing name of named record field.

co19/LanguageFeatures/Records/record_type_annotations_A04_t06, line 35, 39: Same issue.

co19/LanguageFeatures/Records/record_type_annotations_A01_t04, line 28, 30, 31: Missing parameter name.

co19/LanguageFeatures/Records/record_type_annotations_A02_t11, line 45, 49: Missing parameter name.

co19/LanguageFeatures/Records/static_semantics_A04_t02, line 38: `void` occurs as an expression.  Line 39 and 40 have similar issues. Looks like the test makes an attempt to use a record type as an expression, and that is not supported (need to use `typedef typeOf<X> = X;` or something like that and then `typeOf<(void,)>`).

co19/LanguageFeatures/Records/record_type_annotations_A01_t02, line 29: Spurious '}'.

co19/LanguageFeatures/Records/record_type_annotations_A07_t02, line 40, 46, 48: Missing parameter name.

co19/LanguageFeatures/Records/record_type_annotations_A01_t03, line 38: Spurious '}'.

co19/LanguageFeatures/Records/expandos_A01_t01, line 24: Missing ':'.

**Comment by sgrekhov** [comment]
@eernstg Spec parser is cool! Thank you!
