### ISSUE TITLE
Test Dart 2 feature 'instantiate to bound'

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#148]
Cf. meeting on Wed Apr 10th, there's a need for new tests corresponding to the Dart 2 instantiate-to-bound feature, as specified in https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md.

This feature is tightly interconnected with super-bounded types, but given that they can be specified explicitly (hence arising without any instantiation to bound), there's a separate issue for that, #147.

**Comment by iarkh** [comment]
Added to https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Instantiate-to-bound
Simple-bounds tests are in https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Simple-bounds
Regression tests for some bugs found during the i-2-b tests creating are in https://github.com/dart-lang/co19/tree/master/LanguageFeatures/regression
