### ISSUE TITLE
Extensions can provide setters for record types

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1487]
Consider the following files:

1. https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Records/members_A02_t06.dart, lines 28 and 33.
2. https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Records/members_A03_t06.dart, lines 27 and 32.

I think they should not yield a compile-time error because the setters are provided by the extension. @eernstg WDYT?

**Comment by eernstg** [comment]
That's a corner case, of course, but we do have the [following rule](https://github.com/dart-lang/language/blob/2cab05fe6cc408ad95c2ddc52da3001b575da3b5/specification/dartLangSpec.tex#L6218):

```latex
The type $S$ does not have a member with the basename $m$
```

In the given context, `$S$` is the static type of the receiver. So the rule implies that if the receiver type has a getter named `n` then we can't invoke an extension setter named `n=` (unless we use an explicit `TheExtension<...>(theReceiver).n = e`).

**Comment by sgrekhov** [comment]
Closing as "As designed"
