### ISSUE TITLE
Can Object? be used as a type literal value of a record literal field value?

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1489]
Line 47 in the following test contains record literal `(Object?,)`. IIRC `Object?` can't be used as a type literal, including fields of a record literals. @eernstg WDYT?

https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Records/static_semantics_A04_t02.dart#L47

**Comment by eernstg** [comment]
That would be a syntax error. We do not have an expression of the form `e?` for any `e`. (We do have types of the form `T?` for some types `T`, but `Object?` is used as an expression in this case).
