### ISSUE TITLE
LayoutTests/fast/css/css-selector-text_t01 fails in Chrome 47 on n | a

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#15]
I don't know what's going on here, but LayoutTests/fast/css/css-selector-text_t01 starts to fail in Chrome 47 on the pattern "n|a"

**Comment by sgrekhov** [comment]
There are several problems here.
First this tests checks some non-standard properties as -webkit-.... These checks won't work in non-Webkit browsers
Second browsers are free how to return css text. It can be "a+b" and "a + b",  "* | *" and "*", "*|a" and "a"

So solution is to remove all wrong checkings and strip all spaces before the check.

**Comment by sgrekhov** [comment]
Fixed. 10be750cc4f0a7e91160ee14bfead55c0628ba5b
