### ISSUE TITLE
co19_2 tests with Dart 1 all caps constants need to be fixed

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#151]
co19 copy of the corresponding SDK issue: https://github.com/dart-lang/sdk/issues/33894

**Comment by athomas** [comment]
The tests are annotated with the SDK issue in the co19_2 status files.

**Comment by leafpetersen** [comment]
Note that https://github.com/dart-lang/dart2_fix can be used to automate many of these fixes.

**Comment by devoncarew** [comment]
Bumping the priority of this one since we've lost significant test coverage here; the and analyzer configurations, 2-3k tests are currently excluded because of upper case constants.

**Comment by sgrekhov** [comment]
Fixed
