### ISSUE TITLE
It is a compile-time error if a setter declares a return type other than void

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#153]
Tests:
co19_2/Language/Classes/Setters/return_type_not_void_t01
co19_2/Language/Classes/Setters/syntax_t04
co19_2/Language/Classes/Setters/type_object_t02

https://github.com/dart-lang/sdk/blob/4b8d3e4cf133c7c2f980e2d3894e44e041907453/docs/language/dartLangSpec.tex#L1544

**Comment by sgrekhov** [comment]
Fixed
