### ISSUE TITLE
Views tests should use the 'views' experimental flag

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#1539]
The views tests, for instance `co19/LanguageFeatures/Views/syntax_A02_t04.dart`, use the `extension-types` flag:
```
// SharedOptions=--enable-experiment=extension-types
```
instead of the correct `views` flag:
```
// SharedOptions=--enable-experiment=views
```

**Comment by eernstg** [comment]
The mechanism was just renamed to 'inline class'. Perhaps it would be helpful to rename the flag, too?

**Comment by johnniwinther** [comment]
Ok. I (try to) rename the flag (haven't tried that before) and give a heads up when that change has landed.
