### ISSUE TITLE
It is a compile-time error if a class has a setter named $v=$ with argument type $T$ and a getter named $v$ with return type $S$, and $S$ may not be assigned to $T$.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#154]
Tests:
co19_2/Language/Classes/Setters/same_name_getter_different_type_t01

https://github.com/dart-lang/sdk/blob/4b8d3e4cf133c7c2f980e2d3894e44e041907453/docs/language/dartLangSpec.tex#L1547

**Comment by sgrekhov** [comment]
Fixed
