### ISSUE TITLE
Throwing a null should raise TypeError, not NullThrownError

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1553]
In the following text it is expected that throwing the `null` value results in `NullThrownError`. In NullSafe mode an attempt to throw `null` should raise `TypeError` instead.

* co19/Language/Expressions/Throw/evaluation_t04
* co19/LibTest/async/Future/Future.sync_A01_t03
* co19/Utils/tests/Expect/throws_A01_t03

cc @lrhn

**Comment by lrhn** [comment]
The null safety specification [says](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#:~:text=It%20is%20an%20error%20if%20the%20static%20type%20of%20e%20in%20the%20expression%20throw%20e%20is%20not%20assignable%20to%20Object.):

> It is an error if the static type of `e` in the expression `throw e` is not assignable to `Object`.

It doesn't explicitly say what happens for `null` typed as `dynamic`, but *I believe* it should be treated the same way as other places where we have a required type:
* The context type schema for `e` is `Object`.
* It's a run-time type error if the value of `e` is not an instance of a subtype of `Object` (aka. "implicit downcast from `dynamic`").

@leafpetersen Do you agree with this?

Example showing that we have `bool` as context type in conditions, but not `Object` in `throw`:
```dart
void main() async {
  if (ct(false)) print("ok"); // "CT: bool"
  throw ct("a"); // "CT: dynamic"
}

// Captures static context type.
T ct<T>(Object? value) {
  print("CT: $T");
  return value as T;
}
```

**Comment by leafpetersen** [comment]
The preference would be to use `Object` as the context type, as discussed in the original issue [here](https://github.com/dart-lang/language/issues/385#issuecomment-498351391).  It looks like we neither specified it as such, nor implemented it as such though.  Technically breaking to change it now.
