### ISSUE TITLE
Please fix warnings and hints that block the Dart 3.0 version bump

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1554]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8796600349762931777/+/u/test_results/new_test_failures__logs_

We need to fix all the `unexpected analysis errors` (note these only appear when the version is Dart 3.0). The version bump CL is https://dart-review.googlesource.com/c/sdk/+/271922

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/1556
