### ISSUE TITLE
Update language version comments from 2.19 -> 3.0

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1555]
This also blocks the version bump. Please prepare a PR that bumps all language versions in tests from 2.19 to 3.0, *but do not land it yet*.

**Comment by sgrekhov** [comment]
@athomas there is no Dart version 2.19 in co19 tests. Sometimes we use 2.18 and lower for testing iteraction with legacy

**Comment by eernstg** [comment]
I was confused about that, too. 

@athomas, what does 'language version comment' mean? We have comments at the beginning of libraries of the form

```dart
// @dart = 2.9
```

in tests whose purpose it is to check that legacy libraries (with respect to some boundary version) are (still) treated correctly when a new feature is introduced: The new feature should usually be some kind of error in the legacy library. But there are no language version comments indicating the "current" language (and the current language of most tests is supposed to silently and effortlessly move up as the tool chain moves up the language versions).

**Comment by sgrekhov** [comment]
Closed as not actual for co19
