### ISSUE TITLE
It is a compile-time error if the return type of a user-declared operator \code{[]=} is explicitly declared and not \VOID{}.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#156]
Tests:
co19_2/Language/Classes/Instance_Methods/Operators/return_type_t01

https://github.com/dart-lang/sdk/blob/4b8d3e4cf133c7c2f980e2d3894e44e041907453/docs/language/dartLangSpec.tex#L1454

**Comment by sgrekhov** [comment]
Fixed
