### ISSUE TITLE
co19 roll is falling

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/co19#1564]
Looks like one of the new patterns tests isn't working:
https://dart-review.googlesource.com/c/sdk/+/272641/1

**Comment by sgrekhov** [comment]
@mit-mit syntax of logical-or and logical-and patterns was [changed](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#CHANGELOG) from `|` and `&` to `||` and `&&`. Seems that this new syntax is not supported yet and this caused new failures. I don't see anyhting wrong with the tests

**Comment by mit-mit** [comment]
Thanks @sgrekhov, that makes sense.

Approved those failures and landed in https://dart-review.googlesource.com/c/sdk/+/272641?tab=checks.
