### ISSUE TITLE
Remove FallThroughError tests

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1565]
The following tests should be deleted, because they rely on the existence of `FallThroughError`, and that class is being removed:

LibTest/core/FallThroughError/toString_A01_t01.dart
LibTest/core/FallThroughError/FallThroughError_A01_t01.dart

**Comment by eernstg** [comment]
Closing: This was already done in #1563.

**Comment by mit-mit** [comment]
Hi @sgrekhov, can we remove these from `co19_2` too?
