### ISSUE TITLE
Mixins application tests need to be updated

### ISSUE THREAD

**Issue by dhil** [dart-lang/co19#158]
In Dart 2+ it is a compile-time error to derive a mixin from a class whose super class is not `Object`. There are several tests in the `co19_2` test suite that use a mixin that extends another class than `Object`, which makes them either invalid in Dart 2 or failing/passing for the wrong reason.

The following test cases need to be updated (or removed).
```
Language/Mixins/Mixin_Application/static_warning_t01
Language/Mixins/Mixin_Application/static_warning_t02
Language/Mixins/Mixin_Application/superinterfaces_t07
Language/Mixins/Mixin_Application/syntax_t11
Language/Mixins/Mixin_Application/syntax_t12
Language/Mixins/Mixin_Application/syntax_t13
Language/Mixins/Mixin_Application/syntax_t14
Language/Mixins/Mixin_Application/syntax_t21
Language/Mixins/Mixin_Application/syntax_t22
Language/Mixins/Mixin_Application/syntax_t23
Language/Mixins/Mixin_Application/syntax_t24
Language/Mixins/Mixin_Application/syntax_t25
```

**Comment by dhil** [comment]
Kernel currently allows mixins to extends other classes than `Object`, since they are used pervasively in Flutter. Eventually the Flutter code base will have to corrected, but until then, this issue should be considered as **blocked**.

**Comment by ngolovleva** [comment]
Fixed.
