### ISSUE TITLE
Remove tests for CyclicInitializationError

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/co19#1586]
`CyclicInitializationError` is deprecated and about to be removed. Please remove these tests both from co19 and co19_2:
https://github.com/search?q=repo%3Adart-lang%2Fco19%20CyclicInitializationError&type=code

**Comment by sgrekhov** [comment]
Please see #1590 and #1591. Note that there are still mentions of `CyclicInitializationError` in the assertions text (which are cite from the specification), but this will be updated after https://github.com/dart-lang/language/issues/2720
