### ISSUE TITLE
Language/Types/Type_Void/{syntax_t09,using_t02} contain compile-time errors

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/co19#159]
These two tests have compile-time errors.  It is a compile-time error to pass a value with static type `void` to the builtin function `print` (which takes an `Object`) in `Language/Types/Type_Void/syntax_t09`:

```dart
void v = null;

main() {
  try {
    print(v);
  } catch (x) {}
}
```

It is a compile-time error to initialize a variable of type `int` with a value with static type `void` in `Language/Types/Type_Void/using_t02`:

```dart
void foo() {return;}

main() {
  int i = foo();
}
```

These are covered by the feature spec https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generalized-void.md

**Comment by sgrekhov** [comment]
Fixed
