### ISSUE TITLE
Remove use of NullThrownError in co19/LibTest/async/Future / Future.error_A01_t01.dart 

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#1599]
We need to cleanup the use of the `NullThrownError` so it can be removed from the SDK. I believe `TypeError` suffice here.
https://github.com/dart-lang/co19/blob/be8f8ae44d3f5222713ab1c51e7dbf2296db0719/LibTest/async/Future/Future.error_A01_t01.dart#L21

**Comment by nshahan** [comment]
A legacy version of this test also exists that needs to be fixed as well.
```
co19_2/LibTest/async/Future/Future.error_A01_t01
```

**Comment by sgrekhov** [comment]
Legacy version of this test was fixed by #1597. Roll of co19_2 should be completed and yhe changes shoule be enebled
