### ISSUE TITLE
Failure in FF 42/linux co19/LayoutTests/fast/canvas/canvas-composite-text-alpha_t01 

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#16]
This seems like it might be a Firefox issue. The test passes on other platforms.

"Unexpected source! expected: [0, 0, 0, 0] actual: [255, 0, 0, 255] , composite type: source-in, source: [255, 0, 0, 255], destination: [0, 255, 0, 255]<br>Unexpected destination! expected: [0, 0, 0, 0] actual: [0, 255, 0, 255] , composite type: source-in, source: [255, 0, 0, 255], destination: [0, 255, 0, 255]<br>"

**Comment by sgrekhov** [comment]
Reproduced on FF 43 on Ubuntu. Nrep on Chrome

**Comment by sgrekhov** [comment]
This is a Firefox on Linux issue. This test passes on Windows (FF and Chrome) and on Chrome on Linux. No fix needed.
