### ISSUE TITLE
Unexpected runtime error in object pattern tests

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1609]
The following line throws at runtime when I add the support for object patterns. From looking at the file I can say that my understanding matches that behavior, that is, that the error should be thrown at line 33 because of the cast of `null` to `num`

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/object_A01_t02.dart#L33

The stack trace is as follows:

```
Unhandled exception:
type 'Null' is not a subtype of type 'num' of ' in type cast'
#0      test (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/object_A01_t02.dart:33:53)
#1      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/object_A01_t02.dart:89:39)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

Similarly in another test.

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/object_A01_t03.dart#L37

But maybe I'm reading the test wrongly.

The stack trace is as follows:

```
Unhandled exception:
type 'Null' is not a subtype of type 'num' of ' in type cast'
#0      test (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/object_A01_t03.dart:37:61)
#1      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/object_A01_t03.dart:110:39)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-release-x64 co19/LanguageFeatures/Patterns/object_A01_t03
```

**Comment by sgrekhov** [comment]
@chloestefantsova 

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/object_A01_t02.dart#L33

Is Ok. It expects 
https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/object_A01_t02.dart#L88

But according to the stacj trace error occurs on the next line, line 89
https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/object_A01_t02.dart#L89

Why `Circle(2)` matches `case Circle(sizeAsInt: 10, areaAsNull: final c2 as num):`? `sizeAsInt` of the pattern has value `10`, but `sizeAsInt` of the `shape` in a switch statement is `2`. This pattern shouldn't match. The same is thrue about the next test

**Comment by eernstg** [comment]
Just an idea that came to mind: Could it be a matter of subpattern matching order?

If line 89 calls `test` and reaches line 33, and the pattern there checks the type of the scrutinee (`Circle`, so that's OK), then proceeds to the patternFields, but it starts with `areaAsNull: final c2 as num`, then we'd get the dynamic error. The matching process will then throw rather than failing. This would not happen if the matching process had checked `sizeAsInt: 10` first.

**Comment by chloestefantsova** [comment]
Thank you, @sgrekhov and @eernstg. It seems to be the order the checks are made indeed! I'm closing this issue and creating the one for the order of checks in the SDK repo.
