### ISSUE TITLE
Some of the pattern tests expect a record element to understand the `>` operation

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1613]
Some of the tests use the `>` operation in a sub-pattern of a record pattern. However, nothing is known about the type of the corresponding element of the record, and the compiler can't produce the code applying `>` to a receiver of the `Object` type.

Examples of the described expectations are the following:

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/record_A01_t05.dart#L47

https://github.com/dart-lang/co19/blob/f4bd100ed6fe9a1f9a98d6e4163d742824fbf21c/LanguageFeatures/Patterns/record_A01_t06.dart#L46

**Comment by sgrekhov** [comment]
This issue exists in map and list pattern tests as well. Good catch, thank you!
