### ISSUE TITLE
co19_2/LibTest/typed_data/Uint8ClampedList/shuffle_A01_t01 sometimes fails.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/co19#162]
co19_2/LibTest/typed_data/Uint8ClampedList/shuffle_A01_t01 sometime fails.

It is not guaranteed that a shuffle changes the order of the elements - it could be a 'perfect shuffle'.
The test data has 6 elements, giving 6! permutations.
Picking these at random, one would expect 1 in 720 shuffles to be 'perfect' and fail the test.

1. I suggest changing the test so that _most_ shuffles change the order.
Try ten that reuse the same random number generator, and check that most of them are different.

2. With a given seed (e.g. Random(6)), check that the same seed produces the same order.

**Comment by sgrekhov** [comment]
Fixed by 66507d7f096172a005abc889fd2b8b23084aecae

**Comment by athomas** [comment]
See also #167.
