### ISSUE TITLE
List literals need type arguments in some of the patterns tests

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1628]
In a patterns test a check is made as follows:

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/list_A01_t01.dart#L61

The testing procedure and the supposed matching line are as follows:

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/list_A01_t01.dart#L34-L36

The test currently fails at runtime, and I believe it's because the invocation of the testing procedure should say `test(<num>[1, 1])` instead of `test([1, 1])`.

My reasoning is as follows:

1. Procedure `test` accepts `List<dynamic>`, which is taken as the type context in inferring the type argument for the list literal in `test([1, 1])`. The downwards context wins, and the type arguments is inferred as `dynamic`.
2. In the testing procedure the runtime type of the value is `List<dynamic>`.
3. The first check in matching against the supposed pattern `<num>[1, > 0 || -42]` is testing for the type of the object.
4. `List<dynamic>` is not a subtype of `List<num>`, and the matching fails.

@eernstg, do you agree with my analysis?

A similar failure happens in another test.

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/list_A04_t05.dart#L77

**Comment by alexmarkov** [comment]
In addition to `co19/LanguageFeatures/Patterns/list_A01_t01` and `co19/LanguageFeatures/Patterns/list_A04_t05` mentioned above, the following tests for list patterns also suffer from the same problem:
```
co19/LanguageFeatures/Patterns/list_A01_t02
co19/LanguageFeatures/Patterns/list_A01_t03
```

The following tests for map patterns are also affected as they don't specify type arguments but expect maps of certain types:
```
co19/LanguageFeatures/Patterns/map_A01_t01
co19/LanguageFeatures/Patterns/map_A01_t03
```

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/map_A01_t01.dart#L76

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/map_A01_t01.dart#L51

**Comment by eernstg** [comment]
I agree with the analysis. It looks like the test is intended to test pattern matching with a list pattern that has a type argument. Many other list patterns in `test` don't have it, and their type argument would then be `dynamic` (based on the static type of the scrutinee `list` on line 35), so it makes sense to add the type argument in line 61 rather than removing the type argument in line 36 (for better coverage).

**Comment by alexmarkov** [comment]
Tests for map patterns need similar updates.
