### ISSUE TITLE
A runtime error in a patterns test that requires operators > and <= on a String

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1629]
The following line in a patterns test results in a runtime error.

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/logical_and_A01_t02.dart#L34

The failure happens when the list literal from that line is checked agains a pattern in another line.

https://github.com/dart-lang/co19/blob/ac4a905460672efd4006f633ea63d978ad577bf1/LanguageFeatures/Patterns/logical_and_A01_t02.dart#L25

As I understand it, an object with the runtime type `String` is passed as an element of the list of static type `List<dynamic>`. The process of matching against the pattern invokes operator < on the object, which a `String` doesn't have. It results in an error.

The stack trace is as follows:

```
stderr:
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method '>'.
Receiver: "1"
Tried calling: >(0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      matches (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/logical_and_A01_t02.dart)
#2      main (file:///b/s/w/ir/tests/co19/src/LanguageFeatures/Patterns/logical_and_A01_t02.dart:34:18)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Comment by alexmarkov** [comment]
`co19/LanguageFeatures/Patterns/logical_and_A03_t02` also has the same problem.

**Comment by alexmarkov** [comment]
Reopening as `LanguageFeatures/Patterns/logical_and_A03_t02`  which has the same problem is not fixed yet.

**Comment by alexmarkov** [comment]
It looks like the same happens in

https://github.com/dart-lang/co19/blob/780034a9476ea8e9de6d2eecf33e6e0f02a2c220/LanguageFeatures/Patterns/logical_and_A02_t02.dart#L39
https://github.com/dart-lang/co19/blob/780034a9476ea8e9de6d2eecf33e6e0f02a2c220/LanguageFeatures/Patterns/logical_and_A02_t02.dart#L27

**Comment by alexmarkov** [comment]
Also:

https://github.com/dart-lang/co19/blob/780034a9476ea8e9de6d2eecf33e6e0f02a2c220/LanguageFeatures/Patterns/logical_and_A03_t02.dart#L36
https://github.com/dart-lang/co19/blob/780034a9476ea8e9de6d2eecf33e6e0f02a2c220/LanguageFeatures/Patterns/logical_and_A03_t02.dart#L25
