### ISSUE TITLE
Make shuffle tests more robust

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#167]
The shuffle tests, e.g. [LibTest/typed_data/Uint32List/shuffle_A01_t01.dart](https://github.com/dart-lang/co19/blob/master/LibTest/typed_data/Uint32List/shuffle_A01_t01.dart#L35), shuffle lists of 6 elements.  This test fails if the shuffled list turns out to be the same as the original list. To lower the probability of a shuffle ending up with an identity, the number of elements in the list should be increased.

(Currently we see the test fails, because sometimes the shuffle ends up having the same order as the original list.)

**Comment by sgrekhov** [comment]
Fixed by  ce15738
