### ISSUE TITLE
The shuffle tests need to have proper types attached to them

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#169]
From [LibTest/typed_data/Float64x2List/shuffle_A01_t01.dart](https://github.com/dart-lang/co19/blob/master/LibTest/typed_data/Float64x2List/shuffle_A01_t01.dart#L17):
```dart
f64x2(x, y) => new Float64x2(x, y);

main() {
  var list = [
    f64x2(1.0, 2.0), f64x2(2.0, 3.0), f64x2(3.0, 4.0), f64x2(4.0, 5.0),
    f64x2(5.0, 6.0)
  ];
  var sl = new Float64x2List.fromList(list);
  ...
}
```

The `f64x2` has a return type of `dynamic`, which makes `list` have type `List<dynamic>`, which causes a type error at `new Float64x2List.fromList(list);`

**Comment by sgrekhov** [comment]
Fixed by  ce15738
