### ISSUE TITLE
LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart is racy

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#171]
The [LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart](https://github.com/dart-lang/co19/blob/master/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart) eagerly cancels the subscription for the `StreamSubscription s = dir.watch().listen((FileSystemEvent event) { ... });` stream after creating a directory entry. The event might be already reported from the OS, but by cancelling the subscription we don't wait for it.

Instead the test could be re-written like this:
```dart
import "dart:io";
import "dart:async";
import "../../../Utils/expect.dart";
import "../file_utils.dart";

main() {
  Directory dir = getTempDirectorySync();
  Directory target = getTempDirectorySync();
  asyncStart();

  StreamSubscription s;
  s = dir.watch().listen((FileSystemEvent event) {
    Expect.isFalse(event.isDirectory);
    dir.deleteSync(recursive: true);
    target.deleteSync();
    s.cancel();
    asyncEnd();
  });

  // Trigger a file system event.
  getTempLink(parent: dir, target: target.path);
}
```
Here we watch a directory and the program will not complete until we have received a `FileSystemEvent`, which we validate is the right event.

**Comment by mkustermann** [comment]
There is no need for a timer here.

Similarly other tests could be made time independent and less racy, e.g. `tests/co19_2/src/LibTest/io/FileSystemDeleteEvent/isDirectory_A01_t05.dart`

**Comment by sgrekhov** [comment]
@mkustermann, thank you for suggestion. But in this case temporary directories will be deleted only in the case when test pass. If anything goes wrong, then 
```dart
    dir.deleteSync(recursive: true);
    target.deleteSync();
    s.cancel();
```
is not called. That's why timer was added here. How often this test fails? May be simply to increase timeout before canceling the stream and calling of cleanup routine?

**Comment by sgrekhov** [comment]
@mkustermann thank you for clarification about `.timeout()`. Then what about of rewriting of the test (and all the similar) in the following way?

```dart
main() {
  Directory dir = getTempDirectorySync();
  Directory target = getTempDirectorySync();
  asyncStart();
  StreamSubscription s = dir.watch().listen((FileSystemEvent event) {
    Expect.isFalse(event.isDirectory);
    asyncEnd();
  });
  getTempLink(parent: dir, target: target.path);
  new Future.delayed(new Duration(seconds: 1), () {
    s.cancel().then((_) {
      dir.delete(recursive: true);
      target.delete();
    });
  });
}
```
