### ISSUE TITLE
Tests with STATIC_WARNING.UNNECESSARY_NULL_ASSERT_PATTERN

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#1734]
With https://dart-review.googlesource.com/c/sdk/+/278687 the following test started passing
```
co19/LanguageFeatures/Patterns/record_A02_t03
```
but these tests started failing
```
co19/LanguageFeatures/Patterns/switch_statement_A07_t02
co19/LanguageFeatures/Patterns/list_A05_t05
co19/LanguageFeatures/Patterns/switch_statement_A07_t01
```

There might be other tests that are currently failing with the analyzer, which also have such unnecessary patterns, but because these tests are already failing, we don't see them yet. I will report them later then.

I believe the [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md) does not describe warnings for unnecessary null-assert and null-check patterns, but I think @munificent reacted positively to implementing them, so they might be added to the spec.

**Comment by munificent** [comment]
> I believe the [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md) does not describe warnings for unnecessary null-assert and null-check patterns,

That's correct.

> but I think @munificent reacted positively to implementing them, so they might be added to the spec.

I definitely support these warnings, but I don't have any plans to actually specify them. I thought we were generally trying to move away from having warnings in the spec and leaving it up to implementations to decide how to handle them?

@leafpetersen

**Comment by eernstg** [comment]
@munificent, perhaps we could mention these warnings as *commentary*, such that we can perform the action of "taking the warnings out of spec docs" in one step (and then put them into some other documents?), without creating the obvious danger that we forget some of them.

**Comment by munificent** [comment]
Added a section to the proposal and tried to come up with some more warnings: https://github.com/dart-lang/language/pull/2813
