### ISSUE TITLE
LibTest/io/HttpClientRequest/done_A02_t01.dart is causing flakes

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#177]
Looking at this [code](https://github.com/dart-lang/co19/blob/master/LibTest/io/HttpClientRequest/done_A02_t01.dart):
```dart

test(String method) async {
  asyncStart();
  String helloWorld = "Hello test world!";
  HttpServer server = await HttpServer.bind(localhost, 0);
  server.listen((HttpRequest request) {
    request.response.write(helloWorld);
    request.response.close();
  });

  HttpClient client = new HttpClient();
  client.open(method, localhost, server.port + 1, "")
      .then((HttpClientRequest request) {
        request.done.catchError((_) {
          server.close();
          asyncEnd();
        });
        return request.close();
  });
}
```

It makes an http server `server` and connects to `server.port + 1`. Now sometimes this will work and sometimes this will fail, depending on whether there is some other process which has a server on `server.port + 1`.

This causes flakiness in our tests.

**Comment by sgrekhov** [comment]
@mkustermann, I see no other way to get an error before response is available. I tried several other way to get it but had no success. So I'm gooing simply to delete this test. Do you agree?

**Comment by mkustermann** [comment]
If you want to connect to a server which doesn't exist and ensure you get an appropriate error message on the http request, then we have to use a server port which is not otherwise used.

Since we run many tests, which often spawn servers, concurrently, it's not save to use `server.port + 1`. But we know for sure that the servers our tests spawn are never privileged. So they will be always higher than 1024. Which means one option would be to pick a port within 0..1024 which is unused on most platforms.

From common port lists (see [/etc/services](http://www.cs.cmu.edu/afs/cs/user/jl/services)) I could suggest using port 3 for example and adding a comment to the test, that we assume nothing listens on it.

**Comment by sgrekhov** [comment]
@mkustermann unfortunately using of port 3 (and any other from 0..1024 or higher) doesn't work. It produces "SocketException: OS Error: The remote computer refused the network connection." when calling `HttpClient.open()`. Only use of `server.port + 1` produses `HttpException: Invalid response line, uri = http://127.0.0.1:57949` that I need. No idea why. Is it a bug or feature of `HttpServer`?

**Comment by mkustermann** [comment]
> Only use of server.port + 1 produses HttpException: Invalid response line, uri = http://127.0.0.1:57949 that I need.

This does not work at all on my machine. How do you run this?

For testing that a connection got refused this test works:
```dart
import "dart:io";
import "../../../Utils/expect.dart";
test(String method) async {
  asyncStart();

  HttpClient client = new HttpClient();
  try {
    await client.open(method, 'localhost', 3, "");
  } catch (error) {
    Expect.isTrue('$error'.contains('refused'));
    asyncEnd();
  }
}
main() {
  test("no-such-method");
}
```

For testing that the connection succeeds but the protocol was not correct, e.g. you can use:
```dart
import "dart:io";
import "../../../Utils/expect.dart";

test(String method) async {
  asyncStart();

  final server = await HttpServer.bind('localhost', 0);
  server.listen((HttpRequest request) {
    request.response
      ..write('Hello test world!')
      ..close();
  });

  HttpClient client = new HttpClient();
  final request = await client.open(
      method, server.address.address, server.port, '');
  try {
    // This should throw.
    await request.close();
  } catch (error) {
    print('ERROR: $error');
    asyncEnd();
  }

  await client.close();
  await server.close();
}

main() async {
  asyncStart();
  await test('');
  await test('no such method');
  asyncEnd();
}
```
which will produce
```
 % dart test.dart
unittest-suite-wait-for-done
ERROR: HttpException: Connection closed before full header was received, uri = http://[::1]:40301
ERROR: HttpException: Connection closed before full header was received, uri = http://[::1]:34003
unittest-suite-success
```

I have not been able to get "HttpException: Invalid response line" in any way.

**Comment by sgrekhov** [comment]
> This does not work at all on my machine. How do you run this?

```dart
import "dart:io";
import "../../../Utils/expect.dart";

var localhost = InternetAddress.loopbackIPv4.address;

test(String method) async {
  asyncStart();
  String helloWorld = "Hello test world!";
  HttpServer server = await HttpServer.bind(localhost, 0);
  server.listen((HttpRequest request) {
    request.response.write(helloWorld);
    request.response.close();
  });

  HttpClient client = new HttpClient();
  client.open(method, localhost, server.port + 1, "")
      .then((HttpClientRequest request) {
    request.done.catchError((error) {
      print("Error: $error");
      server.close();
      asyncEnd();
    });
    return request.close();
  });
}

main() {
  test("no-such-method");
}
```
The above produces
```
unittest-suite-wait-for-done
Error: HttpException: Invalid response line, uri = http://127.0.0.1:53660
unittest-suite-success
```
Dart VM version: 2.1.0-dev.8.0 (Wed Oct 24 21:47:12 2018 +0200) on "windows_x64"

**Comment by sgrekhov** [comment]
Thank you for advices. Please review https://github.com/dart-lang/co19/pull/181

**Comment by mkustermann** [comment]
> The above produces

> unittest-suite-wait-for-done
> Error: HttpException: Invalid response line, uri = http://127.0.0.1:53660
> unittest-suite-success

> Dart VM version: 2.1.0-dev.8.0 (Wed Oct 24 21:47:12 2018 +0200) on "windows_x64"

For me the above produces this:

```
% dart test.dart
unittest-suite-wait-for-done
Unhandled exception:
SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 45824
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
% dart --version
Dart VM version: 2.1.0-edge.411518e068436903f3f72915f1ce5a33582b4f70 (Tue Oct 30 15:05:03 2018 +0100) on "linux_x64"
```

Could it be that there are some servers running on your system which the `port + 1` happens to connect to?

Otherwise this seems very likely to be a difference in behavior between linux and windows. Have you tried this on non-windows by any chance?

**Comment by sgrekhov** [comment]
> Otherwise this seems very likely to be a difference in behavior between linux and windows. Have you tried this on non-windows by any chance?
Exactly the same result as yours on Linux_64. Seems,  when HttpServer binds some port on Windows this affects port + 1 somehow. I'll investigate this and create a new issue if needed.

**Comment by mkustermann** [comment]
@sgrekhov Excellent, thank you very much for investigating!

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/181
