### ISSUE TITLE
Incorrect member conflict tests

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/co19#179]
Rules for member conflicts are described and discussed in https://github.com/dart-lang/sdk/issues/33235. Some `co19` tests expect compile-time errors for situations which are not defined to be conflicts. These are marked in https://github.com/dart-lang/sdk/blob/master/tests/co19_2/co19_2-kernel.status as `Legal, see #33235`.

There is a corresponding issue for fixing tests to conform to these rules: https://github.com/dart-lang/sdk/issues/33238

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/190
