### ISSUE TITLE
Tests initializer_not_a_constant_t0* are buggy

### ISSUE THREAD

**Issue by mhausner** [dart-lang/co19#18]
The tests listed below should reference the class C containing the expected compile-time error, for example by constructing an instance of the class in main(). Otherwise, the compiler is at liberty not to compile C and thus no compile-time error is observed.

Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t01
Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t02
Language/Classes/Constructors/Constant_Constructors/initializer_not_a_constant_t03
Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_superclass_t01
Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_superclass_t02

E.g:
```
class A {
}

class C {
  final x = new A();
  const C();
}

main() {
  const C(); // <<<< reference class C to ensure it gets compiled.
}
```

**Comment by sgrekhov** [comment]
Fixed. Please see ea952f48d41bf2362ff6edb7dc84c7e885f7502c
