### ISSUE TITLE
Make LibTest/io/Stdin/last_A02_t01.dart more robust

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#182]
From [LibTest/io/Stdin/last_A02_t01.dart](https://github.com/dart-lang/co19/blob/master/LibTest/io/Stdin/last_A02_t01.dart):

```dart
run_process() {
  stdin.last.then((List<int> l) { print(new String.fromCharCodes(l)); });
}

run_main() async {
  String executable = Platform.resolvedExecutable;
  String eScript = Platform.script.toString();
  int called = 0;

  await Process.start(executable, [eScript, "test"], runInShell: true).then(
      (Process process) async {
    process.stdin.writeln("Testme");
    process.stdin.close();
    await process.stderr.toList().then((errors){
      Expect.isTrue(errors.isEmpty);
    });
    await process.stdout.toList().then((out) {
      String res = systemEncoding.decode(out[0]);
      // Get rid from possible new line symbols here
      Expect.equals("Testme", res.trimRight());
      called++;
    });
  });
  Expect.equals(1, called);
```

There are at least two issues here:

* Using `stdin.last.then(...)` in  `run_process()` is not right, since `stdin` is `Stream<List<int>>`, i.e. a stream of bytes. The bytes can be delivered in any sizes, e.g. each individual byte can be devlivered on it's own. So it cannot be assumed that the bytes obtained in `stdin.last` is  the last line.

=> Instead something like `stdin.transform(utf8.decoder).transform(const LineSplitter()).last.then((lastLine) { ... });` will ensure to split the incoming bytes by line endings and gets the last line.

* Using `systemEncoding.decode(out[0])` to get the entire output of the subprocess is also not quite right, since it only looks at a prefix of the output.

=> Instead it should do something like `await process.stdout.transform(systemEncoding.decoder).join('')`.

We see the following flakiness on our build infrastructure:
```


FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Stdin/last_A02_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 660ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_last_A02_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/last_A02_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 01.000327s):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_last_A02_t01/out.dill

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <Testme>, actual: <>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      run_main.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/last_A02_t01.dart:34:14)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._complete (dart:async/future_impl.dart:476:7)
#8      Stream.toList.<anonymous closure> (dart:async/stream.dart:977:18)
#9      _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#11     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#12     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#13     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
#14     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
#15     _StreamController.close (dart:async/stream_controller.dart:621:5)
#16     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1728:21)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#21     _StreamController._add (dart:async/stream_controller.dart:639:7)
#22     _StreamController.add (dart:async/stream_controller.dart:585:5)
#23     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1290:35)
#24     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:18)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-mac-release-simdbc64 co19_2/LibTest/io/Stdin/last_A02_t01
```

**Comment by iarkh** [comment]
Hello,

Regarding the first suggestion:

> Using stdin.last.then(...) in run_process() is not right, since stdin is Stream<List<int>>, i.e. a stream of bytes. The bytes can be delivered in any sizes, e.g. each individual byte can be devlivered on it's own. So it cannot be assumed that the bytes obtained in stdin.last is the last line.
> => Instead something like stdin.transform(utf8.decoder).transform(const LineSplitter()).last.then((lastLine) { ... }); will ensure to split the incoming bytes by line endings and gets the last line.

This is a test for the Dart API Spec, so test `last_A02_t01` should check exact assertion from Spec. I.e. it should call "stdin.last" method and check that it does exactly the things written in the Spec.

I believe that if I call `stdin.transform(utf8.decoder).transform(const LineSplitter()).last`, I actually don't test `stdin.last`.

So which test result should I expect when `stdin.last.then(...)` is called?

I can check that result is a last line **or** some previous one... Is it acceptable?

**Comment by lrhn** [comment]
The one test you can do is to check that the list of bytes you get from `stdin.last` is a suffix of the bytes that you expect. You can't assume *how long* a suffix it is, just that there are no missing bytes that would come after that list.

Do not check for "lines" at all. Stdin is not guaranteed to be line based. Check that you get some "last" bytes.
