### ISSUE TITLE
(Phase 1) Issue for co-19 Test for Constants Project

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/co19#185]
Issue Tracker: https://github.com/dart-lang/language/issues/60
Feature specification:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/feature-specification.md
Implementation plan:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md

Phase 1 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60) 

What is the request?
As per implementation, 
The co19 team can start implementing tests early using the experimental flag. Those tests should not be tested by default by the Dart SDK until the feature has been released.

**Comment by athomas** [comment]
What's left to do here?

**Comment by iarkh** [comment]
I believe all done, maybe we will need to add some additional test when >>> operator is implemented for int.
