### ISSUE TITLE
[Class modifiers] Remove use of classes as mixins

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/co19#1875]
Pre-Dart 3 any class can be used as a mixin. In Dart 3, only `mixin class foo` (a declaration that defines both a class and a mixin.) and `mixin foo` are allowed:
https://github.com/dart-lang/language/issues/1643
https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md

There seems to be a bunch of classes in co19 that use classes as mixins, from this test run:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8788634602419351857/+/u/test_results/new_test_failures__logs_

Can we get those updated?

cc @lrhn

**Comment by sgrekhov** [comment]
@mit-mit please provide a link to the Gerrit changelist

**Comment by lrhn** [comment]
The CL which should (when it successfully lands) enable this is https://dart-review.googlesource.com/c/sdk/+/284304

If CFE/analyzer actually implements it correctly, there might be some tweaks needed, if they don't actually look at the `Function` declaration.

**Comment by mit-mit** [comment]
The mentioned changelist is the same as mentioned in https://github.com/dart-lang/co19/issues/1874#issuecomment-1438640378

**Comment by sgrekhov** [comment]
If you don't mind I'll fix if when CL is landed

**Comment by sgrekhov** [comment]
https://github.com/dart-lang/co19/pull/1907 added `// @dart=2.19` to all legacy mixin tests. I believe this fixed this issue. Closing it
