### ISSUE TITLE
(Set Literals) Co-19

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/co19#188]
***** Request: 
As per implementation Plan:

Task12 : (co19 tests)
co19 tests written.

****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

**Comment by sgrekhov** [comment]
Fixed. Tests can be fount at https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Set-literals
