### ISSUE TITLE
Potential typo in an expectation in a patterns test

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#1898]
It seems that the expectation `Object?` should be replaced with `(Object?)` in the following spots in the test.

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A05_t01.dart#L31-L32

https://github.com/dart-lang/co19/blob/7b4f3e723211011878e185db6fa57fbafabd6bb7/LanguageFeatures/Patterns/type_inference_A05_t01.dart#L35-L36

**Comment by sgrekhov** [comment]
#1903 will fix it
