### ISSUE TITLE
Set language version of tests mixing in classes to 2.19

### ISSUE THREAD

**Issue by munificent** [dart-lang/co19#1899]
Dart 3.0 makes it an error to mixin a class that isn't marked `mixin class`. This breaks a lot of existing Dart SDK tests that were doing that, often for unrelated reasons:

* Many of these tests are older than mixin declaration syntax so mixing in a class was the only way to test any mixin functionality.

* Some of them are deliberately mixing in classes, and those classes should just be marked `mixin`.

* Some of them are mixing in classes from the core libraries that are no longer allowed to be mixins.

* There are probably other reasons I'm not thinking of.

Eventually, we'll want to figure out why each of these tests is mixing in a class and fix it appropriately. But, for now, in order to be able to enable the "class-modifiers" flag, we want to just get the tests passing and continuing to behave the way they do today.

The easiest way to fix most of those tests is to simply pin them to language version 2.19. If the class that the test is mixing in is defined in the same library, then this will preserve the current behavior. It's only an error to mixin a non-`mixin` class if the class is declared in a Dart 3.0 library. This probably won't fix *all* test failures since some tests may be mixing in classes from other libraries, but it should fix most.

I landed [a fix](https://dart-review.googlesource.com/c/sdk/+/285923). for the language/ and lib/ tests today. Can you do a similar fix for the co19 tests?

Here is tweaked version of the very hacky script I wrote to add the `@dart=2.19` comments to all of the SDK tests. It includes a list of all of the co19 tests that were failing because of mixin errors as of a couple of days ago:

https://gist.github.com/munificent/b81adc0eaec0db34be713755982cc72c

You may need to tweak it a bit to get it to work, but that should get you started.

Thank you, and let me know if there's anything I can do to help.

cc @jakemac53

**Comment by jakemac53** [comment]
I also am seeing failures related to extending classes which are now listed as `final`. See the logs here for at least some, there may be more https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787787247092936257/+/u/test_results/new_test_failures__logs_.

**Comment by sgrekhov** [comment]
@munificent thank you for the script. I modified it to handle generated tests and to add language version at the end of the description. I also removed from the script tests that already had language version lover than 2.19 (`co19/LanguageFeatures/nnbd/weak/overriding/*`)
Please see #1907
