### ISSUE TITLE
Document.getCSSCanvasContext is removed (and deprecated) from Chrome

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#19]
Document.getCSSCanvasContext is a non-standard extension that is now removed. See https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/WvqvdsmiQzg

Three tests (or more) probably fail because of this, and should be removed or rewritten:
LayoutTests/fast/canvas/canvas-as-image_t01: RuntimeError # Please triage this failure
LayoutTests/fast/canvas/canvas-css-crazy_t01: RuntimeError # Please triage this failure
LayoutTests/fast/canvas/crash-set-font_t01: RuntimeError # Please triage this failure

**Comment by sgrekhov** [comment]
Fixed. Tests rewritten. See 551719d2f407c232f584d297bc3b862fcc67e093
