### ISSUE TITLE
Triaged CFE test failures with patterns and records enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/co19#1902]
I'm working on enabling the "records" and "patterns" experiment flags in the SDK. Turning those features on causes some co19 tests to fail because the expected behavior has changed. I went ahead and triaged the [failures for the front end tests](https://ci.chromium.org/ui/p/dart/builders/try/front-end-nnbd-linux-release-x64-try/20835/overview) and it looks like they should all be fairly straightforward fixes:

**`()` is a valid expression now:**

co19/Language/Classes/definition_t15.dart
co19/Language/Expressions/Instance_Creation/Const/syntax_t03
co19/Language/Reference/Lexical_Rules/Reserved_Words/const_t05
co19/Language/Reference/Lexical_Rules/Reserved_Words/return_t05
co19/Language/Reference/Lexical_Rules/Reserved_Words/throw_t05
co19/Language/Reference/Lexical_Rules/Reserved_Words/is_t05

**Constants and switches don't need to have primitive equality any more:**

co19/Language/Statements/Switch/equal_operator_t01
co19/Language/Statements/Switch/equal_operator_t02
co19/LanguageFeatures/nnbd/static_errors_A30_t03

**Non-empty switch cases are no longer require to have an explicit exit:**

co19/Language/Statements/Switch/execution_case_no_default_t03
co19/Language/Statements/Switch/execution_case_t03
co19/Language/Statements/Switch/last_statement_t01
co19/LanguageFeatures/nnbd/static_errors_A29_t01
co19/LanguageFeatures/nnbd/static_errors_A29_t02

**Case constants no longer have to have the same type as the switched value:**

co19/Language/Statements/Switch/execution_t01
co19/Language/Statements/Switch/expressions_t01
co19/Language/Statements/Switch/expressions_t02
co19/Language/Statements/Switch/expressions_t03
co19/Language/Statements/Switch/expressions_t04
co19/Language/Statements/Switch/type_t01
co19/Language/Statements/Switch/type_t02
co19/LanguageFeatures/nnbd/static_errors_A30_t02

**Some expressions are no longer valid in cases:**

co19/Language/Statements/Switch/syntax_t01

**A new non-exhaustive switch error is being correctly reported but not expected by the test:**

co19/LanguageFeatures/nnbd/static_errors_A30_t04
co19/LanguageFeatures/nnbd/static_errors_A30_t07
co19/LanguageFeatures/nnbd/static_errors_A30_t08

**I'm not sure what's going on here, but I would only expect an error on the second `default`:**

co19/Language/Statements/Switch/syntax_t16

Let me know if you want any suggestions on how to update the tests. You probably know better than I do. :)

**Comment by sgrekhov** [comment]
@munificent please clarify how `records` and `patterns` experimental flags are going to be used? Some syntax that was wrong before these flags now became valid. For example
```dart
  const []; // Ok
  const (); // Ok with records, compile time error without records
```
If we are going to always run co19 tests with these flags enabled, then no problem, I'll change the tests according to the new syntax. But if we are going to run the tests in both modes (with and without new flags) then I'm not sure if we need to change the tests now

cc @athomas @eernstg

**Comment by athomas** [comment]
The bulk of the tests should assume that records and patterns are enabled by default (soon they will be). If a test already needs features from records or patterns then it needs the experiment flag (similar to how we do feature specific testing). Post-3.0 we will remove those experiment flags from the tests.

If we want to test that `const ();` is an error on language version 2.19, we should create specific tests for that language version that specific the language version they require `// @dart=2.19`.

**Comment by munificent** [comment]
What @athomas said. :) Unlike null safety, we are not planning to fork all of the tests with pre-records/patterns and post-records/patterns copies of each one. Most will just be migrated directly to be valid with records and patterns and then we'll add tests as needed to verify behavior under 2.19 that differs from 3.0.

**Comment by sgrekhov** [comment]
Thank you. Please see https://github.com/dart-lang/co19/pull/1908
