### ISSUE TITLE
Update co19 tests to reflect the changed rule about map pattern matching

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#1976]
The language team decided that map pattern matching should be 'loose' rather than 'strict', in the sense that there is no support for the rest element in a map pattern (such as the `...` in `{"key1": value1, ...}`), and map pattern matching will allow key/value pairs to exist even though they are not matched (that is, `{"key1": value1}` now works in the same way as `{"key1": value1, ...}` used to work).

The co19 tests need to be updated correspondingly: Map patterns with `...` should be a compile-time error, and existing tests using map patterns with `...` should be updated to not have that, and they should expect the same behavior as they did before this change (with `...` and with the old semantics). Tests about map patterns where `...` did not occur should behave the same if a `when` clause is added where the length is tested. And tests about map patterns where `...` did not occur should no longer use `length` to verify that there are no non-matched key-value pairs (they may still call `length` in order to verify that there are _enough_ key/value pairs to satisfy the given set of field patterns).

**Comment by sgrekhov** [comment]
There are some runtime errors
