### ISSUE TITLE
False passes in webgl tests on Mac

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#20]
For some time all the webgl tests were suppressed due to https://github.com/dart-lang/sdk/issues/22026 

However, they're running now on the Mac bots, and this reveals a number of passes that seem suspect or outright wrong.

**Comment by alan-knight** [comment]
Issues with what seem like false passes, in Dartium, on Mac are

LayoutTests/fast/canvas/webgl/gl-object-get-calls_t01
LayoutTests/fast/canvas/webgl/incorrect-context-object-behaviour_t01
LayoutTests/fast/canvas/webgl/null-object-behaviour_t01
LayoutTests/fast/canvas/webgl/bad-arguments-test_t01
LayoutTests/fast/canvas/webgl/context-lost_t01
LayoutTests/fast/canvas/webgl/framebuffer-test_t01
LayoutTests/fast/canvas/webgl/invalid-passed-params_t01
LayoutTests/fast/canvas/webgl/tex-input-validation_t01
LayoutTests/fast/canvas/webgl/tex-sub-image-2d-bad-args_t01

**Comment by sgrekhov** [comment]
@alan-knight Why do you believe that passes of these tests are false? The first 3 of them works for me (under dart2js on ubuntu), the other fail. Is there a way to run these tests under Dartium on Ubuntu (I get' Unable to fetch WebGL rendering context for Canvas' under Dartium)?

**Comment by alan-knight** [comment]
I think they're false passes because none of the bots are able to run WebGL at all, according to dartbug.com/22026  And if the ones after the first three are failing for you, then they probably shouldn't be passing on the bots. bad-arguments-test_t01 and context-lost_t01, the first two I checked, are showing as passing on the Mac bot, when it fails for me locally.

I get the same error on Ubuntu, it may be completely broken.

**Comment by sgrekhov** [comment]
bad-arguments-test_t01 failed because of bug in the test. Fixed. 5dccd0cfd6c8c8dd22da459b35bf1c8de67fec38

**Comment by sgrekhov** [comment]
At least I was able to run all of these tests in Dartium. All of these tests passes for me under Windows and Linux as well. So I think that no any change in tests needed. Just update co19-dartium.status file (remove all of these test from this file). Unfortunately I have no grants for this.

**Comment by alan-knight** [comment]
These seem to be passing for me now locally on Mac, so that seems all right. They're suppressed for Windows and Linux because our bots don't run WebGL. This is annoying, because it produces different results locally and on the bots, but I don't know what to do about it.
