### ISSUE TITLE
Failures on Patterns flow analysis: recognize trivially exhaustive switches.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#2010]
There are new test failures on [Patterns flow analysis: recognize trivially exhaustive switches.](https://dart-review.googlesource.com/c/sdk/+/293860).

The tests
```
co19/LanguageFeatures/Patterns/Exhaustiveness/lifting_cast_pattern_A01_t01 MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-linux
cfe-strong-linux
cfe-weak-linux
```

For example, here is the failure message from the analyzer:
```
static error failures:
- Missing expected unspecified error at line 20, column 5, length 5.
```

What's happening is that the analysis has been improved.  Previously a bogus error was issued for `test1`, claiming that control flow might reach the end of the function without returning a value; with this fix, that bogus error is gone.

**Comment by sgrekhov** [comment]
@stereotype441 updated test (which works in the current analyzer and CFE) looks like:
```dart
int test1(Object obj) {
  switch (obj) {
    case int(isEven: true) as int:
      return 1;
    case int _:
      return 2;
  }
}

int test2(Object obj) => switch (obj) {
//                       ^^^^^^
// [analyzer] unspecified
// [cfe] unspecified
    int(isEven: true) as int => 1,
    int _ => 2
  };

main() {
  test1(1);
  test2(2);
}
```
If this switch is exhaustive then why there is still an error for the switch expression?

**Comment by stereotype441** [comment]
> co19/LanguageFeatures/Patterns/Exhaustiveness/lifting_cast_pattern_A01_t01

It looks like this is a rare case where flow analysis is smarter than the exhaustiveness checker.  I filed https://github.com/dart-lang/sdk/issues/51986.
