### ISSUE TITLE
Remove experiment flags for 3.0 features

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#2046]
Experiments to remove:
```
sealed-class
class-modifiers
records
patterns
```

/cc @eernstg

**Comment by sgrekhov** [comment]
Need to remove experiments in Dart SDK

**Comment by sgrekhov** [comment]
https://dart-review.googlesource.com/c/sdk/+/309660
https://dart-review.googlesource.com/c/sdk/+/309680
