### ISSUE TITLE
Tests of experimental language features need "--enable-experiment" flags

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#208]
The new language features tested by `LanguageFeatures/Constant_update2018` and `LanguageFeatures/Set-literals` are not yet enabled by default by Dart tools; in order to test them, they need to be explicitly enabled by adding one of the following comments to the `.dart` files:

- `// SharedOptions=--enable-experiment=set-literals`
- `// SharedOptions=--enable-experiment=constant-update-2018`

Note that the test infrastructure searches for exactly the string `// SharedOptions=`, so adding a `SharedOptions=` annotation to a `/*` style comment is not sufficient.

For more information, see https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md

@athomas

**Comment by sgrekhov** [comment]
Fixed by 8b40b18b6167505d1788fc16c2fd78693a33f7e9 and 0be959898e1c1ce0398168c2b253ad8d0cb3d01e
