### ISSUE TITLE
New error in LanguageFeatures/Enhanced-Enum/grammar_A01_t02.dart

### ISSUE THREAD

**Issue by kallentu** [dart-lang/co19#2105]
Fiddling with the constant evaluator added another error to `LanguageFeatures/Enhanced-Enum/grammar_A01_t02.dart` 
```
/============================================================================================================\
| co19/LanguageFeatures/Enhanced-Enum/grammar_A01_t02 broke (Pass -> MissingCompileTimeError, expected Pass) |
\============================================================================================================/

--- Command "dart2analyzer" (took 49ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/gen/dartanalyzer.dart.snapshot -Dtest_runner.configuration=analyzer-asserts-linux --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json --format=json /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Enhanced-Enum/grammar_A01_t02.dart

static error failures:
- Unexpected error at line 1, column 0, length 2: COMPILE_TIME_ERROR.CONST_EVAL_METHOD_INVOCATION
```

While this error is a little non-sensical, it's mostly due to the parsing errors and how the rest of the analyzer handles the recovered code. I don't expect this to be fixed on the analyzer side, but wanted to create an issue to make sure the failure is captured and if we could handle it in this test perhaps.

**Comment by kallentu** [comment]
Context is this change: https://github.com/dart-lang/sdk/commit/c86af3c39ba3593d829701e866bf40bc0a8a6317

**Comment by sgrekhov** [comment]
@kallentu  thank you for additional info. I was able to reproduce the issue on the freshly build SDK. Fixed

**Comment by kallentu** [comment]
Thanks for helping fix it :)
