### ISSUE TITLE
Type error in LibTest/collection/DoubleLinkedQueue/removeFirst_A01_t01

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#22]
LibTest/collection/DoubleLinkedQueue/removeFirst_A01_t01

The type error given in checked mode is correct. DoubleLinkedQueue implements Queue, not the other way around.

Unhandled exception:
type 'ListQueue' is not a subtype of type 'DoubleLinkedQueue' of 'list'.
#0      main (file:///usr/local/google/home/regis/dart1/sdk/tests/co19/src/LibTest/collection/DoubleLinkedQueue/removeFirst_A01_t01.dart:35:14)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by sgrekhov** [comment]
Fixed. 47cbb3d7b09c44ee146375395dc20fbd7aea4edc
