### ISSUE TITLE
rename_A02_t03 failing 

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/co19#2284]
[rename_A02_t03](https://github.com/dart-lang/co19/blob/00292501dd4d8b0e246130d55a024727e31d62eb/LibTest/io/Link/rename_A02_t03.dart) is failing because it expects that you cannot rename a `Link` to the path of an existing `File`.

That is actually allowed but our documentation was incorrect. I've fixed it in https://github.com/dart-lang/sdk/commit/5b7b8aab40e017d2a13348b36df3a2c2a5c42b71

I could not find any other tests impacted by this but I didn't look very carefully.

**Comment by sgrekhov** [comment]
Note https://github.com/dart-lang/sdk/issues/53583
