### ISSUE TITLE
create_A04_t04 should not expect that the target of the symlink must exist on Windows

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/co19#2291]
This is the [relevant code](https://github.com/dart-lang/co19/blob/dcc3cbe37ae5aa0212987d2038d70fba7139a3ed/LibTest/io/Link/create_A04_t04.dart#L46).

I've updated the docs in [this PR](https://dart-review.googlesource.com/c/sdk/+/328661/3/sdk/lib/io/link.dart).

I think that this test can just be deleted.

**Comment by sgrekhov** [comment]
According to the updated docs if we are create Link to a not existing directory then this link should be created and be a file simlink. I'll change the tests accordingly.
If you don't mind I'll do it after the landing of the PR

**Comment by brianquinlan** [comment]
Sure. The PR is documentation-only though.
