### ISSUE TITLE
Bound error in LibTest/collection/LinkedList/LinkedList_A01_t01

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#23]
The bound error reported in LibTest/collection/LinkedList/LinkedList_A01_t01 is correct, since type parameter String does not extend upper bound LinkedListEntry<String>

'dart:collection/linked_list.dart': malbounded type: line 31: type parameter 'E' of class 'LinkedList' must extend bound 'LinkedListEntry<E>', but type argument 'String' is not a subtype of 'LinkedListEntry<String>'

class LinkedList < E extends LinkedListEntry < E >>
                   ^
'file:///usr/local/google/home/regis/dart1/sdk/tests/co19/src/LibTest/collection/LinkedList/LinkedList_A01_t01.dart': malbounded type: line 29 pos 13: type 'LinkedList<String>' has an out of bound type argument
  check(new LinkedList<String>());
            ^
type error.
#0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:58)
#1      main (file:///usr/local/google/home/regis/dart1/sdk/tests/co19/src/LibTest/collection/LinkedList/LinkedList_A01_t01.dart:29:13)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by sgrekhov** [comment]
Fixed. 4e5e611497f910c730ccdc1801ba9997e0592d3b
