### ISSUE TITLE
Compile-time error errors due to exact types of set literals

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/co19#230]
`LanguageFeatures/Set-literals/exact_types_of_literals_A01_t03.dart` has:

```dart
  LinkedHashSet<int> v11 = {};
  Expect.isTrue(v11 is LinkedHashSet<int>);
```
The first line is a compile-time error.  The empty non-const set/map literal is a set literal, so it has static type `Set<T>` for some `T`.

Type inference tries to satisfy `Set<T> <: LinkedHashSet<int>` by choosing `T` but there is no such `T` and so it infers `Set<dynamic>`.

The rules for exact types of literals require us to reject the assignment of the `Set<dynamic>` to `LinkedHashSet<int>` with a compile-time error because `LinkedHashSet<int>` is not a supertype of `LinkedHashSet<dynamic>`.

**Comment by kmillikin** [comment]
For the same reason, `LanguageFeatures/Set-literals/semantics_A05_t01.dart` has a compile-time error.  It has:

```dart
LinkedHashSet<int> test4() => {};
```

which is a compile-time error.

**Comment by lrhn** [comment]
Correct. The "exact type" for set and map literals is going to be `Set<T>`/`Map<K,V>`, and not any of the `LinkedHash`-subclasses.
I originally said something else in the feature document, but that was based on a misunderstanding of what we currently do for maps. This has (now) been fixed to match the formal language specification (which is now complete and should be used as the source of truth for this feature).

**Comment by sgrekhov** [comment]
@lrhn, please, update [feature specification examples](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md#examples) section. It contains

> /*
> context                  expression            runtime type and const-ness
> */
> ...
> LinkedHashSet<int> v11 = {};                // LinkedHashSet<int>

I can add an issue for Language, if needed

**Comment by lrhn** [comment]
Good catch. I've fixed it
