### ISSUE TITLE
`FileSystemEntity.type()` called on a broken symlink should return `notFound` on all platforms

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/co19#2329]
A list of required changes is here: [new_test_failures__logs_.txt](https://github.com/dart-lang/co19/files/13129032/new_test_failures__logs_.txt)

This is required to unbreak https://dart-review.googlesource.com/c/sdk/+/331841

**Comment by sgrekhov** [comment]
@brianquinlan  Fix is prepared here https://github.com/dart-lang/co19/pull/2332. But I'm waiting for landing of https://dart-review.googlesource.com/c/sdk/+/331841 first. It's a common practice when we do a change and then update failing co19 tests

**Comment by eernstg** [comment]
Oh, I just reviewed and landed #2332, I hope that doesn't create any problems.

**Comment by sgrekhov** [comment]
Ok. I'll simply check the status of the  https://dart-review.googlesource.com/c/sdk/+/331841 before doing the next roll. No problem, thank you!

**Comment by eernstg** [comment]
Very good, thanks!

**Comment by brianquinlan** [comment]
https://dart-review.googlesource.com/c/sdk/+/331841 is merged
