### ISSUE TITLE
A extension-types test expecting an error on implementing Object should be corrected

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/co19#2338]
The following test expects a compile-time error on extension types implementing `Object`.

https://github.com/dart-lang/co19/blob/b1935e565325b156ec2408063559859e1529c3d6/LanguageFeatures/Extension-types/static_analysis_extension_types_A10_t03.dart#L35-L38

According to https://github.com/dart-lang/sdk/issues/53840, an extension type can implement `Object`. After landing https://dart-review.googlesource.com/c/sdk/+/333000 the CFE will stop the emit the error, and the test should be updated.

**Comment by sgrekhov** [comment]
This issue is addressed by https://github.com/dart-lang/co19/pull/2328. Please review

**Comment by sgrekhov** [comment]
Fixed by #2328
