### ISSUE TITLE
[Extension type] Add more constant constructors tests

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#2349]
Add tests based on examples from
https://github.com/dart-lang/sdk/issues/53934
https://github.com/dart-lang/sdk/issues/53935
https://github.com/dart-lang/sdk/issues/53936

**Comment by eernstg** [comment]
Thanks!

**Comment by sgrekhov** [comment]
Closing this issue. Added tests for the cases, described in https://github.com/dart-lang/sdk/issues/53935 and https://github.com/dart-lang/sdk/issues/53936
Tests for https://github.com/dart-lang/sdk/issues/53934 will be added as part of #2350
