### ISSUE TITLE
Nullable this as non-nullable

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#2356]
The tests

`co19/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A02_t02`
`co19/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A02_t03`

seem to assume that `this` is non-nullable even when the representation type is not non-nullable:
```
extension type ET1<T>(T id) {
  Object test1() => this;
```
The getter should probably return `Object?` instead.

**Comment by sgrekhov** [comment]
@johnniwinther what's wrong with `co19/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A02_t03`? It doesn't have such method. How can I reproduce this issue?

**Comment by johnniwinther** [comment]
Turns out the (other) test was `co19/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t02`. It (still) has the same problem.
