### ISSUE TITLE
Layout test times out on failure due to async testing error

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#242]
The test
LayoutTests/fast/css-generated-content/pseudo-transition_t01.dart

has an error near line 77, where the failures should be in a try-finally block so the asyncEnd is reached.

The asyncEnd should be protected by try-finally so it always executes:

Existing code:

testTransition(id)
--
  | {
  | var div = document.getElementById(id);
  | div.className = 'transition';
  | shouldBe(div.offsetWidth, 52);
  | // This will be flaky, but it's a reasonable approximation for testing
  | // in a browser instead of DRT.
  | setTimeout(() {
  | shouldBeCloseTo(div.offsetWidth, 20, 1);
  | var computedTop = getPseudoComputedTop(id);
  | shouldBeCloseTo(computedTop, 170, 1);
  | }, 1000);
  | setTimeout(() {
  | shouldBeCloseTo(div.offsetWidth, 12, 1);
  | var computedTop = getPseudoComputedTop(id);
  | shouldBeCloseTo(computedTop, 200, 1);
  | asyncEnd();
  | }, 2000);
  | }
  |  
  | asyncMultiStart(2);
  |  
  | testTransition('before');
  | testTransition('after');

new code suggestion, or else put the asyncEnd() in its own timer, of 2500 ms:

testTransition(id)
  {
    var div = document.getElementById(id);
    div.className = 'transition';
    // This will be flaky, but it's a reasonable approximation for testing
    // in a browser instead of DRT.
    setTimeout(() {
      shouldBeCloseTo(div.offsetWidth, 20, 1);
      var computedTop = getPseudoComputedTop(id);
      shouldBeCloseTo(computedTop, 170, 1);
    }, 1000);
    setTimeout(() {
     try {
        shouldBeCloseTo(div.offsetWidth, 12, 1);
        var computedTop = getPseudoComputedTop(id);
        shouldBeCloseTo(computedTop, 200, 1);
      } finally {
        asyncEnd();
      }
    }, 2000);
    shouldBe(div.offsetWidth, 52);
  }

  asyncMultiStart(2);
  testTransition('before');
  testTransition('after');

**Comment by sgrekhov** [comment]
@whesse please clarify, why asyncEnd() should always be protected by try-finally? If there is a failure inside of some code with asyncEnd() at the end, then test fail anyway. I treated asyncEnd() as an indicator that some async code was called, not more. There are more than 2K asyncEnd() calls in co19 tests, it'll took some time to wrap all of them

**Comment by whesse** [comment]
Because browsers do not quit on throwing an error, but continue running all other scheduled calls, a test running on a browser does not know it is complete until all the async jobs it is waiting for report that they are done.  This is when the number of asyncEnd() calls equals the arg to asyncMultiStart().

We may be able to improve the JS test driver code, so that it knows that a test has failed once it receives the first thrown error, and can stop it then.  I'll look into this.  But otherwise, all the asyncEnd() calls should be guaranteed to be hit even in failing cases.  They turn into timeouts otherwise.

**Comment by whesse** [comment]
Retrying this test, it seems like the runtime error is correctly sent to the driver page, and the test fails, even though the asyncEnd is not hit.  So something in my diagnosis of the timeout error I saw was incorrect, and it is OK to have failing tests that throw exceptions not hit the asyncEnd.  Closing the issue.
