### ISSUE TITLE
Exhaustiveness uses extension type erasure

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#2420]
@sgrekhov, do we have coverage for the following kind of situation?

```dart
sealed class S {}
class A extends S {}
class B extends S {}

extension type E(B it) {}

void f(S s) {
  var x = switch (s) {
    A() => 1,
    E() => 2,
  };
}
```

In a situation where we wish to determine whether or not a given switch (expression or statement) is exhaustive, we should use the extension type erasure of every extension type that we encounter (as an object pattern in a case, as the type of the matched value, in a cast pattern, whatever).

It is important that we consider the extension type erasure and not just the declared superinterface relationships of the extension types, because the actual exhaustiveness property is determined by the run-time types of the objects that we're working with, and that is again approximated at compile time by the extension type erasure (and not in a useful way by the extension type itself).

I don't remember seeing any tests of this nature, but I might have forgotten. It would be great if you could take a look, and put it on the TODO list if we don't have anything.

**Comment by sgrekhov** [comment]
No, we don't. I'll add them, thank you!
