### ISSUE TITLE
Implicit `call` method tear-offs with extension typed receivers

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#2428]
The proposal in https://github.com/dart-lang/language/issues/3467 was accepted by the language team. This means that it should be possible to perform `.call` method tear-offs also in the case where the receiver is an expression whose static type is an extension type. In this case it should be possible to tear off both a `call` method which is a non-extension type member (that is, inherited from some "normal" type), and also a `call` method which is an extension type member (from the receiver type or "inherited" from some other extension type).

@sgrekhov, I think no such tests have been written, isn't that true?

**Comment by sgrekhov** [comment]
We have a couple of tests that dealing with a `call()` method but not in the way described in https://github.com/dart-lang/language/issues/3467
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t05.dart
https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/dynamic_semantics_member_invocation_A03_t06.dart

I'll add more tests

**Comment by eernstg** [comment]
Thanks! dynamic_semantics_member_invocation_A03_t06.dart gets close because it uses the `call` of an extension type implicitly in line 45 and 47. But it's an invocation, and the new thing is that it can also be a tear-off.
