### ISSUE TITLE
Update exhaustiveness tests according to the language#3524

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#2439]
Update exhaustiveness tests according to the https://github.com/dart-lang/language/issues/3524
List of the tests that should be updated can be found here https://github.com/dart-lang/co19/pull/2437/files

**Comment by eernstg** [comment]
Thanks! The info needed is whether the language team wishes to have that always-exhaustive status propagate from an extension type erasure to the corresponding extension type. dart-lang/language#3524 should answer that question.

**Comment by sgrekhov** [comment]
Closing this issue. All of the tests mentioned in https://github.com/dart-lang/co19/pull/2437 works on the latest SDK. Some of the tests were failing but they now are fixed by https://github.com/dart-lang/co19/pull/2450
