### ISSUE TITLE
const literals can't contain double keys

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/co19#247]
ERROR|COMPILE_TIME_ERROR|CONST_MAP_KEY_EXPRESSION_TYPE_IMPLEMENTS_EQUALS|/b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LanguageFeatures/Control-flow-collections/static_semantics_A02_t01.dart|57|16|3|The constant map entry key expression type 'double' can't override the == operator.

I believe this is correct.

```
It is a compile-time error if                                                    
the operator \lit{==} of the key of an entry in a constant map literal           
is not primitive 
```

The section on the == operator lists primitive == operators, and it only list String, int, Type, Symbol, Object, Null, bool, functions, lists, maps, and sets.

@eernstg in case he knows why doubles weren't included.

**Comment by eernstg** [comment]
True, `double` is not included here. One reason for omitting it is that equality for doubles is a bit unusual, and in particular not-a-number is not equal to itself so it's not even reflexive (all comparisons return false).
