### ISSUE TITLE
co19/LibTest/async/Timer/Timer.periodic_A02_t01 is flaky

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/co19#2471]
The tests
```
co19/LibTest/async/Timer/Timer.periodic_A02_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-linux-debug-simriscv64
```

The test went from flaky to failing. From the [log](https://dart-ci.appspot.com/log/vm-linux-debug-simriscv64/vm-linux-debug-simriscv64/419/co19/LibTest/async/Timer/Timer.periodic_A02_t01), it seems like a duration is slightly longer than expected. So it will probably revert to flaky again.

**Comment by eernstg** [comment]
Thanks for the input, I just landed #2472.
