### ISSUE TITLE
Migrate `Pointer.elementAt` to `operator +`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/co19#2486]
`Pointer.elementAt` has been deprecated in Dart 3.3, and will be removed in Dart 3.4.

The removal CL is making a bunch of co19 tests fail:

co19/LibTest/ffi/Bool/Bool_A02_t01
co19/LibTest/ffi/Char/Char_A02_t01
co19/LibTest/ffi/Int/Int_A02_t01
co19/LibTest/ffi/Int16/Int16_A02_t01
co19/LibTest/ffi/Int32/Int32_A02_t01
co19/LibTest/ffi/Int64/Int64_A02_t01
co19/LibTest/ffi/Int8/Int8_A02_t01
co19/LibTest/ffi/IntPtr/IntPtr_A01_t03
co19/LibTest/ffi/Long/Long_A02_t01
co19/LibTest/ffi/LongLong/LongLong_A02_t01
co19/LibTest/ffi/Pointer/elementAt_A01_t01
co19/LibTest/ffi/Pointer/elementAt_A01_t02
co19/LibTest/ffi/Pointer/elementAt_A01_t03
co19/LibTest/ffi/Pointer/elementAt_A01_t04
co19/LibTest/ffi/Pointer/elementAt_A04_t01
co19/LibTest/ffi/Pointer/elementAt_A04_t02
co19/LibTest/ffi/Short/Short_A02_t01
co19/LibTest/ffi/SignedChar/SignedChar_A02_t01
co19/LibTest/ffi/Struct/Struct_A05_t01
co19/LibTest/ffi/Struct/Struct_A05_t02
co19/LibTest/ffi/Struct/Struct_A05_t03
co19/LibTest/ffi/Uint16/Uint16_A02_t01
co19/LibTest/ffi/Uint32/Uint32_A02_t01
co19/LibTest/ffi/Uint64/Uint64_A02_t01
co19/LibTest/ffi/Uint8/Uint8_A02_t01
co19/LibTest/ffi/UintPtr/UintPtr_A02_t01
co19/LibTest/ffi/Union/Union_A05_t01
co19/LibTest/ffi/Union/Union_A05_t02
co19/LibTest/ffi/Union/Union_A05_t03
co19/LibTest/ffi/UnsignedChar/UnsignedChar_A02_t01
co19/LibTest/ffi/UnsignedInt/UnsignedInt_A02_t01
co19/LibTest/ffi/UnsignedLong/UnsignedLong_A02_t01
co19/LibTest/ffi/UnsignedLongLong/UnsignedLongLong_A02_t01
co19/LibTest/ffi/UnsignedShort/UnsignedShort_A02_t01

https://dart-review.googlesource.com/c/sdk/+/346380
https://dart-ci.firebaseapp.com/cl/346380/3

@sgrekhov Could you please migrate these tests or guide @shikharish to migrate these tests?
The `elementAt` tests could be replaced with `operatorPlus` tests.

FYI @shikharish We need to have these tests updated as well, before we can land the CL.

Context:

* https://github.com/dart-lang/sdk/issues/54250

**Comment by sgrekhov** [comment]
I'll do the change
