### ISSUE TITLE
testing for invalid register custom element names

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#25]
This test co19/LayoutTests/fast/dom/custom/element-names_t01  for Dartium roll 45  needs to change from:    

var invalidNames = [
    // Hyphen missing:
    'foo',
    'xfoo',
    // Reserved names:
    // hyphen-containing names from the applicable specifications,
    // namely the SVG and the MathML.
    'annotation-xml',
    'font-face',
    'font-face-src',
    'font-face-uri',
    'font-face-format',
    'font-face-name',
    'missing-glyph'
    ];

to:

var invalidNames = [
        // Hyphen missing:
        'foo',
        'xfoo',
        // Reserved names:
        // hyphen-containing names from the applicable specifications,
        // namely the SVG and the MathML.
        'annotation-xml',
        // names containing colon
        ':-xfoo',
        'xfoo-:yfoo'
    ];

**Comment by sgrekhov** [comment]
@terrylucas why do you believe that 'font-face',... etc should be removed? Custom Elements specification clearly states (https://www.w3.org/TR/custom-elements/#concepts) that these names are illegal

> The custom element type identifies a custom element interface and is a sequence of characters that must match the NCName production, must contain a U+002D HYPHEN-MINUS character, and must not contain any uppercase ASCII letters.The custom element type must not be one of the following values:
> 
>     annotation-xml
>     color-profile
>     font-face
>     font-face-src
>     font-face-uri
>     font-face-format
>     font-face-name
>     missing-glyph

This test just test this statement. If Dartium fails this means that is is a bug in Dartium, not in tests. I added checking for colon, as it was requested, but didn't remove 'font-face' etc. I even added color-profile and uppercase ASCII letters check. Please see baea490f87c0b77bcbefe309445b90ad67802cdd
