### ISSUE TITLE
LanguageFeatures/Extension-types/exhaustiveness_map_A02_t02 needs updating for CL 345822

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#2502]
[CL 345822](https://dart-review.googlesource.com/c/sdk/+/345822) (which addresses https://github.com/dart-lang/language/issues/3534) modifies flow analysis so that recognizes when a single pattern is guaranteed to match because its erased type is either the same as, or a supertype of, the erased type of the matched value. This partially addresses a situation where a switch statement is recognized by the exhaustiveness checker as exhaustive, but not by flow analysis.

Such a situation occurs in LanguageFeatures/Extension-types/exhaustiveness_map_A02_t02:

```dart
extension type ET1<K, V>(Map<K, V> _) {}

String test(ET1<bool, bool> m) {
//     ^^^^
// [analyzer] unspecified
// [cfe] unspecified
  switch (m) {
    ...
    case Map():
      return "other";
  }
}
```

Currently the above code expects an error, because flow analysis cannot tell that the pattern `Map()` is guaranteed to match the extension type `ET1<bool, bool>`. After the CL lands, flow analysis will recognize that the `Map()` pattern is guarnateed to match, so there will be no error.

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/2503
