### ISSUE TITLE
[augmentation-libraries] Cover success case for aliased augmenting declarations

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#2574]
PR https://github.com/dart-lang/co19/pull/2568 contains a test LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t02.dart checking that we get the expected compile-time errors in the case where a type alias of a type declaration of a mismatched kind is augmented.

Do we have a test which is testing the same situation, except that the type aliases denote types of the same kind? (That is, the case where we should not get an error because there is no kind mismatch, but there might still be an error because a tool mistakenly treats the type alias as a new and different kind and fails to see that the type alias denotes a declaration of the right kind).

**Comment by scheglov** [comment]
Where the fact that type aliases can be used is described in the specification?

**Comment by sgrekhov** [comment]
Interesting. @eernstg specification contains the following syntax
```
typeAlias ::= 'augment'? 'typedef' typeIdentifier typeParameters? '=' type ';'
  | 'augment'? 'typedef' functionTypeAlias
```
What exactly can be augmented here? Could you show any useful example? We cannot change `typeParemeters` section, cannot change `type`, cannot change anything in `functionTypeAlias`

**Comment by sgrekhov** [comment]
> Interesting. @eernstg specification contains the following syntax
> 
> ```
> typeAlias ::= 'augment'? 'typedef' typeIdentifier typeParameters? '=' type ';'
>   | 'augment'? 'typedef' functionTypeAlias
> ```
> 
> What exactly can be augmented here? Could you show any useful example? We cannot change `typeParemeters` section, cannot change `type`, cannot change anything in `functionTypeAlias`

Ah, it's for adding metadata and DocComments. Ok

**Comment by eernstg** [comment]
It is not unthinkable that a type alias augmentation could do something which is similar to variable declarations:

```dart
typedef F<X> = List<X>;
augment typedef F<X> = Map<augmented<X>, augmented<X>>; // means `Map<List<X>, List<X>>`.
```

I wouldn't recommend it, though. :smile:

So let's stick to the DartDoc comments and metadata.
