### ISSUE TITLE
Change LayoutTests/fast/dom/shadow/event-path_t01 test for roll 45

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#26]
Change LayoutTests/fast/dom/shadow/event-path_t01:

    var expected = ['#b', '#a', BodyElement, HtmlHtmlElement, HtmlDocument];
to:
    var expected = ['#b', '#a', BodyElement, HtmlHtmlElement, HtmlDocument, Window];

**Comment by sgrekhov** [comment]
Fixed. See 860efd51dcef7370f2c12127ae258b3648b8c589
