### ISSUE TITLE
Errors in constant update tests

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/co19#261]
`ShortCircuitOperators_A02_t02`: The `const` constructor is not called, and therefore its initializers are not evaluated, so the expression in the initializer only needs to be potentially constant, which it is. To produce an error because it is not constant, add a `const` call to the constructor in `main`.

`ShortCircuitOperators_A04_t02`: Only the `true` branch is evaluated, which is constant (and the `false` branch is potentially constant), so the whole expression is a valid constant expression. Also, the constructor is not called.

`ShortCircuitOperators_A04_t03`: Only the `true` branch is evaluated, which is constant (and the `false` branch is potentially constant), so the whole expression is a valid constant expression.

`ShortCircuitOperators_A04_t06`: Only the `false` branch is evaluated, which is constant (and the `true` branch is potentially constant), so the whole expression is a valid constant expression. Also, the constructor is not called.

`ShortCircuitOperators_A04_t07`: Only the `false` branch is evaluated, which is constant (and the `true` branch is potentially constant), so the whole expression is a valid constant expression.

`CastOperator_A04_t03`: The initializer is a valid constant expression, since `o` is a parameter to the constructor and `A` is a compile-time constant type. Also, the constructor is not called.

`ShortCircuitOperators_A02_t05`: The constructor is not called, so the test doesn't test what it is supposed to.

`ShortCircuitOperators_A01_t03`: The constructor is not called, so the test doesn't test what it is supposed to. It gives a compile-time error because the name of the constructor is wrong.

**Comment by iarkh** [comment]
Hello,
It seems like some problems described here contradicts Dart Language Specification according to the issue #https://github.com/dart-lang/language/issues/189 filed by me some time ago.

For example, ShortCircuitOperators_A04_t02:
``` dart
class MyClass {
  final bool res;
  const MyClass() : res = (true ? true : (null as String).length);
}

main() {}
```
`(true ? true : (null as String).length)` is not a valid expression here because `(null as String).length` is of the type `int` and it's assigned to the `bool` variable. So, compile error should be thrown here.

Please see issue #189 for more details.

What do you think?

**Comment by iarkh** [comment]
One more test which looks correct for me: CastOperator_A04_t03:
``` dart
class A {
  A();
}

class MyClass {
  final A a;
  const MyClass(Object o) : a = o as A;
}

main() {
  const inst = MyClass(1);
}
```
Default `A` constructor is not declared as `const`, so A is not a constant class, so `o as A` is not a correct constant expression, so `const MyClass(Object o) : a = o as A;` should throw compile error even if constructor was not called in the source code.

**Comment by iarkh** [comment]
Finally, I've added constructor call to two tests: `ShortCircuitOperators_A02_t02` and `ShortCircuitOperators_A01_t03`. 

Could you please take a look at my comments above and confirm that other tests should be updated?

**Comment by askeksa-google** [comment]
> `(true ? true : (null as String).length)` is not a valid expression here because `(null as String).length` is of the type `int` and it's assigned to the `bool` variable. So, compile error should be thrown here.

Yes, you are right. Since the expression is not a valid expression (because of the types) it is also not a valid constant expression.

> Default `A` constructor is not declared as `const`, so A is not a constant class, so `o as A` is not a correct constant expression, so `const MyClass(Object o) : a = o as A;` should throw compile error even if constructor was not called in the source code.

For a type cast `o as A` to be a potentially constant expression, there is no requirement that `A` has a `const` constructor. There are perfectly valid values that I can pass to the `MyClass` constructor which will make the evaluation of the initializer expression succeed. Example:
```dart
class B implements A {
  const B();
}

const x = const MyClass(const B());
```
Thus, this test should not give an error.

**Comment by askeksa-google** [comment]
The new test `CastOperator_A04_t04` should also not be a compile-time error, for the same reason as `CastOperator_A04_t03`.

I think maybe the confusion arises around the concept of a "constant type expression" used in the spec to describe the requirement on the type in an `as` expression. This essentially just means that the type is not a type parameter and is not parameterized (transitively) by any type parameters. It has nothing to do with whether the type can be instantiated as a `const` instance.

Also, the new `CastOperator_A04_t04` merely tests that you can't pass a non-constant expression to a `const` constructor. I think it would be useful to have a positive test for the `as` expression. The current `CastOperator_A04_t04` would achieve that, if you just mark it as positive.

And apologies, but it turns out I was a bit too quick is accepting your explanation based on the types.  When the types in the two branches in a conditional expression differ, the resulting type of the expression is merely the least upper bound of the two types. I.e. in the case of `bool` and `int`, or of `String` and `int`, as in the examples, the expression is type correct, and the type of the conditional expression is `Object`, which is assignable to any type.

Thus, I maintain all of the errors in the issue, except for `ShortCircuitOperators_A02_t05`, which is indeed a type error.

**Comment by askeksa-google** [comment]
Related to the requirements on the `as` expression, it could also be useful to have a negative test where the type is a type variable, and one where it is a class parameterized by a type variable.

**Comment by iarkh** [comment]
> Also, the modified CastOperator_A04_t03 merely tests that you can't pass a non-constant expression to a const constructor. I think it would be useful to have a positive test for the as expression. The current CastOperator_A04_t04 would achieve that, if you just mark it as positive.

You are right, CastOperator_A04_t04 should not throw a compile error. There is already such positive test - it's CastOperator_A01_t01, so I've just removed CastOperator_A04_t04.

**Comment by iarkh** [comment]
> And apologies, but it turns out I was a bit too quick in accepting your explanation based on the types. When the types in the two branches in a conditional expression differ, the resulting type of the expression is merely the least upper bound of the two types. I.e. in the case of bool and int, or of String and int, as in the examples, the expression is type correct, and the type of the conditional expression is Object, which is assignable to any type.

Just to be clear: 
- According to the comment above, source code like the following **should not** throw a compile error: 
``` dart
class MyClass {
  final bool res;
  MyClass() : res = (true ? true : (null as String).length);
}
```
- And according to the comments in https://github.com/dart-lang/language/issues/189 - the following code **should** throw a compile error: 
`const bool b = false && (null as String).length`

@eernstg , do you agree?

**Comment by eernstg** [comment]
I agree that `(true ? true : (null as String).length)` is not a compile-time error (it's just an expression, and we use least upper bound to find the type as mentioned).

Maybe the intention is to have `const MyClass`? With that, it is also not a error due to the requirements on potentially constant expressions.

It's also not a compile-time error to have `const MyClass()` anywhere, because that does not give rise to any evaluation steps that would cause a dynamic error at run time.

But `(false ? ..)` would attempt to compute the `length` of the null object, which "would cause a dynamic error", so it's a compile-time error to have that as a constant expression.

`bool b` has a compile-time error because `int` is not assignable to `bool`, and that's required for both operands in an expression of the form `e1 && e2`. It does not matter whether `b` is constant.

**Comment by askeksa-google** [comment]
The fixes look good, thanks.

However, the changes made to `ShortCircuitOperators_A04_t09` and `ShortCircuitOperators_A04_t11` in the same commit have a small error: The instantiation of `MyClass` is done with `new` but in a `const` context, so that is a compile-time error. To fix it, just replace `new MyClass` by `const MyClass` in those two tests.
