### ISSUE TITLE
Testing null aware elements

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#2694]
The [null aware elements](https://github.com/dart-lang/language/blob/main/working/0323-null-aware-elements/feature-specification.md) feature is being implemented, so we need some tests on that topic.

**Comment by eernstg** [comment]
Thanks!

**Comment by sgrekhov** [comment]
Closing as completed. Expressions checklist below

Expression | Test
-- | --
?a.b = e | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?a?.b = e | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?a[e1] = e2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?a?[e1] = e2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?super.b = e | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?super[e1] = e2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A02_t01.dart
?this | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_this_super_A02_t01.dart
?super.b | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_this_super_A01_t01.dart
?super[e1] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_this_super_A01_t01.dart
?super(42) | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_this_super_A01_t01.dart
?(e) | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_parenthesized_A01_t01.dart
?null | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/constants_A01_t01.dart
?1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?0x1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?true | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?false | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?'Hello' | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?r'Hello' | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t02.dart
?{1} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?< int >{1} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?{1: 2} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?< int, int >{1: 2} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?[1] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?< int >[1] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t03.dart
?const {1} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?const < int >{1} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?const {1: 2} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?const < int, int >{1: 2} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?const [1] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?const <int>[1] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t05.dart
?(1, name: 2) | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_records_A01_t01.dart
?const (1, name: 2) | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_records_A01_t01.dart
?MyClass.new | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_functions_A01_t01.dart
?switch (1) { _ => 2 } | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_switch_A01_t01.dart
?throw 0 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_throw_A01_t01.dart
?() => 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_functions_A01_t01.dart
?() async => 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_functions_A01_t01.dart
?() {} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_functions_A01_t01.dart
?() async {} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_functions_A01_t01.dart
?new MyClass() | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_new_const_A01_t01.dart
?const MyClass() | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_new_const_A01_t01.dart
?a..toString() | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_cascade_A01_t01.dart
?a?..toString() | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_cascade_A01_t01.dart
?true ? 1 : 2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_A05_t01.dart
?1 ?? 2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_A05_t02.dart
?false \|\| true | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_logical_A01_t01.dart
?true && false | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_logical_A01_t01.dart
?super == 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_equality_A01_t01.dart
?1 is int | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_relational_A02_t01.dart
?1 as int | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_relational_A02_t02.dart
?1 < 2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_relational_A01_t01.dart
?super < 2 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_relational_A01_t02.dart
?1 \| 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_bitwise_A01_t01.dart
?super \| 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_bitwise_A01_t02.dart
?1 ^ 1 | syntax_bitwise_A01_t01.dart
?super ^ 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_bitwise_A01_t02.dart
?1 & 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_bitwise_A01_t01.dart
?super & 1 | syntax_bitwise_A01_t02.dart
?1 << 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_shift_A01_t01.dart
?super << 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_shift_A01_t02.dart
?1 + 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_additive_A01_t01.dart
?super + 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_additive_A01_t02.dart
?1 * 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_multiplicative_A01_t01.dart
?super * 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_multiplicative_A01_t02.dart
?-1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_prefix_A03_t01.dart
?!true | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_prefix_A02_t01.dart
?~1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_prefix_A03_t01.dart
?await 1 | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_prefix_A04_t01.dart
?a++ | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_postfix_A01_t01.dart
?a.b++ | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_postfix_A01_t02.dart
?super.b++ | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_unary_postfix_A01_t02.dart
?(a, b) = (2, 3) | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A03_t01.dart
?[a, b] = [2, 3] | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A03_t02.dart
?{true: a, false: b} = {true: 2, false: 3} | https://github.com/dart-lang/co19/tree/master/LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_assignment_A03_t02.dart
