### ISSUE TITLE
Wildcards Update - Removed no defaults needed for unnamed optional wildcard parameters

### ISSUE THREAD

**Issue by kallentu** [dart-lang/co19#2729]
We revoked allowing unnamed optional wildcard parameters to not have a default value.
So the following is an error:
```dart
int foo([int _]) => 2;
//           ^
```

Not sure if there were tests made for this one spec change, but we reverted this from the spec and I want to make sure that the co19 tests aren't testing for this behaviour. Feel free to close if this is already the case.

Issue of this change: https://github.com/dart-lang/language/issues/3807

cc. @sgrekhov @eernstg

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/2730
