### ISSUE TITLE
Language/Expressions/Object_Identity/double_t02.dart needs expectations updated for different backend platforms

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#2734]
[Language/Expressions/Object_Identity/double_t02.dart](https://github.com/dart-lang/co19/blob/master/Language/Expressions/Object_Identity/double_t02.dart) should be updated to expect different results on platforms that use JavaScript number semantics as described by this [support document](https://dart.dev/guides/language/numbers#identity). With the JavaScript semantics the nan values should not be identical.

**Comment by sgrekhov** [comment]
[Language/Expressions/Object_Identity/constant_objects_t01.dart](https://github.com/dart-lang/co19/blob/master/Language/Expressions/Object_Identity/constant_objects_t01.dart) and [Language/Expressions/Object_Identity/double_t03.dart](https://github.com/dart-lang/co19/blob/master/Language/Expressions/Object_Identity/double_t03.dart). should be fixed as well
