### ISSUE TITLE
LanguageFeatures/Patterns/shared_case_scope_A02_t02 needs to be modified for bugfix to UNREACHABLE_SWITCH_CASE

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#2872]
https://dart-review.googlesource.com/c/sdk/+/384326 fixed issue https://github.com/dart-lang/sdk/issues/56710, which prevented the analyzer from properly reporting an `UNREACHABLE_SWITCH_CASE` warning for a switch case that contains a `when` clause.

The following co19 test needs to be modified to account for the fixed warning:
- LanguageFeatures/Patterns/shared_case_scope_A02_t02

Probably the best thing to do is ignore the warning with an `// ignore` comment.

**Comment by sgrekhov** [comment]
Runtime error is not fixed
