### ISSUE TITLE
Errors in some tests comparing nested iterables

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/co19#297]
A couple of tests are using setEquals/listEquals to compare nested structures. They likely intended to use deepEquals.

* LanguageFeatures/Spread-collections/DynamicSemantics_Set_A02_t05
  * Line 35 also has a typo (',' should be '.')
* LanguageFeatures/Spread-collections/DynamicSemantics_Set_A02_t06
  * A couple of these tests (the first two expectations) have an extraneous pair of curly braces.

**Comment by iarkh** [comment]
DynamicSemantics_Set_A02_t05: already fixed in the revision a8f76152eea718bde96466f5eb9104107b270403 
DynamicSemantics_Set_A02_t06: already fixed in the revision 62ee7b830ede9650b68786ec2ed18cb5e469ca44

**Comment by iarkh** [comment]
`A couple of tests are using setEquals/listEquals to compare nested structures. They likely intended to use deepEquals.`
Could you please clarify what you mean here? Which exact test is incorrect?

**Comment by Markzipan** [comment]
For example, tests comparing {{}, []} won't be equal to another instance of {{}, []}. Nested empty iterables don't compare properly using setEquals/listEquals. Editing those functions would be another solution.
