### ISSUE TITLE
Misc. errors in some spread syntax tests

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/co19#298]
* LanguageFeatures/Spread-collections/Syntax_A01_t02
  * The final expectation should have `"abc", "int", "hello"` instead of `1, 2, 3`

* LanguageFeatures/Spread-collections/Syntax_A02_t02
  * The final expectation should have `"abc", "int", "hello"` instead of `1, 2, 3`

* LanguageFeatures/Spread-collections/Syntax_A01_t06
  * The final expectation probably intends to be something like: 
`  Expect.isEquals([...list2, ...list3], [14, 18, 99, ...?list1, 0, 2, 4, 6, 8]);`

* LanguageFeatures/Spread-collections/Syntax_A02_t09
  * This doesn't import expect.dart (not sure if that's okay in this context)
  * I believe the final two expectations are supposed to pass, as Map<dynamic, dynamic> accepts null keys and values.

**Comment by iarkh** [comment]
Fixed in revisions 055967ee56c70801c7aa99b190640ad727fdb29c, 1f98c68cf1e18650b9fe534613f7ebc0e4117616,
