### ISSUE TITLE
List<dynamic> potentially causing errors for some spread tests

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/co19#299]
A couple of tests seem to want type inference for generics (instead of assuming dynamic). If so, `List` should be replaced by `var` (or otherwise updated). 

* LanguageFeatures/Spread-collections/StaticSemantic_A04_t01
* LanguageFeatures/Spread-collections/StaticSemantic_A04_t02
* LanguageFeatures/Spread-collections/StaticSemantic_A05_t01
  * Tests 4 and 5 (so l6 and l7)
* LanguageFeatures/Spread-collections/StaticSemantic_A06_t01
  * Test 4

**Comment by iarkh** [comment]
I've corrected some issues here.
However, could you please clarify what is wrong with the rest?
For example:
StaticSemantic_A04_t01:
```
 int number = 1;
  String str = "checkme";
  Map map = {1: 1, 2: 2};
  List list = [1, 2, 3, 4, 5];

  List l1 = [...number];  //# 01: compile-time error
  List l2 = [...str];     //# 02: compile-time error
  List l3 = [...map];     //# 03: compile-time error
  List l4 = [...list[0]]; //# 04: compile-time error
```
`number`, `str`, `map` and `list[0]` are objects which does not implement `Iterable`, so compile error should be thrown here.
In practice, only first three throw a compile error, and the fourth one throws "Unimplemented code" runtime error for me (tested with dart 2.2.1-dev.1.0, spread-collections and set-literals experimental options are turned on).

The same is about StaticSemantic_A4_t02 and StaticSemantic_A06_t01.

**Comment by Markzipan** [comment]
List list is the same as declaring List<dynamic> list (no type inference here). This means list[0] is dynamic, and ...[list[0]] becomes a runtime check/error. 

But do let me know if you think I'm mistaken.
