### ISSUE TITLE
Tests expect TypeError, should just be 'a dynamic error'

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#3]
These tests expect TypeError to be thrown:

Language/03_Overview/1_Scoping_A02_t05
Language/03_Overview/1_Scoping_A02_t06

but the spec only mentions that 'a dynamic error occurs'. (§16.12.1 New)

**Comment by sgrekhov** [comment]
Fixed. Excessive exception type check removed. Please see https://github.com/dart-lang/co19/commit/3776223d9209ab3ae6346cff03adb88cfc0417e3
