### ISSUE TITLE
Unclear why error is expected in Control-flow-collections/static_semantics_A02_t02 cases 5, 7, 13, 15

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/co19#310]
```dart
  bool b = true;                                                                 
  List collectionNum = [3, 1.0, 4, 1, 5];                                        
  // ...    
  Map<String, int> map = {if (b) for (var v in collectionNum) if (v > 3) "$v": v,}; //# 05: compile-time error
  // ...
  Map<String, int> map = {if (!b) for (var v in collectionNum) if (v > 3) "$v": v}; //# 07: compile-time error
  // ...
  Map map = <String, int>{if (b) for (var v in collectionNum) if (v > 3) "$v": v,}; //# 13: compile-time error
  // ...
  Map map = <String, int>{if (!b) for (var v in collectionNum) if (v > 3) "$v": v}; //# 15: compile-time error
```

In all of these examples, "$v" : v is a map literal entry of key/value types String, num. String is assignable to String, and num is assignable to int. Therefore `Map<String, num>` (for examples 13 & 15) are also assignable to `Map<String, int>`.

If we remove the if and for elements, we can create a code example valid for dart 2.2:

```dart
void main() {                                                                    
  num v = null;                                                                  
  Map<String, int> map0 = {"$v": v};                                             
  Map<String, int> map1 = {"$v": v};                                             
  Map map2 = <String, int>{"$v": v};                                             
  Map map3 = <String, int>{"$v": v};                                             
  print(map0);                                                                   
  print(map1);                                                                   
  print(map2);                                                                   
  print(map3);                                                                   
}              
```

This is valid dart 2.2

```
$ dartanalyzer lib/test.dart
Analyzing lib/test.dart...
No issues found!

$ dart --checked lib/test.dart
lib/test.dart:1: Warning: Interpreting this as package URI, 'package:test/test.dart'.
{null: null}
{null: null}
{null: null}
{null: null}
```

So it's not clear to me what error is expected or why. I have a very strong suspicion that this is not an error (I certainly don't see any).

**Comment by MichaelRFairhurst** [comment]
This will also affect static_semantics_A01_t02.dart cases 3, 4, 7, 8

```dart
void main() {                                                                    
  num v = null;                                                                  
  List<int> list0 = [v];                                                         
  List<int> list1 = [v];                                                         
  List list2 = <int>[v];                                                         
  List list3 = <int>[v];                                                         
  print(list0);                                                                  
  print(list1);                                                                  
  print(list2);                                                                  
  print(list3);                                                                  
}
```

```
$ dartanalyzer lib/test.dart
Analyzing lib/test.dart...
No issues found!

$ dart --checked lib/test.dart
lib/test.dart:1: Warning: Interpreting this as package URI, 'package:test/test.dart'.
[null]
[null]
[null]
[null]
```

I can see why there may be some confusion, note that these fail if you change the type of v from num to double.

That's because doubles are not a subtype of ints and ints are not a subtype of doubles. That means they are not assignable to each other.

On the other hand, num and int are assignable to each other because int is a subtype of dart (and assignability is either T <: S or S <: T).

I see I should have seen this when I filed #306

**Comment by sgrekhov** [comment]
@MichaelRFairhurst thank you for filling this. There were even more issues in this test. I hope I've fixed them all. It's amazing how hard to write correct tests when you have no compiler to check the code.

**Comment by stereotype441** [comment]
@sgrekhov did you see @MichaelRFairhurst's comment above indicating that this bug also applies to `static_semantics_A01_t02.dart` cases 3, 4, 7, and 8?  It looks like they haven't been updated.

**Comment by sgrekhov** [comment]
@stereotype441 I don't see any problems in `static_semantics_A01_t02.dart` now. Mentioned issue was fixed by 817e960f62731510e26bf634e0a927c7656156f3. Now it should be Ok. So I'm closing this item. If you see any additional issues, please reopen

**Comment by stereotype441** [comment]
@sgrekhov I just took a deeper look at `static_semantics_A01_t02.dart` and I believe there is an issue. 
 The `@description` field of the test says `Checks that element type of the list literals is the static type of the type argument used to create the list`.

But it's not necessary for the static type of list literal elements to be *the same* as the type argument used to create the list.  The actual rule is:
- List literal elements that are themselves literals need to have a static type that is *a subtype of* the element type of the list literal.
- List literal elements that are not themselves literals need to have a static type that is *assignable to* the element type of the list literal.

So in cases 3, 4, 7, and 8:
```dart
List<int> list = [if (b) for (var v in collection) if (v > 3) v,]; //# 03
List<int> list = [if (!b) for (var v in collection) if (v > 3) v]; //# 04
List list = <int>[if (b) for (var v in collection) if (v > 3) v,]; //# 07
List list = <int>[if (!b) for (var v in collection) if (v > 3) v]; //# 08
```
The second rule applies (since `v` is not a literal), so what is required is that the static type of `v` (`num`) is assignable to the element type of the list literal (`int`).  `num` *is* assignable to `int`, because `int` is a subtype of `num`, so this is ok.

**Comment by MichaelRFairhurst** [comment]
I think the confusion here is that issue #306 has been fixed for static_semantics_A01_t02.dart, however, issue #310 has not been.

Paul's explanation of how this issue affects static_semantics_A01_t02.dart is spot on and hopefully the makes the issue confusion (#306/#310) a non-issue!

**Comment by sgrekhov** [comment]
@stereotype441 , @MichaelRFairhurst thank you. I missed this issue, sorry. Now I changed collection type to `var collection = <double>[3, 1.0, 4, 1, 5];` So now it is `List<double>` and not assignable to `int`
