### ISSUE TITLE
Change co19/WebPlatformTest/shadow-dom/elements-and-dom-objects/extensions-to-event-interface/event-path-001_t01 for roll 45

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#32]
Change test co19/WebPlatformTest/shadow-dom/elements-and-dom-objects/extensions-to-event-interface/event-path-001_t01 

change:
    assert_equals(e.path.length, 6, 'path.length');
    assert_equals(e.path[0], child, 'path[0] should be child');
    assert_equals(e.path[1], shadowRoot, 'path[1] should be shadowRoot');
    assert_equals(e.path[2], host, 'path[2] should be host');
    assert_equals(e.path[3], doc.body, 'path[3] should be body');
    assert_equals(e.path[4], doc.documentElement, 'path[4] should be html');
    assert_equals(e.path[5], doc, 'path[5] should be document');
to:
    assert_equals(e.path.length, 7, 'path.length');
    assert_equals(e.path[0], child, 'path[0] should be child');
    assert_equals(e.path[1], shadowRoot, 'path[1] should be shadowRoot');
    assert_equals(e.path[2], host, 'path[2] should be host');
    assert_equals(e.path[3], doc.body, 'path[3] should be body');
    assert_equals(e.path[4], doc.documentElement, 'path[4] should be html');
    assert_equals(e.path[5], doc, 'path[5] should be document');
    assert_equals(e.path[6], doc.window, 'path[6] should be window');

**Comment by sgrekhov** [comment]
Fixed. See 61e4984f0857d944d69ff953dc4218149f2ba9c6
