### ISSUE TITLE
Change test co19/WebPlatformTest/shadow-dom/elements-and-dom-objects/shadowroot-object/shadowroot-methods/test-002_t01 for roll 45

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#33]
Change test co19/WebPlatformTest/shadow-dom/elements-and-dom-objects/shadowroot-object/shadowroot-methods/test-002_t01

Change an occurrences of:

getElementsByClassName('clazz')

to:

querySelectorAll('.clazz')

**Comment by sgrekhov** [comment]
This tests tested getElementByClassName() method of ShadowRoot interface. There are no this method in a ShadowRoot interface any longer. So the test was simply removed. 1bf53456984440f41d4cb468ff63e2fd7279c2fb
