### ISSUE TITLE
Add constant-update-2018 to all spread/unified/control-flow collections tests

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#332]
Please add the constant-update-2018 experiment flag to all tests for spread/unified/control-flow:
// SharedOptions=--enable-experiment=spread-collections,constant-update-2018

**Comment by athomas** [comment]
Background: we want to ensure that these features work well together and some of the tests require the constant update to be enabled to work correctly.

**Comment by sgrekhov** [comment]
Fixed
