### ISSUE TITLE
Add constant-update-2018 flag to collections tests

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/co19#337]
All tests in `LanguageFeatures/Control-flow-collections` and `LanguageFeatures/Spread-collections` that contain `const` collections need to enable the `constant-update-2018` experiment to function properly.

This can be done similarly to https://dart-review.googlesource.com/c/sdk/+/97939

**Comment by sgrekhov** [comment]
Duplicate of #332. Already fixed. Closed

**Comment by askeksa-google** [comment]
Ah, somehow overlooked that issue when I looked for it. Thanks!
