### ISSUE TITLE
co19/LayoutTests/fast/innerHTML/javascript-url_t01 need to change for roll 45

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#34]
**Change line:**
  r.setInnerHtml(r.innerHtml.replaceAll('&37;3C!--D--&37;3E', '123'),
to
  r.setInnerHtml(r.innerHtml.replaceAll('&amp;37;3C!--D--&amp;37;3E', '123'),

**Change line:**
  Expect.isTrue(r.innerHtml.indexOf('''javascript:test('text&',&quot;test2&&quot;)''') > -1, 'test 4');
to:
  Expect.isTrue(r.innerHtml.indexOf('''javascript:test('text&amp;',&quot;test2&amp;&quot;)''') > -1, 'test 4');

**Comment by sgrekhov** [comment]
Fixed. See 0fa6bd933f479e6eee7b9a2a0c8a0ef53157009c. Please note that test fails in FF/dart2js on Piont 2. Actual string there is '...&quot;text<&quot;...'. I think this is a bug in FF/dart2js. Dart API specification, at this moment, contains no information about how setAttribute() should escape quotes. W3C setAttribute() spec (https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-F68F082) reads
>  ...any markup (such as syntax to be recognized as an entity reference) is treated as literal text, and needs to be appropriately escaped by the implementation...

I believe implementation should recognize, that in this text, at Point 2, double quotes should not be escaped
