### ISSUE TITLE
Delete test co19/LayoutTests/fast/encoding/css-charset-dom_t01

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#35]
CSSCharsetRule encoding has been removed from Chrome see

[https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/lwq9fhV5uF8/ikrrc76SvG4J]

**Comment by sgrekhov** [comment]
Test deleted. c8faebc7f46956b21772b422233a964ec0cdda84
