### ISSUE TITLE
co19/LayoutTests/fast/dom/fragment-activation-focuses-target_t01 needs to change for 45 roll

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#36]
**Change line:**
```
    link2.click();
    shouldBe(document.activeElement, link2);
```
**to:**
```
    link2.click();
    shouldBe(document.activeElement, document.body);
```

**Comment by sgrekhov** [comment]
Fixed. See b73c6a36cbb8722c38373632184f79fb5f3ea13a

Note that I didn't find specification that specifies how focus should be moved. Now this test works in Dartium but fails in FF with dart2js compiler. In FF in both cases focus is not moved and stayed on the links. I'm not sure which behavior is right but close this issue. If the test is wrong investigation of FF test failures will discover it
