### ISSUE TITLE
LibTest/io/CompressionOptions/DEFAULT_A01_t01 clientMaxWindowBits and serverMaxWindowBits can be null

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#364]
Hi,

I looked at <https://github.com/dart-lang/sdk/issues/29436> (Wrong CompressionOptions.DEFAULT options) and it seems to me that the current implementation behavior is desirable, that `clientMaxWindowBits` and `serverMaxWindowBits` is null by default to request the default window size of 15.  I've made a changelist to update the documentation at <https://dart-review.googlesource.com/c/sdk/+/103813>.

The co19 test `LibTest/io/CompressionOptions/DEFAULT_A01_t01` should be updated to expect the default `clientMaxWindowBits` and `serverMaxWindowBits` to be null.

Jonas

**Comment by sgrekhov** [comment]
I'll fix this as soon as changelist, mentioned above, will be merged

**Comment by sortie** [comment]
Okay. I've sent the change <https://dart-review.googlesource.com/c/sdk/+/103813> to the commit queue and it'll land shortly. Please update the test when it's landed.
