### ISSUE TITLE
'MyStreamConsumer<dynamic>' is not a subtype of type 'StreamConsumer<List<int>>'

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#369]
A number of tests are failing with the error:

```
type 'MyStreamConsumer<dynamic>' is not a subtype of type 'StreamConsumer<List<int>>'
```

This relates to this class:

```dart
class MyStreamConsumer<List> extends StreamConsumer<List> {
```

Oftentimes it's used as e.g.:

```dart
  StreamConsumer consumer = new MyStreamConsumer();
  IOSink sink = new IOSink(consumer);
```

However that loses the generic information and the class is considered StreamConsumer<dynamic> instead of StreamConsumer<List<dynamic>> or StreamConsumer<List<int>> as it probably should be.

This seems to be a regression as of the transition to Dart 2.

The following tests are affected:

* LibTest/io/IOSink/IOSink_class_A01_t01
* LibTest/io/IOSink/IOSink_class_A02_t01
* LibTest/io/IOSink/addError_A01_t01
* LibTest/io/IOSink/addError_A01_t02
* LibTest/io/IOSink/addError_A01_t03
* LibTest/io/IOSink/addError_A01_t04
* LibTest/io/IOSink/addError_A02_t01
* LibTest/io/IOSink/addError_A02_t02
* LibTest/io/IOSink/addError_A03_t01
* LibTest/io/IOSink/addStream_A01_t01
* LibTest/io/IOSink/addStream_A02_t01
* LibTest/io/IOSink/addStream_A02_t02
* LibTest/io/IOSink/add_A01_t01
* LibTest/io/IOSink/add_A01_t02
* LibTest/io/IOSink/add_A02_t01
* LibTest/io/IOSink/add_A03_t01
* LibTest/io/IOSink/add_A03_t02
* LibTest/io/IOSink/add_A04_t01
* LibTest/io/IOSink/writeln_A01_t02

**Comment by eernstg** [comment]
> regression as of the transition to Dart 2.

Right, class `IOSink` had `implements StreamSink<List<int>>` already in 2013 (e.g., commit 5540c28c5b44535521d8edb9a14f612f3f1c5b31), but `consumer` with dynamic type `MyStreamConsumer<dynamic>` used to be a subtype of `StreamSink<List<int>>`, and that's not true in Dart 2.

I'd recommend that these tests are revised to eliminate these errors. For instance, it's confusing that `MyStreamConsumer` has a type parameter named `List`, and it might be better to simply have

```dart
class MyStreamConsumer extends StreamConsumer<List<int>> { ... }
...

main() {
  var consumer = new MyStreamConsumer();
  IOSink sink = new IOSink(consumer);
  ...
}
```
