### ISSUE TITLE
LibTest/io/InternetAddress/reverse_A01_t01.dart assumes reverse lookup of localhost is hostname

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#376]
The test `LibTest/io/InternetAddress/reverse_A01_t01.dart` attempts to reverse look up localhost assumes it's going to get the machine's local name. However on my Linux desktop and our cloud machines, it instead resolves to `localhost`. This is probably due to how `/etc/hosts` is configured on a particular machine. The test should be changed to allow `host.host` to be either `"localhost"` or `Platform.localHostname`. Potentially it's also valid to configure it to a fully qualified hostname, in which case the test should probably just check that it gets a valid string.

**Comment by iarkh** [comment]
Fixed in revision dfd67e92105ed47664f0f9f8ca11138d571847b0
