### ISSUE TITLE
Wrong expectation in Language/Classes/Setters/syntax_t04

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#38]
In the setter section, the spec states:
"It is a static warning if a setter declares a return type other than void."
This indicates that no value is returned from a setter.

Also, in the assignment section, the spec states:
"The value of the assignment expression is o2 irrespective of whether setter
lookup has failed or succeeded."

**Comment by sgrekhov** [comment]
I believe the test is correct. According setter syntax in is allowed to specify setter return type. It makes no sense to specify return type other than void but it is allowed. There will be static warning in this case but no error. The test  simply tests this

**Comment by crelier** [comment]
I agree that the syntax is allowed and only gives a static warning.
My point is that the result returned by the setter is ignored. The value of the expression invoking the setter is the same as the value being assigned, i.e. 0 in this test.

The problem is the wrong expectation in these lines:
  Expect.equals(1, c.s1 = 0, "Setter should return expected value");
  Expect.equals(2, C.s2 = 0, "Static setter should return expected value");

They should be
  Expect.equals(0, c.s1 = 0, "Setter should return expected value");
  Expect.equals(0, C.s2 = 0, "Static setter should return expected value");

**Comment by sgrekhov** [comment]
Now I see. This was fixed in 15821d765455082ceccca254356a377c1afabe2e. Closed
