### ISSUE TITLE
Wrong import statement in Language/Libraries_and_Scripts/Imports/namespace_changes_t10

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#39]
The self import statement should be:
import "namespace_changes_t10.dart";

**Comment by sgrekhov** [comment]
@crelier there is this statement in the test. What's wrong?

**Comment by crelier** [comment]
Sorry, I should also have written what I am seeing:
import "1_Imports_A02_t10.dart";

I suspect you may have already fixed it, since you are asking.

Our current version is this one:
commit 3ed795ea02e022ef19c77cf1b6095b7c8f5584d0
Author: Sergey G. Grekhov <sgrekhov@unipro.ru>
Date:   Tue Sep 29 11:48:38 2015 +0600

**Comment by sgrekhov** [comment]
Ok. No this issue in the current version of co19 tests. Closed
