### ISSUE TITLE
Cookie constructor now has mandatory parameters and name/value setters validate

### ISSUE THREAD

**Issue by sortie** [dart-lang/co19#393]
Hi,

I'm about to land a breaking change to the Dart SDK that makes the optional parameters to the Cookie constructor now be mandatory, and the name/value setters now validate.

Bug: <https://github.com/dart-lang/sdk/issues/37192> 
CL: <https://dart-review.googlesource.com/c/sdk/+/103840/1>

The following co19 tests needs to be updated:

* `LibTest/io/Cookie/Cookie_A01_t01.dart`
* `LibTest/io/Cookie/Cookie_A01_t02.dart`

It is now a compile time error to not pass both parameters, so these tests should probably be deleted.

Additionally this change makes the `name` and `value` setters check whether the strings are valid according to RFC 6265. You could test that if you'd like.

I'll update this issue once the changelist lands.

Jonas

**Comment by sortie** [comment]
`LibTest/io/Cookie/value_A01_t01` is also wrong because it assigns to `value` with a string that's not RFC 6265 compliant (contains a space).

**Comment by sortie** [comment]
This change landed as https://github.com/dart-lang/sdk/commit/44415c49e43e528d680459c64f92694df4c0427a.

**Comment by sgrekhov** [comment]
I added name value check, name was checked in `LibTest/io/Cookie/Cookie_A01_t05.dart`

**Comment by sortie** [comment]
Thanks Sergey
