### ISSUE TITLE
Move triple-shift tests to LanguageFeatures/Triple-shift

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#394]
The NewOperators_A01_* tests depend on triple-shift which is no longer part of the constant-update-2018 feature, please move them LanguageFeatures/Triple-shift

**Comment by iarkh** [comment]
Files are moved.

Please note that these are the tests for constants only, i.e whole Triple-shift Spec is not covered by them. 
Please let me know if I need to cover this completely.
