### ISSUE TITLE
Static extension methods: add tests for The call Member

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#400]
Documentation [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#the-call-member)

**Comment by lrhn** [comment]
The "aliasing" is not a feature of static extension methods. It's listed only as a *potential* extension, one which has not been chosen (and proably won't).

**Comment by sgrekhov** [comment]
@lrhn , thank you! Changed to The call member
