### ISSUE TITLE
Wrong expectation in Language/Expressions/Property_Extraction/Named_Constructor_Extraction/not_class_t01

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#41]
The test Language/Expressions/Property_Extraction/Named_Constructor_Extraction/not_class_t01 expects a runtime error, because E is not a class in new E#m.

E, being an enum, is actually a class.
We could then argue that a noSuchMethod be thrown. However, the section on enum states that it is a compile-time error to instantiate an enum. So if we write new E#, it is not a noSuchMethod method anymore. However, it is to late to report the compile-time error when the closurize constructor is invoked.

The spec will be changed to state that a compile-time error is expected in the case of new E#m.

**Comment by sgrekhov** [comment]
Will fix this when spec will be updated

**Comment by sgrekhov** [comment]
This part was removed from the spec, tests was deleted. Closed.
