### ISSUE TITLE
Outdated URI in import or part statements

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#42]
The URI in import or part statements need to be updated in these tests:
Language/Libraries_and_Scripts/URIs/syntax_t04
Language/Libraries_and_Scripts/URIs/syntax_t05
Language/Libraries_and_Scripts/URIs/syntax_t09
Language/Libraries_and_Scripts/URIs/syntax_t10
Language/Libraries_and_Scripts/URIs/syntax_t14
Language/Libraries_and_Scripts/URIs/syntax_t15

**Comment by sgrekhov** [comment]
@crelier I don't see any outdated URI in these tests (at least in the latest version of co19 tests). Please clarify what's wrong with these tests

**Comment by crelier** [comment]
This must be the same problem as for #39 and #40. Our version is behind and needs updating.
One example, in Language/Libraries_and_Scripts/URIs/syntax_t04, I see:
import "5_Library1" ".dart";

**Comment by sgrekhov** [comment]
Ok. No this issue in the current version of co19 tests
