### ISSUE TITLE
extension_member_resolution_t04 doesn't actually test type inference

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#428]
At https://github.com/dart-lang/co19/blob/c33859f6ad09a273ea27c7788f25fc6fd520d3b1/LanguageFeatures/Extension-methods/extension_member_resolution_t04.dart#L10

the goal for this test as announced as testing that 'standard type inference is used', but that's not easy to test. ;-)

The test _actually_ tests that the invocation in line 31 resolves to `ExtC<...>`, and that's based on the i2b tie-breaker rule (because both matched types are `List<C>`), so in that sense it's basically a test of extension conflict resolution.

If `method` is changed to `Type method() => T;` it could be used to test something which is determined via type inference.

A similar consideration would be relevant for '.._t05'.

**Comment by sgrekhov** [comment]
@eernstg , please review 2ab6a8a. Does it test type inference now?

**Comment by eernstg** [comment]
Looks good! By the way, the test would be stronger as follows:

```dart
...
// Line 25.
List<C> list1 = [];
...
// Line 28.
List<A> list2 = [];
...
```

because we have then chosen the static type for `list1` and for `list2` explicitly. This is better documentation, and we avoid having to factor in "by the way, what type did type inference give this variable?", which would just be noise anyway because that's not the type inference step that we wish to test here.

We would then more directly test that the inference applied to the extension method invocations 
`list1.method()` and `list2.method()` choose exactly the type argument that we expect.

**Comment by sgrekhov** [comment]
Thank you
