### ISSUE TITLE
Tests expect compile-time error without trying to execute erroneous code.

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#43]
These tests expect a compile-time error without actually trying to execute the erroneous code:
Language/Mixins/Mixin_Application/error_t01
Language/Mixins/Mixin_Application/error_t02
Language/Mixins/declaring_constructor_t01
Language/Mixins/not_object_superclass_t01
Language/Mixins/reference_to_super_t01

Their respective main() should allocate the erroneous class.

Note section 7 in the spec explaining that compile-time errors may be delayed until the erroneous code is executed.

**Comment by sgrekhov** [comment]
Fixed. See 8bd21b669760b54d5b58688e3d3cdfd917e5c8b9

Language/Mixins/Mixin_Application/error_t01 - code added
Language/Mixins/Mixin_Application/error_t02 - code added
Language/Mixins/declaring_constructor_t01 - no way to explicitly call the code. Constructor should do that
Language/Mixins/not_object_superclass_t01 - this test deleted as obsolete
Language/Mixins/reference_to_super_t01 - this test deleted as obsolete
