### ISSUE TITLE
semantics_of_extension_members_t05 doesn't ensure lexical resolution

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#434]
At https://github.com/dart-lang/co19/blob/c33859f6ad09a273ea27c7788f25fc6fd520d3b1/LanguageFeatures/Extension-methods/semantics_of_extension_members_t05.dart#L25

the invocation of `isEven` must resolve to the declaration `MyUnaryNumber.isEven`, but in the given test this would still be the outcome even if it were implemented such that `!isEven` gets transformed into `!this.isEven` and that is then processed as usual (because there is no other extension which could apply, and no instance method `isEven` on `List<Object>`, and then we just resolve it to `MyUnaryNumber.isEven` from scratch).

In order to actually test that the lexically visible declaration wins the test could be adjusted as follows:

The extension `MyUnaryNumber` is declared in a different library _L_ and imported by `semantics_of_extension_members_t05`, and the library _L_ also contains a private extension `on List<Object>`.

This means that the invocation `list.isEven` in main would resolve to `MyUnaryNumber.isEven` (only that extension is in scope), but if `!isEven` is transformed into `!this.isEven` and processed from scratch then it would be ambiguous (hence an error); so _only_ the approach where it is resolved lexically would avoid the error in the declaration of `isOdd`.

This conflicts with `list.isEven` in line 26 because that would now also be a conflict, so maybe the test should be split in two.

There may also be another way to have a conflict in the extension itself, but no conflict as seen from main, or there could be more methods (`isOdd2` could call `isEven2`, and `isEven2` could have a conflict), etc. Something will work. ;-)

**Comment by sgrekhov** [comment]
> The extension MyUnaryNumber is declared in a different library L and imported by semantics_of_extension_members_t05, and the library L also contains a private extension on List<Object>.
> 
> This means that the invocation list.isEven in main would resolve to MyUnaryNumber.isEven (only that extension is in scope), but if !isEven is transformed into !this.isEven and processed from scratch then it would be ambiguous (hence an error)

@eernstg , thak you for suggestion. But, please, clarify why " if !isEven is transformed into !this.isEven and processed from scratch then it would be ambiguous"? If the second extension in a library L is private, so it is not in the scope?

```dart
library my_unary_number;

extension MyUnaryNumber on List<Object> {
  bool get isEven => length.isEven;
  bool get isOdd => !isEven;
  static bool isListEven(List<Object> list) => list.isEven;
}

extension on List<Object> {
  bool get isEven => true;
}
```
If we import this and if `!isEven` is transformed to `!this.isEven`, then `MyUnaryNumber` is anyway the only applicable extension and `List` itself has no `isEven`. Why there should be a conflict?

**Comment by eernstg** [comment]
The idea is that we should exactly one of the two extensions should be in scope for `main`, so they will be defined in some library _L_, one of them will have a public name, and the other one will have a private name. So we can use the public one from `main`. But inside the public one (inside _L_), both extensions are available, so if we just use a regular extension method invocation (such as we do in `this.isEven`) there will be a conflict: Both the private and the public one are in scope and applicable.

But the intended static analysis and semantics is that the declaration in the lexical scope "wins" when we use a plain `isEven` inside an extension.

So _if_ an implementation just goes ahead and desugars `!isEven` to `!this.isEven` inside the public extension then we will get an ambiguity error which is incorrect. This applies only to the invocation in the body of `isOdd` and not to the ones in `main`, because any invocations from `main` do not have the extension method in its lexical scope.

**Comment by sgrekhov** [comment]
@eernstg thank you. I left this test unchanged (because of `isListEven`) and added new test wilth two extensions (public and private one) in the library
