### ISSUE TITLE
syntax_name_t03 expects access to extension which is not in scope

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#439]
At https://github.com/dart-lang/co19/blob/c33859f6ad09a273ea27c7788f25fc6fd520d3b1/LanguageFeatures/Extension-methods/syntax_name_t03.dart#L29

the extension `MyFancyList` is not in scope, so `list.doubleLength` is a compile-time error. Note that there is a difference between not being in scope, and being shadowed by / conflicted with another declaration.

**Comment by sgrekhov** [comment]
Compile error is an expected result of this test (see `* @compile-error` on line 20)

**Comment by eernstg** [comment]
Ah, I overlooked that; thanks!
