### ISSUE TITLE
Tests check for mixin restrictions that has been lifted.

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#44]
It is now allowed to refer to super from a mixin or to mixin a class extending a subclass of Object.
These tests should not expect a compile-time error anymore:

Language/Mixins/not_object_superclass_t01
Language/Mixins/reference_to_super_t01

**Comment by sgrekhov** [comment]
These files were removed a long time ago. See ff63456159150ce88c500584c827a05646c64b12
