### ISSUE TITLE
Wrong expectation in checked mode.

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#45]
These tests cannot pass in checked mode, see 16.4.1 Boolean Conversion.

Language/Errors_and_Warnings/static_warning_t01
Language/Errors_and_Warnings/static_warning_t02
Language/Errors_and_Warnings/static_warning_t03
Language/Errors_and_Warnings/static_warning_t04
Language/Errors_and_Warnings/static_warning_t05
Language/Errors_and_Warnings/static_warning_t06

**Comment by sgrekhov** [comment]
Fixed. See eb427d03f632f661bacdea98026de835c10a1b98
