### ISSUE TITLE
Off by one width in LayoutTests/fast/css/content/content-quotes-01_t01

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#46]
Fails in current Chrome with expectation of width 196px vs. 197px. Seems like it might reasonably tolerate the off by one in measurement. Not sure what current JS version of the test does.

**Comment by sgrekhov** [comment]
@alan-knight please, specify version of Chrome on which this issue can be observed. I can't reproduce it on Dartium, Chrome or FF. In all these browsers the test passes for me.

Tested FF 44.0, Chrome 48.0.2564.103 (64-bit), Dartium 45.0.2454.0 (64-bit)
Dart VM version: 1.15.0-dev.4.0 (Wed Feb 24 02:44:28 2016) on "linux_x64"

**Comment by alan-knight** [comment]
Chrome 49.0.2623.75 (64-bit)
on linux_64. I'm running via Chrome Remote Desktop, which might also be a factor in font measurement. But it also fails on the bots.

**Comment by sgrekhov** [comment]
Thank you. Reproduced on Chrome 49. But the test works on Dartium 45 and FF 44. So this is a Chrome issue. What to do next depends on the main goal of this test suite.  If the goal is to test Dart API and dart2js, then ok, let's allow 1px tolerance in the tests, no problem. If the goal is to find all issues in browsers, then don't change the test. @whesse, what's you opinion?

The second, I was able to run this test in Chrome only after switching off all asyc stuff in the test code. Before that I got "Uncaught" error. No problem in FF and Dartium. @alan-knight had you had anything like this?

**Comment by alan-knight** [comment]
Well, realistically if we leave the test as is and suppress it, it will probably never get looked at again, and ends up giving us no information at all. So I'd vote for changing it.

**Comment by sgrekhov** [comment]
Fixed. See e7968d119bd412050a7540f968e068ad568a4971

**Comment by whesse** [comment]
The test LayoutTests/fast/css/content/content-quotes-05_t01 is also marked with this issue number in the status file - if it is the same problem, please fix it the same way.

**Comment by sgrekhov** [comment]
The same issue, the same fix. Fixed. de357f6
