### ISSUE TITLE
Some ReceivePort tests are broken

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/co19#474]
The bots are currently failing on what looks like a few broken tests:

- https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905283770615031600/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0
- https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905283960860701008/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

Failures:
- `type 'Future<dynamic>' is not a subtype of type 'Future<int>'`
- `type '_AsBroadcastStream<dynamic>' is not a subtype of type 'Stream<int>' of 'stream'`
- `type 'Future<dynamic>' is not a subtype of type 'Future<int>'`

Tests:
co19_2/LibTest/isolate/ReceivePort/transform_A01_t01
co19_2/LibTest/isolate/ReceivePort/firstWhere_A01_t01
co19_2/LibTest/isolate/ReceivePort/firstWhere_A02_t01

There are possibly other tests that need to be updated as well.

**Comment by sgrekhov** [comment]
There were other tests that failed. Fixed
