### ISSUE TITLE
LayoutTests/fast/forms/ValidityState-tooLong-textarea_t01 fails

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#48]
shouldBeTrue(textarea.validity.tooLong); 
at line 41 fails in Chrome.

This seems to me like a Chrome bug, but noting it here.

**Comment by whesse** [comment]
Also ValidityState-tooLong-input_t01 is failing.

**Comment by sgrekhov** [comment]
This is not a bug in test. I believe this is a bug in Chrome.
Here we have:
textarea.value.length == 4
textarea.maxLength == 3
textarea.validity.tooLong == false

If value length is longer than maxLength then validity.tooLong should be true. But it's false in since Chrome 49. It's a Chrome issue.
