### ISSUE TITLE
Potential bug in test Language/Generics/parameter_A04_t02.dart

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/co19#481]
My understanding of the spec says that the test [parameter_A04_t02.dart](https://github.com/dart-lang/co19/blob/fb16d63b7b990c36829c812f5501db1c7745e241/Language/Generics/parameter_A04_t02.dart) should fail at run time.  Concretely, I think that the raw type `Test` should expand into `A Function(Null)` instead of `A Function(A)` by the instantiate-to-bound algorithm.

According to the [spec](https://github.com/dart-lang/language/blob/fa179ea95a12867db33a794f506d5390bd9f4111/specification/dartLangSpec.tex), section **14.3.2  The Instantiation to Bound Algorithm**, the computation of the type arguments for `Test` should proceed as follows:

**0.** S1 = A, S2 = X1, U10 = S1 = A, U20 = S2 = X1 *// The preliminary steps of the algorithm.*
**1.** There are no dependency cycles, so phase 1 of the algorithm is skipped.
**2.** The lowest number j such that Xj occurs in Up0 for some p is 1 because X1 occurs in U20.
**3.** V0 = `Test<A, X1>`, and the position of the first argument to `Test` is covariant, and the position of the second argument to `Test` is contravariant (because `typedef Test<X1 extends A, X2 extends X1> = X1 Function(X2);`).  It means that X1 occurs only once in V0, and the occurrence is contravairant, so we need to substitute it with `Null`.
**4.** U11 = A, U21 = Null.  Algorithm terminates.

**Comment by eernstg** [comment]
Agreed.

**Comment by iarkh** [comment]
Hello,

I run recent dart version (2.6.0-dev1.0) and the following code sample:
``` dart
class A {}

typedef Test<X1 extends A, X2 extends X1> = X1 Function(X2);
typedef Expected1 = A Function(A);
typedef Expected2 = A Function(Null);

main() {
  print(Expected1 == Test);
  print(Expected2 == Test);
}
```
produces the following output:
> true
> false

So if `Test` should be expanded to `A Function(Null)`, should I now file a bug against the runtime here?

**Comment by stefantsov** [comment]
Actually, I've filed the issue exactly because I landed an update for how variance is used for typedefs.  At the current bleeding edge of Dart SDK the program from the [comment](https://github.com/dart-lang/co19/issues/481#issuecomment-534393190) above prints the following:

```
false
true
```
