### ISSUE TITLE
Tests expect unary minus operator to bind too tightly

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#486]
This tests expect the unary minus operator to bind closer than the method call which is not true. 

https://github.com/dart-lang/co19/blob/50c5e295e113cc590d29f426d1e2e469e5a6b9ba/LanguageFeatures/Extension-methods/syntax_member_declarations_t01.dart#L44

https://github.com/dart-lang/co19/blob/50c5e295e113cc590d29f426d1e2e469e5a6b9ba/LanguageFeatures/Extension-methods/syntax_name_t04.dart#L31

https://github.com/dart-lang/co19/blob/50c5e295e113cc590d29f426d1e2e469e5a6b9ba/LanguageFeatures/Extension-methods/syntax_t03.dart#L35

**Comment by nshahan** [comment]
@a-siva It sounds like you were wondering about this issue also. It seems that the test has an error in the expectation.

**Comment by a-siva** [comment]
Thanks for filing this, I was about to file one.
