### ISSUE TITLE
ayoutTests/fast/dom/shadow/host-context-pseudo-class-css-text_t01 failing

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#49]
Failing in current Chrome. Not clear to me why.
"Expect.equals(expected: <.foo:host-context(div,body.mytheme,p#myid,.bar::before,span:hover) > div { display: block; }>, actual: <:host-context(*) { display: block; }>) fails.

**Comment by whesse** [comment]
Also co19/LayoutTests/fast/dom/shadow/host-pseudo-class-css-text_t01 is failing on Chrome with dart2js.

**Comment by whesse** [comment]
I'm not sure this issue should be filed on the co19 tracker unless we know it is not a dart2js error, and are sure that it is the test that is wrong.  Unless the test is wrong, it is not a co19 issue.

**Comment by sgrekhov** [comment]
This is not a dart2js issue. Argument of :host() and :host-context() pseudo-class functions is list of comma-separated compound selectors (https://www.w3.org/TR/css-scoping-1/#host-selector). According definition of compound selector (https://www.w3.org/TR/selectors4/#compound) it's not quite clear if pseudo-elements (like ::before) may or may not be part of compound expression. But the fact is that Chrome changed its behavior and now doesn't accept pseudo-elements among :host() and :host-context() arguments. 

I changed the tests to follow the current Chrome behavior (see ecce051da071cfe116df2cab807b3aca8d449da2) but I'd like anyone who is more familiar with css selectors to confirm if pseudo-elements are part or not of the compound selector

**Comment by terrylucas** [comment]
The BNF at the bottom of the the selector spec
https://www.w3.org/TR/selectors4
<https://www.w3.org/TR/selectors4/#compound> show's compound_selector
production having pseudo terms e.g.,

compound_selector
  : type_selector [ id | class | attrib | pseudo ]*
    | [ id | class | attrib | pseudo ]+
  ;
pseudo
  : ':' ':'? [ IDENT | functional_pseudo ]
  ;
functional_pseudo
  : FUNCTION S* value ')'
  ;


.foo:host-context(div, body.mytheme, p#myid, .bar::before, span:hover) >
div {
    display: block;
}

However the above highlighted is a functional_pseudo and the insides is a
value see the grammar https://www.w3.org/TR/CSS21/grammar.html

expr
  : term [ operator? term ]*
  ;
term
  : unary_operator?
    [ NUMBER S* | PERCENTAGE S* | LENGTH S* | EMS S* | EXS S* | ANGLE S* |
      TIME S* | FREQ S* ]
  | STRING S* | IDENT S* | URI S* | hexcolor | function
  ;
function
  : FUNCTION S* expr ')' S*
  ;

So I don't believe that value (expression inside of a FUNCTION) can be a
compound selector.



On Thu, Mar 10, 2016 at 1:17 AM, Sergey G. Grekhov <notifications@github.com

**Comment by terrylucas** [comment]
forgot to paste in operator production:

 expr is term [ operator? term] *

operator
  : '/' S* | ',' S*
  ;

**Comment by sgrekhov** [comment]
Terry, thank you. I missed Grammar section on the bottom of the spec. According it pseudo-elements (like ::before) can be part of the compound selector. According :host() and :host-context() specification (https://www.w3.org/TR/css-scoping-1/#host-selector) their argument is "a selector list comprised of compound selectors.". 

So .bar::before is a legal selector for :host() and :host-context()

That means that I should change the test and revert my previous fix. Test will fail but it's an issue in the latest  Chrome that it doesn't accept compound expression with pseudo elements as an argument of :host() and :host-content().

**Comment by sgrekhov** [comment]
Previous change reverted cbd96960607fe5a0e6629a8eab9e530802d0a8b3
