### ISSUE TITLE
Issues found in NNBD tests

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#491]
Issues found by @eernstg:

- syntax_A01_t04 talks about `Never`, but never uses it
- syntax_A05_t0* uses `required` but apparently only on the first named parameter
- syntax_A07_t01 actually has the opposite issue of many others: The fact that `<type>` does not syntactically allow for two or more question marks can be verified by inspection of the grammar (it's a small proof by induction, involving parts like "`<functionType>` cannot end in '?'", "`<typeName>` cannot end in '?'"). So we're talking about verifying that certain programs that have a syntax error according to the grammar will also incur a compile-time error, and that's generally not something we do. (There are too many ways to write a program with a syntax error). So this particular test has fine coverage already, and there is no need to expand it with additional cases! ;-)
-  syntax_A08_t02 only differs from _t01 by using a different type (int/bool), but this is a syntax topic, so type distinctions like that should not matter. If there is something interesting to test regarding those types then it should be a separate test with a comment explaining what is being tested.
-  static_errors_A03_t01 tests a static check on function calls, but 01/02 are not function calls.
-  static_errors_A04_t05 duplicate of t02?
-  static_errors_A07_t01 declares two parameters named `x` in the same parameter list (03..06), so the name clash masks the testing of the error that should be tested. Similar issue with _t02.._t04.
-  static_errors_A09_t0* `test4()` cannot be a compile-time error, a function of type `Function` can be called with any actual argument list that doesn't itself have an error.
- static_errors_A15_t01 tests the dynamic type of `x` and relies on type promotion to give `x` a type which is not a subtype of `Object`. However, "not a subtype of `Object`" is a predicate which is true for all top types and for `Null` and for a set of types which are subtypes of `Null` (like a type variable `X` whose declaration says `X extends Null`, or a constrained type variable `X & Null` where the bound of `X` could be any top type, and a bunch of other cases: it is any type `T` such that `NULL(T)` and not `BOTTOM(T)`). That set of types isn't equal to the meaning of any particular term derived from `<type>`, that is, this is not a denotable type. So we're not likely to promote `x` to such a type, which means that we can't expect the tools to use `!(x is Object)` for anything at all! However, we'd still have the declaration `var x`, and that declaration will give `x` a top type (presumably `dynamic`), so the test should incur an error, and indicated by the expectation comment. But `!(x is Object)` is simply misleading so we shouldn't have that. Moreover, we shouldn't use promotion to obtain a particular typing of a given variable if that variable might as well have been declared to have that type in the first place, because that makes us depend on two steps (having the right promotion plus having the right behavior for the actual topic of the test), and it's better to rely on just one step (plus enumeration as needed, e.g., by declaring `x` to have type `X` where `X extends Null`; and declaring `x` to have type `Object?`; etc).
- static_errors_A20_t01 uses `static-type warning`. This probably has to be `static type warning`; it's possible but not a given that warnings can be tested at all at this point, but I guess that's not a problem (we just need to approve of a failure to detect the warning, or whatever `test.py` allows us to specify).
- static_errors_A20_t02 contains two occurrences of `a ??= c`, which does not make sense: This would assign the value of `c` to `a` in the case where `a` is null; but the type of `a` is non-nullable, so it isn't null. Also, `c` has a nullable type, so it's an error to assign it to `a`. I guess it should have been `c ??= a`? static_errors_A20_t03 has `a ??= c` where type of `c` is non-nullable, and we do expect a warning here, but that would still work if changed to `c ??= a`, so I suppose that is what we want everywhere. One more thing about static_errors_A20_t02: It is slightly confusing that the comment talks about testing static warnings, but the actual test contain elements that are only detected at run time: `clist` is either non-null or null, and it's used in `...? clist` with both; there should be some dynamic tests for the handling of `...?` somewhere, and the duplication of everything in `main` (one time with non-null, next time with null) belongs in such a dynamic test.
- static_errors_A21_t01 has `var v = null`, which gives `v` the type `dynamic`, so it does not test `Null` as claimed.
- static_errors_A21_t03 claims to `test S* for some S where S is nullable`, but it does not contain any expressions whose type is `S*` for any `S`.
- static_errors_A21_t04 claims to do the same thing, but even though this one does import a legacy library, it doesn't contain any expressions whose type is `S*` for any `S`. In order to get that, there must be something in `legacy_library_lib` which can be used to obtain an object from an expression whose type is determined in `legacy_library_lib`. For instance, if `A f() => null;` is a top-level function in `legacy_library_lib` then `f()` in `static_errors_A21_t04` would be an expression of type `A*`. However, `A` is not a nullable type in `static_errors_A21_t04`, so we still don't have an example of the desired setup. One way to get that is to have `dynamic g() => null;` in `legacy_library_lib`: `dynamic` is a nullable type in opted-in code, and `g()` in `static_errors_A21_t04` would be an expression of type `dynamic*`, so you could use `var x = g();` to obtain a variable with type `dynamic*`. Then you could test whether `x = null;` is accepted. Another possibility is to have `Null g() => null;` in `legacy_library_lib` and go through the same steps; or have `A? g2() => null;` in an opted-in library imported by `legacy_library_lib`, then `var x2 = g2();` in `legacy_library_lib`, then use `var y2 = x2` in `static_error_A21_t04` (which should cause `y2` to have type `A?*`). So it's a bit tricky to get to a nullable type which is wrapped in `*`.
- static_errors_A21_t10 again relies on inference where it could as well have declared the desired type directly: `void x = null;`.
- static_errors_A22_t01 could again just use `void f(Never v) { v = null; }`, avoiding the use of promotion and inference to give various things a type when we can actually just write that type. However, the expectation should be a compile-time error, because this is an error test (`Never` is not nullable).
- static_errors_A22_t05 illustrates that we cannot use 'Check that null cannot be assigned to non-nullable type' as the general rule to test for, because that's simply not true. In particular, we can have a non-nullable type which is a supertype of `Null` (for instance `A*` is such a type), and such types on a variable or parameter will allow us to assign the value null. But `static_errors_A22_t05` doesn't contain any expressions of type `S*` for any `S`, so we don't get the required setup in any case. Again, we would need to use an entity (such as a top-level variable `A x;`) which is declared in `legacy_library_lib` and imported into `static_errors_A22_t05`, and we could then test whether it is allowed to assign `Null` to it. However, the general rule for all the positive `A22` tests should actually be 'Check that an expression whose type is non-nullable can be assigned to a variable of type `Object`', and for the negative tests that same attempt should be a compile-time error. I'm using bold here because this affects a bunch of tests in a rather pervasive manner. ;-)
- static_errors_A22_t07 claims to test the treatment of `S*` where `S` is non-nullable, but the test does not contain any expressions of type `S*`. Same fixes as in earlier tests.
- static_errors_A22_t13 has a type `T` which seems to be undefined. Should be `X`. This is again a case where `S` should enumerate some non-nullable types.
- null_check_operator_A01_t0* needs more syntactic forms, and it needs to be based on the actual grammar (in the language specification).
- null_aware_operator_* checks some cases where there is an explicit `?`, but the code transformation which is expressed using `EXP`, `SHORT`, `PASSTHRU`, and so on needs to be tested also in the cases where there is no visible `?`. For example, if the transformation for `e.f` is implemented incorrectly and always just returns `42` then we would transform `o?.x.y` to `42`, even though it should have been transformed into `let z = o in z == null ? null : z.x.y`.

**Comment by sgrekhov** [comment]
@eernstg, regarding 

> null_check_operator_A01_t0* needs more syntactic forms, and it needs to be based on the actual grammar (in the language specification).

Please clarify, what exactly you are expecting to be added and where in the language spec (I use https://spec.dart.dev/DartLangSpecDraft.pdf) can I find the actual grammar?

**Comment by eernstg** [comment]
Right, the relevant grammar rules are the following:

```ebnf
<selector> ::= '!'
    | <assignableSelector>
    | <argumentPart>
<postfixExpression> ::= ...
    | <constructorInvocation> <selector>*
    | <primary> <selector>*
<assignableExpression> ::= <primary> <assignableSelectorPart>
    | 'super' <unconditionalAssignableSelector>
    | <constructorInvocation> <assignableSelectorPart>
    | <identifier>
<assignableSelectorPart> ::= <selector>* <assignableSelector>
<assignableSelector> ::= <unconditionalAssignableSelector>
    | '?.' <identifier>
    | '?.[' <expression> ']'
<unconditionalAssignableSelector> ::= '[' <expression> ']'
    | '.' <identifier>
```

So how do we find a suitable set of examples of terms, given that these rules will of course derive an infinite number of terms? I think it would make sense to consider a small set of selectors on a "receiver" term `x`:

```
x!.name
x![0]
x!?.name
x!?.[0]
x!<int>(42)
x!('-')
x.name!
x[0]!
x?.name!
x?.[0]!
x<int>(42)!
x('-')!
```

and then the receiver `x` needs to take a few different forms:

```
// primary
this
identifier
42
new C()
(true)

// constructorInvocation
C<String>.name(null)
```

and finally all these forms will also fit as `<assignableExpression>`: Take a form for `x`, e.g., `42`, append the selectors, e.g., `!?.name`, check that it's an assignable expression and otherwise add an assignable selector (`name` is an assignable selector, so we're ok), and add an assignment:

```
42!?.name = 1;

// Here's another one that uses operator `[]=`, which should also be covered:
C<String>.name(null)[0] = 1;
```

This would produce roughly 72 examples of syntax, and I think I managed to use all the relevant grammar rules. The easiest way to turn it into compilable code would probably be to define a few extension methods (including operators) `on Object` (with return type `Object`, such that we can evaluate multiple selectors).

There will be a need to have two copies of several things such that we can choose a variant whose return type is non-nullable (say, `42.name`) and another one which is nullable (`42.nameOrNull`), such that the compiler won't complain about using the next selector on a nullable/non-nullable value when it expected the opposite (so we can use `42.nameOrNull!`). Similarly, there may be a need to have some extension methods returning `Function` such that the next selector can be an `<argumentPart>` (say, `42.methodName('-')`).

In any case, it should be possible to start with the pure syntactic forms, and then adjusting the declarations by changing identifiers until it compiles.
