### ISSUE TITLE
Explicit extension operator invocations tested?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#495]
Cf. https://github.com/dart-lang/sdk/issues/38895, I took a look at the co19 tests on extension methods. I think they don't cover the case where an explicitly resolved extension method invocation calls an operator (example derived from [this one](https://github.com/dart-lang/sdk/issues/38895#issuecomment-542593677)):

```dart
extension X on bool {
  bool operator+(bool other) => this | other;
}

main() {
  print(X(false) + true);
}
```

I searched for strings like `) +` and `) *`, but did not find examples where this feature is used.

**Comment by sgrekhov** [comment]
Test uses operator "-" (unary minus). It defined [here](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-methods/my_fancy_list_lib.dart) and used, for example, [here](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-methods/syntax_name_t04.dart). Is this desired test?

**Comment by eernstg** [comment]
Not quite: The point is that an analysis which is a little bit too fast would say that `X(false) + true` is an error because `X(false)` cannot occur as an expression. But the addition is just an instance method invocation, so even though it is different syntactically it is similar to `X(false).foo()` where `foo` is an extension method declared in the extension `X`.

And I couldn't find any test cases where explicit resolution of an extension operator is used (like `X(false) + true`, as opposed to the implicit ones like `false + true`). The example using unary minus is also implicit: `-list` and `-list.split(1)`; the explicitly resolved version would be `-MyFancyList(list)` and `-MyFancyList(list.split(1))`.
