### ISSUE TITLE
Floating point SIMD tests should not assume support for denormal numbers

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/co19#5]
We have SIMD tests that have denormalized numbers as results. (e.g. co19/LibTest/typed_data/Float32x4/operator_multiplication_A01_t01)

On ARM those operations will return 0 if they are computed using the NEON instructions but on X86 they will return something other than 0.0 when using the SSE instructions.

The tests should be written in such a way that they do not assume support for denormal numbers.

**Comment by johnmccutchan** [comment]
Upstream: https://github.com/dart-lang/sdk/issues/24416

**Comment by sgrekhov** [comment]
I fixed the test to not to use denormalized numbers. Please see https://github.com/dart-lang/co19/commit/3a131fc4340ad0ced4a38dd7e1cd9a8b04a20f79
Do you know any other tests that should also be fixed?
