### ISSUE TITLE
Math functions tests fail on Windows

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/co19#50]
The following tests fail on Windows x64
LibTest/math/acos_A01_t01
LibTest/math/asin_A01_t01
LibTest/math/atan_A01_t01
LibTest/math/cos_A01_t01
LibTest/math/tan_A01_t01

These tests works well on Linux

**Comment by alsemenov** [comment]
Specification should be clarified, in order to fix the tests.
Reported bug for specification https://github.com/dart-lang/sdk/issues/26261

**Comment by athomas** [comment]
We need to use approximate equals here. The corresponding SDK issue will be closed as won't fix.
