### ISSUE TITLE
Make type error detection less specific

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#527]
The treatment of type errors in Dart is about to change slightly. Currently there is a distinction between `TypeError` and `CastError`, but in the future we plan to stop making this distinction. Cf. dart-lang/language#787.

In order to avoid having failures due to overly specific expectations about the error thrown in various tests, we should adjust the `checkTypeError` in https://github.com/dart-lang/co19/blob/45dcc9d4a34f008af14f8b881ac2b85f084d46f0/Utils/dynamic_check.dart to be

```dart
checkTypeError(f()) {
  Expect.throws(f, (e) => e is TypeError || e is CastError,
      'Type error should be thrown');
}
```

and use this in order to verify that a type error occurs, rather than checking specifically for a `TypeError` or a `CastError`.

**Comment by eernstg** [comment]
I can see that `checkTypeError` is now applying the less specific check. But how about all the usages?

```
sdk/tests/co19/src((def1183ba...))$ dgrep TypeError | wc -l
6773
sdk/tests/co19/src((def1183ba...))$ dgrep CastError | wc -l
36
```

**Comment by sgrekhov** [comment]
@eernstg thank you for pointing. Fixed

**Comment by eernstg** [comment]
@sgrekhov, thank you for fixing a _lot_ of code in a few hours! ;-)
