### ISSUE TITLE
LibTest/html/Element/getBoundingClientRect_A01_t02 wrong on Safari

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#53]
In current Safari, LibTest/html/Element/getBoundingClientRect_A01_t02 is failing because the two divs are exactly the same height (38). So the problem isn't with getBoundingClientRect, it's that the layout isn't making it larger. On Chrome the second one is of height 53.

**Comment by alan-knight** [comment]
I'm suspicious that 
  LayoutTests/fast/dom/partial-layout-non-overlay-scrollbars_t01
is the same root cause, a change related to scrollbar layout.

**Comment by sgrekhov** [comment]
Probably it was Safari issue. Both of the tests mentioned above works for me on both Safari nad Chrome. Tested on Dart VM 1.20.1 "macos_x64" and Safari 10.0
