### ISSUE TITLE
Null safety tests need update for top-equality

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/co19#530]
The following test: 

https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/generics_A01_t01.dart#L23

is failing on our bots (DDC, Strong):

https://dart-ci.appspot.com/log/ddc-nnbd-linux-release-chrome/dartdevk-strong-linux-release-chrome/1956/co19/LanguageFeatures/nnbd/generics_A01_t01

In this case, the test is incorrect.  `Object?` and `dynamic` are not equal.  It appears that at least these other ones are also breaking similarly:

LanguageFeatures/nnbd/generics_A01_t03
LanguageFeatures/nnbd/generics_A01_t05
LanguageFeatures/nnbd/generics_A01_t07
LanguageFeatures/nnbd/generics_A01_t08

( fyi - @eernstg )

**Comment by eernstg** [comment]
Thanks, @vsmenon! I do not think it is possible to obtain the value of the default bound at run time (we can obtain the 'default default type argument' via instantiation to bound, but that's a different thing). So these tests will probably have to probe the static properties only.
