### ISSUE TITLE
Please triage the failures in the co19 roll to 34a1386e6e7d3e27f5f2b4461aeb6f8794ab55c7

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#537]
In CL https://dart-review.googlesource.com/c/sdk/+/138289/ we rolled co19 to 34a1386e6e7d3e27f5f2b4461aeb6f8794ab55c7

Please triage these new failures and report issues:
https://dart-ci.firebaseapp.com/cl/138289/1

**Comment by sgrekhov** [comment]
Triage results


analyzer-asserts-strong-linuxPass -> CompileTimeError (expected Pass) |  
-- | --
✔ co19/LanguageFeatures/nnbd/static_errors_A18_t02 | Non function type aliases
Pass -> CompileTimeError (expected StaticWarning) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A17_t04 | Non function type aliases
Pass -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t01 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t03 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t05 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t07 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t09 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t11 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t13 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t15 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A16_t02 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A19_t02 | Non function type aliases
new test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A01_t03 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A01_t07 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t01 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t03 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t05 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t07 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t09 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t11 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t13 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t15 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t18 | 40950
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t20 | 40950
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t31 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A14_t11 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A17_t02 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/none | Non function type aliases
new test -> CompileTimeError (expected StaticWarning) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/01 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/02 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/03 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/04 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A32_t03/05 | Non function type aliases
new test -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/late_A10_t01 | 40941
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t04 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t06 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t10 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t14 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A19_t03 | Non function type aliases
new test -> StaticWarning (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A14_t08 | 39865
analyzer-asserts-strong-linuxcfe-strong-linuxPass -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A30_t01 | Test fixed
Pass -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A15_t04 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A22_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A23_t01 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A26_t01 | 39876
new test -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t01 | Test deleted
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t12 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t13 | Test fixed
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t16 | Test fixed
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t17 | Test fixed
✔ co19/LanguageFeatures/nnbd/nullability_definitions_A02_t19 | Non function type aliases
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t17 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t19 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t21 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t23 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t25 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t27 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t08 | Test deleted
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t13 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A26_t03 | 40943
✔ co19/LanguageFeatures/nnbd/static_errors_A26_t04 | 39876
cfe-strong-linuxCompileTimeError -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A31_t01 | 40945
Pass -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t01 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t02 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t03 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t04 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t05 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t01 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t02 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t03 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t04 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A15_t02 | 40949
✔ co19/LanguageFeatures/nnbd/static_errors_A31_t02 | 40945
new test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/const_type_var_elimination_A01_t01 | 40977
✔ co19/LanguageFeatures/nnbd/static_errors_A13_t12 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A13_t13 | Test fixed
new test -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/exports_A01_functions_t16 | 40973
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t01 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t02 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t03 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t04 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t05 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t06 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t07 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t08 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t09 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t10 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t11 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t12 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t13 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A05_t14 | 40951
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t18 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t20 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t22 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t24 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t26 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A06_t28 | 40940
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t06 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t07 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t09 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t10 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t11 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t12 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t14 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t15 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t16 | 40946
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t05 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t06 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t07 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t08 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t09 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t10 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t11 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t12 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t13 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t14 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t15 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A09_t16 | 40948
✔ co19/LanguageFeatures/nnbd/static_errors_A10_t14 | 40954
dartdevk-strong-linux-release-chromenew test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t03 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t04 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t07 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t08 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t09 | 40389
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t13 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t14 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t17 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t18 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t19 | 40389
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t23 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t24 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t27 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t28 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t29 | 40389
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t33 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t34 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t37 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t38 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t39 | 40389
cfe-strong-linuxdartdevk-strong-linux-release-chromenew test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t02 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t04 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t06 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t08 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t10 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t12 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t14 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t16 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t18 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t20 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t22 | 39666
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A02_CLASSPARAM_t24 | 39666
dartdevk-strong-linux-release-chromenew test -> RuntimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t19 | 40389
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t23 | 40389
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A03_t01 | 40978
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A03_t04 | 40978
✔ co19/LanguageFeatures/nnbd/static_errors_A08_t31 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A24_t01 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A24_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A29_t03 | Test fixed
✔ co19/LanguageFeatures/nnbd/static_errors_A29_t04 | Test fixed
