### ISSUE TITLE
LibTest/async/Future/then_A05_t01.dart does not seem to specify failure

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#539]
In [said test](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/async/Future/then_A05_t01.dart), it is described that an `onError` with 3 positional parameters causes a dynamic error. However, the test does not seem to specify this expectation (possibly because `runZoned` only recently obtained the ability to throw synchronously, so the dynamic error used to be missing, and we only now discover that it is not expected).

[This log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8887851701524970304/+/steps/test_results/0/logs/new_test_failures__logs_/0), from [this CL](https://dart-review.googlesource.com/c/sdk/+/136628/), shows that ongoing work can make this issue come up.

**Comment by eernstg** [comment]
Note that the changes being backported have not all been landed, so it may be a good idea to check the corresponding CL in order to see that the tools are actually in a state where the change has taken place.

**Comment by sgrekhov** [comment]
@eernstg the change https://dart-review.googlesource.com/c/sdk/+/136628/ is still in "Merge conflict" state. Is it still actual?

**Comment by eernstg** [comment]
Let's close this issue, and deal with test failures when and if they arise.
