### ISSUE TITLE
LayoutTests/fast/css/background-clip-text_t01 fails on Chrome due to change in Chrome behaviour

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#54]
Setting background-clip to -webkit-text or text fails in current Chrome in JS. I'm not sure
 why.

**Comment by sgrekhov** [comment]
-webkit-... properties are non-standard and therefore checking for these properties is not correct. Removed all the checks where these properties are expected to return anything except empty string.
Fixed. 07fd99559abe584974f323e862c619139d6b3058
