### ISSUE TITLE
LibTest/core/String/String.fromEnvironment_A01_t01 should expect the empty string

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#540]
[Said test](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/core/String/String.fromEnvironment_A01_t01.dart) expects `new String.fromEnvironment(v)` to evaluate to null when `v` is a string which is not defined in the environment.

However, with the upcoming changes [here](https://dart-review.googlesource.com/c/sdk/+/135318/), it will evaluate to the empty string rather than null, so the test needs to be updated to expect that.

This change is being backported, so the change needs to be made in the pre-nnbd branch, but it will also affect the master branch version, so both tests need to be updated.

**Comment by eernstg** [comment]
Note that the changes being backported have not all been landed, so it may be a good idea to check the corresponding CL in order to see that the tools are actually in a state where the change has taken place.

**Comment by eernstg** [comment]
A similar change is needed in [co19_2/LibTest/core/int/int.fromEnvironment_A01_t01.dart](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/core/int/int.fromEnvironment_A01_t01.dart), as well as in the corresponding test from the master branch. It might be useful to add a test case where a `defaultValue` is passed, making this test similar to the one for `String` which is mentioned above.

**Comment by eernstg** [comment]
Here is the CL where the breaking change is performed: https://dart-review.googlesource.com/c/sdk/+/140640. So when that change lands, the above changes to the tests are needed.

**Comment by eernstg** [comment]
Said CL is now landing, so the changes are needed now.

**Comment by sgrekhov** [comment]
Fixed in both branches
