### ISSUE TITLE
Several tests need adjustments now that stack traces will not be null

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#541]
As part of the backporting of a few breaking changes to pre-nnbd semantics, stack traces will no longer be null, cf. https://dart-review.googlesource.com/c/sdk/+/128660.

This breaks the following tests:
- [co19_2/LibTest/async/Future/then_A05_t03](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/async/Future/then_A05_t03.dart)
- [co19_2/LibTest/async/Stream/handleError_A04_t03](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/async/Stream/handleError_A04_t03.dart)
- [co19_2/LibTest/async/Stream/listen_A05_t03](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/async/Stream/listen_A05_t03.dart)
- [co19_2/LibTest/async/StreamSink/addError_A01_t01](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/async/StreamSink/addError_A01_t01.dart)

[This log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8891277871412838192/+/steps/test_results/0/logs/new_test_failures__logs_/0) is one of the locations where this issue has come up.

The stack trace which is provided where a null used to be passed is `StackTrace.empty`, and it should be possible to test against that instead.

**Comment by eernstg** [comment]
Note that the changes being backported have not all been landed, so it may be a good idea to check the corresponding CL in order to see that the tools are actually in a state where the change has taken place.

**Comment by leafpetersen** [comment]
Also co19_2/LibTest/io/IOSink/addError_A01_t04 .

**Comment by sgrekhov** [comment]
@eernstg, @leafpetersen the [CL](https://dart-review.googlesource.com/c/sdk/+/128660) mentioned above is still in "Merge conflict" state. Is the change and this issue still actual?

**Comment by eernstg** [comment]
I think this change is still actual.
@lrhn, do you intend to land https://dart-review.googlesource.com/c/sdk/+/128660?

**Comment by lrhn** [comment]
I think that CL was subsumed by https://dart-review.googlesource.com/c/sdk/+/139880, which has landed. I'll properly abandon the original.
