### ISSUE TITLE
UNIX epoch timestamps rather than null breaks tests

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#543]
The updates in https://dart-review.googlesource.com/c/sdk/+/136585, backporting a breaking change into the pre-nnbd part of the tool chain, cause the following tests to fail:

- [co19_2/LibTest/io/FileStat/statSync_A02_t01](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/io/FileStat/statSync_A02_t01.dart)
- [co19_2/LibTest/io/FileStat/stat_A02_t01](https://github.com/dart-lang/co19/blob/pre-nnbd/LibTest/io/FileStat/stat_A02_t01.dart)

The issue is that the `accessed`, `changed`, `modified` getters no longer return null, so in the cases where null used to be expected we should now expect a non-null placeholder value (1970-01-01 00:00:00.000Z). I believe that timestamp can be obtained using `DateTime.fromMillisecondsSinceEpoch(0, isUtc: true)`.

**Comment by eernstg** [comment]
Note that the changes being backported have not all been landed, so it may be a good idea to check the corresponding CL in order to see that the tools are actually in a state where the change has taken place.

**Comment by eernstg** [comment]
Note that #573 reports on the same issue and contains additional links.

**Comment by sgrekhov** [comment]
Fixed in both master and pre-nnbd branches
