### ISSUE TITLE
LayoutTests/fast/dom/StyleSheet/detached-stylesheet-without-wrapper_t01 fails due to change in Chrome behaviour

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#55]
The test LayoutTests/fast/dom/StyleSheet/detached-stylesheet-without-wrapper_t01 now fails with a parentStyleSheet still being found after head has been removed. This is happening in straight JavaScript as well, so is presumably a change in underlying behaviour.

**Comment by sgrekhov** [comment]
This test failed in FF as well (failure were switched off in *.status files). In both Dart and JS version getMatchedCSSRules() was used which is not supported in FF. I rewrote the test and make check for removed stylesheets in a cross-browser way. Fixed. See c5185eab2f2769d83515025df00410021c781ba5
