### ISSUE TITLE
Null-safety: Least/greatest closure uses `Object?`, not `dynamic`, when no bound is given

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#575]
[Here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#least-and-greatest-closure) is a change to Dart, part of null-safety, that may create the need for several changes to tests that are running with null-safety enabled.

The change is that the least and greatest closure of a type will use `Object?` where it used to use `Object` or `dynamic`. The least and greatest closure is only used during type inference on expressions, and in particular there is no change to the meaning of a raw type used as a type annotation (where instantiation to bound will still use `dynamic` as the initial value of a type argument with no bound).

[Edit April 7, eernstg: The following example does _not_ rely on greatest closure after all, cf. [this comment](https://github.com/dart-lang/language/issues/908#issuecomment-607753083). So we need to develop a template that does indeed test greatest closure.]

One example where it does make a difference is given [here](https://github.com/dart-lang/sdk/issues/40928):

```dart
bool Function(T) predicate<T>(bool Function(T) fn) => (T val) => fn(val);

void main() {
  print(predicate((v) => v % 2 == 1)(3));
}
```

Type inference would previously choose `dynamic` as the actual type argument to the invocation of `predicate`, and hence `v % 2` would be type correct (but unsafe), because `v` would have type `dynamic`. With this change, the type argument and the type of `v` is `Object?`, and `v % 2` is an error because `v` may be null. This issue serves to explain why this kind of error may arise in tests where null safety is enabled.

**Comment by eernstg** [comment]
I'm looking into how to write a small program that actually tests the properties of the greatest/least closure of a type scheme&mdash;the `predicate` example [above](https://github.com/dart-lang/co19/issues/575#issue-579767102) doesn't actually do that.

**Comment by eernstg** [comment]
Here are a couple of templates for how we can test the greatest closure of a type scheme. First dynamically:

```dart
import 'package:expect/expect.dart';

// Standard tools -----------------------------------------------------

Type? _capturedTypeArgument;

X captureTypeArgument<X>() {
  _capturedTypeArgument = X;
  throw 1;
}

Type? get capturedTypeArgument {
  var result = _capturedTypeArgument;
  _capturedTypeArgument = null;
  return result;
}

Type typeOf<X>() => X;

// --------------------------------------------------------------------

class C<X> {}

void main() {
  // The context type scheme is a plain type: `void Function({bool arg})`.
  {
    void f(void Function({bool arg}) Function() g) => g();
    try { f(() => captureTypeArgument()); } catch (_) {}
    Expect.equals(typeOf<void Function({bool arg})>(), capturedTypeArgument);
  }

  // The context type scheme is `C<?>`.
  {
    void f<X>(C<X> Function() g) => g();
    try { f(() => captureTypeArgument()); } catch (e) {}
    Expect.equals(typeOf<C<Object?>>(), capturedTypeArgument);
  }
}
```

The following points are important:

- We declare a function `f` which is used to specify a type scheme. This function takes as many type arguments (with no bounds) as we wish to have `?` in the type scheme. So when the type scheme is a plain type there are no `?`s and `f` is non-generic. But in the more interesting case where the type scheme has a single `?`, `f` takes one type argument. I don't think there is a need to test type schemes with multiple `?`, so let's just stick to a non-generic `f` and an `f` that takes a single type argument, and also focus on the latter because the plain type is trivial (the greatest/least closure is just that same type).
- The support code includes `captureTypeArgument` which is a function that will return _whatever_ the context wants. In order to be able to do this it must throw. So we need to call it in a `try`/`catch` statement. The point is that we may now call `f` and pass a function literal to `f` that returns `captureTypeArgument()`, which is exactly the situation where it is specified that the greatest closure of the context type must be used.


So the captured type argument is the greatest closure of the type scheme, and we can directly test it as shown, using something like `Expect.equals`.

The technique used in order to write these tests is then as follows:

- Choose a type scheme (for instance `Map<int, List<?>>`).
- Write the corresponding function (`void f<X>(Map<int, List<X>> Function() g) => g();`).
- Write the invocation that captures the greatest closure of the chosen type scheme (`try { f(() => captureTypeArgument());  } catch (e) {}`). This code does not depend on the type scheme, but it has to be written each time, identically, because it uses `f` and there will be a new `f` for each type scheme we are testing.
- Write the code that tests the outcome (`Expect.equals(typeOf<Map<int, List<Object?>>>(), capturedTypeArgument);`). This differs from type scheme to type scheme, of course, because each of them has their own expected result that we are testing against.

Then statically:

```dart
import 'package:expect/expect.dart';

// Standard tools -----------------------------------------------------

X captureTypeArgument<X>() => throw 1;

// --------------------------------------------------------------------

abstract class C<X> {
  X get x;
  set x(X value);
}

void main() {
  // The context type scheme is a plain type: `void Function({bool arg})`.
  {
    void f(void Function({bool arg}) Function() g) => g();

    // Verify that we can call the function with the specified arguments.
    f(() => captureTypeArgument()..call());
    f(() => captureTypeArgument()..call(arg: true));
    
    // Verify that a couple of wrong argument lists are rejected.
    f(() => captureTypeArgument()..call(throw 1));
    //                                  ^
    // [analyzer] unspecified
    // [cfe] unspecified
    f(() => captureTypeArgument()..call(arg: 'Hello'));
    //                                       ^
    // [analyzer] unspecified
    // [cfe] unspecified
    
    // Verify that the return type is `void`: Returned value not usable,
    // not even to access a member of `Object`.
    f(() => captureTypeArgument()..call().toString);
    //                                    ^
    // [analyzer] unspecified
    // [cfe] unspecified
  }

  // The context type scheme is `C<?>`.
  {
    void f<X>(C<X> Function() g) => g();

    // Verify that the captured type has an `x`.
    f(() => captureTypeArgument()..x);
    
    // Verify that `x` has a top type.
    f(() => captureTypeArgument()..x = 42);
    f(() => captureTypeArgument()..x = 'Hello');
    f(() => captureTypeArgument()..x = null);
    
    // Verify that `x` does not have type `dynamic` (but, expecting the type
    // to be `Object?` we need the null aware access `?.`).
    f(() => captureTypeArgument()..x?.unknownMember);
    //                               ^
    // [analyzer] unspecified
    // [cfe] unspecified
    
    // Verify that `x` has `Object` members (so it can have type `Object?`,
    // but it cannot have type `void`).
    f(() => captureTypeArgument()..x.toString);
  }
}
```

For the static test we basically need to "dot into the structure" and check that the type represented by the `?` is indeed `Object?` or `Never`. We use a cascade for that, because that will allow us to (1) make the invocation of `captureTypeArgument()` the target of an inference operation where the context type is preserved (so it is still the return type of the parameter type of `f`, with a type argument of `f` in the location where we want a `?` in the type scheme), and yet we can explore whatever we want in the type `T` which is the result of inference on `captureTypeArgument()` by adding a cascade section.


We access `x` when we expect that `T` is `C<...>`. We verify that the type of `x` is a top type by assigning an `int` and a `String` to it () We expect that the member `x` of `T` has type `Object?`, and in particular it is an error to access an undefined member (so `..x.unknownMember` should be a compile-time error), which reveals that `x` doesn't have the type `dynamic`. (And that's important, because this is what the update to null-safety is basically all about). Finally, we must check that `T` isn't `C<void>`, and we do that by detecting that it is not an error to access `toString`.

This was `C<?>`. I also showed a plain type; for that we'd just want to try out some obvious properties such that it is unlikely to be a different type than the one that we expect.

**Comment by iarkh** [comment]
Fixed together with the Issue https://github.com/dart-lang/co19/issues/602
