### ISSUE TITLE
Please triage the failures in the co19 roll to 51ee35d0459ad329287254b79ed3918d78b5bbf3

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#578]
In https://dart-review.googlesource.com/c/sdk/+/139641/ we rolled co19 to 51ee35d0459ad329287254b79ed3918d78b5bbf3

Please triage these new failures and report issues:
https://dart-ci.firebaseapp.com/cl/139641/1

**Comment by sgrekhov** [comment]
Triafe results below


analyzer-asserts-strong-linuxPass -> MissingCompileTimeError (expected Pass) |  
-- | --
✔ co19/LanguageFeatures/nnbd/static_errors_A13_t01 | 41066
✔ co19/LanguageFeatures/nnbd/static_errors_A13_t02 | 41066
new test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t01 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t05 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t07 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/generics_A01_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/generics_A01_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/legacy_libraries_A01_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/legacy_libraries_A01_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/legacy_libraries_A03_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A02_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A04_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A07_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A10_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A14_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A16_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A01_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A01_t07 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A01_t05 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A02_t05 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A14_t11 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A17_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A18_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/none | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A01_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A02_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A02_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A03_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A06_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A06_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A07_t06 | Non function type aliasesnot supported by analyzer
new test -> CompileTimeError (expected StaticWarning) |  
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A17_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/01 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A32_t03/05 | Non function type aliasesnot supported by analyzer
new test -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t06 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t08 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/exports_A01_typedef2_t09 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t05 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t06 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t10 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t14 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t17 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A01_t04 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A03_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A16_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A19_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A19_t03 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A07_t02 | Non function type aliasesnot supported by analyzer
✔ co19/LanguageFeatures/nnbd/type-aliases/syntax_A07_t04 | Non function type aliasesnot supported by analyzer
cfe-strong-linuxnew test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A01_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A03_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A06_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A08_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A12_t02 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t02 | Test fixed
new test -> MissingCompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t03 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t05 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t03 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t06 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t12 | 40972
✔ co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t19 | 40972
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A02_t04 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A15_t02 | 40949
✔ co19/LanguageFeatures/nnbd/type-aliases/static_errors_A15_t04 | 40949
dartdevk-strong-linux-release-chromenew test -> CompileTimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A09_t12 | Test fixed
✔ co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A11_t12 | Test fixed
✔ co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A13_t12 | Test fixed
✔ co19/LanguageFeatures/nnbd/tripple-shift/null_aware_operator_A15_t12 | Test fixed
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t08 | Non function type aliases not supported by DDC
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t10 | Non function type aliases not supported by DDC
✔ co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t08 | Non function type aliases not supported by DDC
✔ co19/LanguageFeatures/nnbd/type-aliases/type_reification_A01_t05 | Non function type aliases not supported by DDC
✔ co19/LanguageFeatures/nnbd/type-aliases/type_reification_A01_t06 | Non function type aliases not supported by DDC
dartdevk-strong-linux-release-chromeCompileTimeError -> RuntimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/legacy_libraries_A02_t01 | 41067
new test -> RuntimeError (expected Pass) |  
✔ co19/LanguageFeatures/nnbd/const_evaluation_A01_t10 | 39678
✔ co19/LanguageFeatures/nnbd/const_evaluation_A01_t12 | 39678
✔ co19/LanguageFeatures/nnbd/const_evaluation_A01_t18 | 39678
✔ co19/LanguageFeatures/nnbd/type-aliases/legacy_libraries_A03_t02 | Test fixed
