### ISSUE TITLE
writeByte_A01_t01.dart needs to be updated

### ISSUE THREAD

**Issue by ZichangG** [dart-lang/co19#582]
The test failed, because the list has not been initialized properly. Then expect() failed.

https://github.com/dart-lang/co19/blob/51ee35d0459ad329287254b79ed3918d78b5bbf3/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart#L37

https://github.com/dart-lang/co19/blob/51ee35d0459ad329287254b79ed3918d78b5bbf3/LibTest/io/RandomAccessFile/writeByte_A01_t01.dart#L51

**Comment by sgrekhov** [comment]
@ZichangG how test fails? It works for me. List initialized at line 35
`file.readIntoSync(list, num);`

**Comment by ZichangG** [comment]
I can't remember where I saw the failure.
I run locally again and this seems to work!
