### ISSUE TITLE
Need tests to work even with different `defaultValue` default values

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#585]
The test 'LibTest/core/String/String.fromEnvironment_A01_t01.dart' needs to be adjusted such that it will continue to work independently of the default value specified for `defaultValue`. So we need this:

```dart
var s2 = const bool.hasEnvironment("SOME_ENV_VARIABLE") ?
    const String.fromEnvironment("SOME_ENV_VARIABLE") : null;
```

Note that it should use `const` rather than `new`: The documentation of these constructors indicates that it is a dynamic error to invoke them at run time (so they can only be used in constant expressions). This is not implemented by all tools, but it is more important to make this test test something that should actually work, and then we may put a TODO somewhere to decide on whether to insist that the `new` usage should cause an exception, and write a separate test for that.

The test 'LibTest/core/int/int.fromEnvironment_A01_t01.dart' needs a corresponding update.

These changes need to be performed in both the master and the pre-nnbd branch, because the default values for `defaultValue` will be changed in both SDKs.

**Comment by sgrekhov** [comment]
Fixed in both branches

**Comment by eernstg** [comment]
Oops, please revert this and make the change as described in #540. It turns out that we have very few tests where we test that the default value for `defaultValue` is as expected for the `fromEnvironment` constructors, so it's better to keep the form that actually breaks when these default values differ from the expected value, rather than making the test independent of said default values.

**Comment by sgrekhov** [comment]
I didn't rever but did the changes for #540 above this. Protection for the case when the system has an environment variable used in the test was left

**Comment by eernstg** [comment]
Sounds good! The important bit is that it should fail if the default value of `defaultValue` of `int.fromEnvironment` differs from `0`, and for `String.fromEnvironment` if it differs from the empty string.

**Comment by eernstg** [comment]
I'm afraid the current version does not test the default value, it uses `bool.hasEnvironment` to avoid depending on the default value, so it could be _anything_ and the test would still succeed. So we need to go back to a form that uses a plain `String.fromEnvironment(ENV_VAR)` and checks that it evaluates to the empty string (because the environment doesn't contain a declaration named `"SOME_ENV_VARIABLE"`, so we use the default value of `defaultValue`, and that's the empty string). Similarly for the `int` test, and in both branches.

**Comment by sgrekhov** [comment]
No problem. Changed in both branches
