### ISSUE TITLE
Runtime failure in co19/LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t19/23

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/co19#593]
The tests `co19/LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t19` and `co19/LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t23` fail at runtime because the evaluation of the overridden field `OPTED_NEVER_FIELD.n` throw on instantiation of the object.

**Comment by iarkh** [comment]
I've filed issue #40389 about overriding Never by Null in legacy code.

Dart and Analyzer behavior changed since that time, however #40389 is still opened as well as language bug #825. NNBD Spec also changed since the time when the tests were created... So is this is a bug and should I update the tests? @Eernstg, could you please confirm?

**Comment by johnniwinther** [comment]
I don't think there is a problem in the override - the CFE doesn't complain anymore. The problem is at runtime - the initialization of the field `Never n = throw ...` throws. I think the test needs to be rewritten to expect the exception on creation:

```Dart
// opt-in
class A {
  Never n = throw 'foo';
}
// opt-out
class B extends A {
  Null n = null;
}

main() {
  try {
    new B();
  } catch(_) {
   return;
  }
  throw 'Exception expected';
}
```

**Comment by eernstg** [comment]
Agreed, initialization of `OPTED_NEVER_FIELD.n` should throw even in the case where an overriding declaration `A.n` prevents access to the former.

But if the purpose is to check statically that it is allowed for a field of type `Never` in an opted-in library to be overridden by a field of type `Null` in a legacy library, it may be more convenient to say `class A implements OPTED_NEVER_FIELD { Null n; }`, and keep `main` unchanged.

**Comment by iarkh** [comment]
> Agreed, initialization of `OPTED_NEVER_FIELD.n` should throw even in the case where an overriding declaration `A.n` prevents access to the former.
> 
> But if the purpose is to check statically that it is allowed for a field of type `Never` in an opted-in library to be overridden by a field of type `Null` in a legacy library, it may be more convenient to say `class A implements OPTED_NEVER_FIELD { Null n; }`, and keep `main` unchanged.

Such a test already exists, it's override_checking_A01_FIELD_t21.
So I've just added exception check for two tests from the description.
