### ISSUE TITLE
Language/Classes/Setters/syntax_t04 test is wrong

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#6]
The Dart language spec 3rd edition June 2015 says that the return type of a setter must be void, and the value of an assignment expression is the RHS, not the return value of the setter:

Page 89, 16.19 Expressions/Assignment
The value of the assignment expression is o2 irrespective of whether setter
lookup has failed or succeeded.

**Comment by sgrekhov** [comment]
Fixed. Please see https://github.com/dart-lang/co19/commit/15821d765455082ceccca254356a377c1afabe2e
