### ISSUE TITLE
Please triage the failures on [co19] Roll co19 to 929da300c553ebb8a9ff744746bcc1326613e1f9

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#609]
There are new test failures on [[co19] Roll co19 to 929da300c553ebb8a9ff744746bcc1326613e1f9](https://dart-review.googlesource.com/c/sdk/+/142990).

The tests
```
co19/LanguageFeatures/Simple-bounds/dynamic/class_FutureOr_l1_t03 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t05 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t06 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t07 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t08 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/class_typedef_l1_t04 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/class_typedef_l1_t08 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef1_typedef_l1_t04 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef1_typedef_l1_t08 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_FutureOr_l1_t04 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_l1_t09 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_l1_t10/none RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_l2_t01 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t05 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t09 RuntimeError (expected Pass)
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t10 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/exports_A01_var_t04 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t02 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t01 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t02 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t06 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t12 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t14 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t20 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t27 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t28 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t29 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/future_flattening_A01_t30 RuntimeError (expected Pass)
    and 80 more tests
```
are failing on configurations
```
analyzer-asserts-strong-linux
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-chrome
dartdevk-strong-linux-release-chrome
```

**Comment by sgrekhov** [comment]
Triage result


Analyzer |  Result
-- | --
co19/LanguageFeatures/nnbd/future_flattening_A01_t49 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t50 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t81 | Test fixed
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t05 | Type aliases are not supported in analyzer
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t06 | Type aliases are not supported in analyzer
co19/LanguageFeatures/nnbd/type-normalization/norm_A01_t01 | Type aliases are not supported in analyzer
co19/LanguageFeatures/nnbd/type-normalization/norm_A05_t01 | Test fixed
co19/LanguageFeatures/nnbd/type-normalization/norm_A08_t01 | 39896
  |  
CFE  |  
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t02 | 41349
co19/LanguageFeatures/nnbd/future_flattening_A01_t06 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t14 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t20 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t27 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t28 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t34 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t42 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t48 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t49 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t50 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t55 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t56 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t81 | Test fixed
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t05 | 41349
co19/LanguageFeatures/nnbd/type-normalization/norm_A01_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A05_t01 | Test fixed
co19/LanguageFeatures/nnbd/type-normalization/norm_A08_t01 | 39896
co19/LanguageFeatures/nnbd/exports_A01_var_t04 | Test fixed
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t03 | 41349
co19/LanguageFeatures/nnbd/future_flattening_A01_t12 | 41437
co19/LanguageFeatures/nnbd/future_flattening_A01_t40 | 41437
co19/LanguageFeatures/nnbd/null_promotion_A01_t09 | 41494
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t01 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t03 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t05 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t07 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t09 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t11 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t13 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t15 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t18 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A02_REQ_ARGS_t20 | 41527
co19/LanguageFeatures/nnbd/overriding/override_checking_A04_t01 | 41529
co19/LanguageFeatures/nnbd/overriding/override_checking_A04_t02 | 41529
co19/LanguageFeatures/nnbd/overriding/override_checking_A04_t03 | 41529
co19/LanguageFeatures/nnbd/overriding/override_checking_A04_t04 | 41529
co19/LanguageFeatures/nnbd/overriding/override_checking_A04_t05 | 41529
co19/LanguageFeatures/nnbd/static_errors_A02_t08 | 41495
co19/LanguageFeatures/nnbd/static_errors_A02_t14 | 41495
co19/LanguageFeatures/nnbd/static_errors_A04_t14 | 41496
co19/LanguageFeatures/nnbd/static_errors_A05_t14 | 40951
co19/LanguageFeatures/nnbd/static_errors_A06_t09 | 40940
co19/LanguageFeatures/nnbd/static_errors_A06_t21 | 40940
co19/LanguageFeatures/nnbd/static_errors_A06_t27 | 40940
co19/LanguageFeatures/nnbd/static_errors_A06_t28 | 40940
co19/LanguageFeatures/nnbd/static_errors_A08_t16 | 41498
co19/LanguageFeatures/nnbd/static_errors_A09_t16 | 41499
co19/LanguageFeatures/nnbd/static_errors_A10_t14 | 40954
co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A01_t10 | 41494
co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t06 | 41494
co19/LanguageFeatures/nnbd/type-aliases/null_promotion_A02_t08 | Test fixed
co19/LanguageFeatures/nnbd/type-aliases/nullability_definitions_A02_t12 | 41501
co19/LanguageFeatures/nnbd/type-aliases/static_errors_A15_t04 | 41501
co19/LanguageFeatures/nnbd/type-normalization/norm_A02_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A03_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A04_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A09_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A10_t01 | Type aliases are not supported
  |  
DDC  |  
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t02 | 41349
co19/LanguageFeatures/nnbd/future_flattening_A01_t49 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t50 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t64 | 41340
co19/LanguageFeatures/nnbd/future_flattening_A01_t65 | 41340
co19/LanguageFeatures/nnbd/future_flattening_A01_t66 | 41340
co19/LanguageFeatures/nnbd/future_flattening_A01_t81 | Test fixed
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t05 | 41349
co19/LanguageFeatures/nnbd/type-normalization/norm_A01_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A05_t01 | Test fixed
co19/LanguageFeatures/nnbd/type-normalization/norm_A08_t01 | 39896
  |  
Dart2js |  
co19/LanguageFeatures/Simple-bounds/dynamic/class_FutureOr_l1_t03 | 39666
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t05 | 41537
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t06 | 41537
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t07 | 41537
co19/LanguageFeatures/Simple-bounds/dynamic/class_l1_t08 | 41537
co19/LanguageFeatures/Simple-bounds/static/class_typedef_l1_t04 | 41537
co19/LanguageFeatures/Simple-bounds/static/class_typedef_l1_t08 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef1_typedef_l1_t04 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef1_typedef_l1_t08 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_FutureOr_l1_t04 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_l1_t09 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_l1_t10/none | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_l2_t01 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t05 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t09 | 41537
co19/LanguageFeatures/Simple-bounds/static/typedef_typedef_l1_t10 | 41537
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A01_t02 | 41502
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t01 | 41349
co19/LanguageFeatures/nnbd/extension_method_resolution_A03_t02 | 41349
co19/LanguageFeatures/nnbd/future_flattening_A01_t29 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t30 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t31 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t33 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t41 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t43 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t44 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t47 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t49 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t50 | Test fixed
co19/LanguageFeatures/nnbd/future_flattening_A01_t53 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t54 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t57 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t58 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t59 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t64 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t65 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t66 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t75 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t76 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t77 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t79 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t80 | 41537
co19/LanguageFeatures/nnbd/future_flattening_A01_t81 | Test fixed
co19/LanguageFeatures/nnbd/null_aware_operator_A09_t06 | Timeout. Strange
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t05 | 41349
co19/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t06 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A01_t01 | Type aliases are not supported
co19/LanguageFeatures/nnbd/type-normalization/norm_A05_t01 | Test fixed
co19/LanguageFeatures/nnbd/type-normalization/norm_A06_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A07_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A08_t01 | 39896
co19/LanguageFeatures/nnbd/type-normalization/norm_A11_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A12_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A13_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A14_t01 | 41502
co19/LanguageFeatures/nnbd/type-normalization/norm_A15_t01 | 41502
co19/LibTest/core/double/operator_truncating_division_A01_t06 | Timeout. Strange
