### ISSUE TITLE
Please triage the failures on Allow 3 digit (_txxx.dart) pattern for co19 tests

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#610]
There are new test failures on [Allow 3 digit (_txxx.dart) pattern for co19 tests](https://dart-review.googlesource.com/c/sdk/+/143500).

The tests
```
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t001 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t002 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t010 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t010 Crash (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t011 Crash (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t011 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t015 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t017 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t018 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t022 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t029 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t030 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t036 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t037 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t039 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t042 Crash (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t042 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t048 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t055 MissingCompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t057 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t058 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t062 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t064 Crash (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t064 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t067 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t068 Crash (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t068 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t075 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t076 RuntimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t077 RuntimeError (expected Pass)
    and 10 more tests
```
are failing on configurations
```
cfe-strong-linux
cfe-weak-linux
dart2js-hostasserts-strong-linux-x64-chrome
dartdevk-strong-linux-release-chrome
```

**Comment by iarkh** [comment]
Here are results:

cfe-strong-linux
new test -> MissingCompileTimeError (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t084   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t092   test corrected


cfe-weak-linux
new test -> CompileTimeError (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t029   test corrected, #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t058   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157   test corrected
new test -> MissingCompileTimeError (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t018   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t022   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t030   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t055   test corrected
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t108   #41566, #41567
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t112   #40553
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t113  test corrected

dart2js-hostasserts-strong-linux-x64-chrome
new test -> Crash (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t010   #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t011   #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t042   #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t064   #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t068   #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t119   #41573

new test -> RuntimeError (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t001  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t002  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t015  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t017  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t036  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t037  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t039  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t048  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t057  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t062  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t067  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t075  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t076  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t077  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t089  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t097  #41502
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t102  #41502


dartdevk-strong-linux-release-chrome
new test -> RuntimeError (expected Pass)
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t010   #41576, #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t011   #41576, #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t042   #41576, #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t064  #41576, #40541
✔ co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t068  #41576, #40541
