### ISSUE TITLE
Failures on co19 roll to f65f3578f95415c9a2f3ad002aac7b507549e64a

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#639]
Only one failing test showed up on this roll so far,

configuration analyzer-asserts-weak-linux
Pass -> CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157

Log of the failure is:

| analyzer-asserts-weak-linux:
co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157 broke 
(Pass -> CompileTimeError, expected Pass) |

--- Command "dart2analyzer" (took 134ms):
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart-sdk/bin/dartanalyzer --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=machine --no-hints /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A06_t157.dart

exit code:
1

stderr:
ERROR|COMPILE_TIME_ERROR|INCONSISTENT_INHERITANCE|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A06_t157.dart|26|7|2|Superinterfaces don't have a valid override for 'f': CHECK_TOP_MERGE.f (Never Function(Never) Function()), A_OUT.f (Null* Function(Null*)* Function()*).
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A06_t157.dart|31|22|1|The getter 'f' isn't defined for the type 'C2'.
ERROR|COMPILE_TIME_ERROR|INCONSISTENT_INHERITANCE|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A06_t157.dart|27|7|2|Superinterfaces don't have a valid override for 'f': A_OUT.f (Null* Function(Null*)* Function()*), CHECK_TOP_MERGE.f (Never Function(Never) Function()).
ERROR|STATIC_TYPE_WARNING|UNDEFINED_GETTER|/b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/overriding/override_checking_A06_t157.dart|30|22|1|The getter 'f' isn't defined for the type 'C1'.

--- Re-run this test:
python tools/test.py -n analyzer-asserts-weak-linux co19/LanguageFeatures/nnbd/overriding/override_checking_A06_t157

**Comment by iarkh** [comment]
Dart passes without any error or warning with the same test.

I've filed SDK Issue #41804 about this.

Seems like overriding with invariant function type parameter works incorrectly somehow and this is a bug in analyzer.

**Comment by sgrekhov** [comment]
I this is a SDK issue https://github.com/dart-lang/sdk/issues/41804 then this one can be closed
