### ISSUE TITLE
Some tests need updates after changes in inference in redirecting factory constructors

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/co19#640]
It seems that after the changes discussed at https://github.com/dart-lang/sdk/issues/34714, two tests need to be updated:

co19_2/Language/Generics/Superbounded_types/class_A03_t02/01
co19_2/Language/Generics/Superbounded_types/class_A03_t05/01

Both tests expect a compile-time error, and the changes imply that the code should be tolerated by the compiler.

/cc @eernstg

**Comment by eernstg** [comment]
Agreed, the two factory bodies of the form `C` should allow for successful inference as `C<X>`, so there is no error.
