### ISSUE TITLE
A mixed program cannot run with strong checking: Tests need adjustments

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#644]
Cf. [Failures on [CFE] Error when strong mode mixed with non-opted-in](https://github.com/dart-lang/sdk/issues/41896) and in particular [this comment](https://github.com/dart-lang/sdk/issues/41896#issuecomment-628613100), about 700 co19 tests need to be adjusted now that there is no support in the common front end (and associated backends) for executing a program `P` in strong checking mode when when `P` includes a legacy library (that is, a library that does not enable null-safety).

One issue is that some tests have both `// @dart = 2.6` (or a similar language version, with no null-safety) and `// Requirements=nnbd-strong`. The latter must be changed to `// Requirements=nnbd-weak` (or, if this is already one test from a pair of near-identical tests where one is `-strong` and the other is `-weak` then the `-strong` one may just be deleted).

In other cases a test has both `// @dart = 2.6` (or similar) and `// SharedOptions=--enable-experiment=non-nullable`. In this case the test should be runnable in both weak and strong checking mode, but any attempt to run it in strong checking mode is an error (at startup). So these tests should have `// Requirements=nnbd-weak` added.

See the SDK issue mentioned above for more details about which tests this is about.

**Comment by eernstg** [comment]
I have closed https://github.com/dart-lang/sdk/issues/41896 ('Failures on [CFE] Error when strong mode mixed with non-opted-in'), but that issue is still relevant for this issue because it contains more information about which tests are affected.

**Comment by sgrekhov** [comment]
@eernstg this [commit](https://github.com/dart-lang/co19/commit/8f7fb8b4dba0e00713dfc259b3df18146f5e4030) changed requirements `nnbd-strong` to `nnbd-weak` for those oped in tests which exports @dart-2.6 code. Now, looking at these test failures, I see that we need to change requirements to `nnbd-weak` for those test which are imported by legacy libraries. In other words
```dart
opted_out.dart
// @dart=2.6
import 'opted_in.dart';
...

opted_in.dart
// SharedOptions=--enable-experiment=non-nullable
// Requirements=nnbd-strong <- must be changed to Requirements=nnbd-weak now
...
```
Ok, I'll do it.

**Comment by eernstg** [comment]
I'm a little confused here: I would expect `// Requirements=...` to have no effect when it occurs in any library which is not the entry point of the current program (that is, the 'main' library). Checking with a few examples, this is confirmed. So we should never have any `// Requirements=...` directives in any library which is not an entry point, that's just misleading noise.

Another way to say this is that a library can only contain these directives if it also contains the function `main` (except of course that it _is_ possible for `main` to be imported into an entry point, but that probably never occurs in practice).

The point is that weak/strong checking mode is a global property of an execution, so there is no way we could specify and get weak checking in one library and strong checking in another library in the same program. In practice this is handled by checking the entry point for `// Requirements=...` directives, and ignoring them in all other libraries of the test program.

In general, an entry point is a library which is never imported by other libraries. (There can be exceptions, like `main.dart` imports `lib.dart` and `lib.dart` imports `main.dart`, because they use declarations in each other; or `main2.dart` imports `main.dart`, and both will be used as entry points (so, most likely, both contain a `main` function, and the `main` function in `main.dart` is unused when we run `main2.dart`). But these situations are rare, let's call them "sick import graphs". ;-)

So apart from programs with sick import graphs, this means that there will never be a `// Requirements=...` directive in an imported file. But the example does exactly that:

```dart
// FILE 'opted_out.dart'.
// @dart=2.6
import 'opted_in.dart';
...

// FILE 'opted_in.dart'.
// SharedOptions=--enable-experiment=non-nullable
// Requirements=nnbd-strong <- must be changed to Requirements=nnbd-weak now
...
```

I think `SharedOptions` have the same property as Requirements, so they should also never occur in a library which is not an entry point. But did you mean to say that `opted_out.dart` is imported by `opted_in.dart` instead? That would fix the example.

Then there's the updated example:

```dart
// FILE 'opted_out.dart'.
// @dart=2.6
// SharedOptions=--enable-experiment=non-nullable
// Requirements=nnbd-weak <- must add this even if there is no import of opted_in library
import 'opted_in.dart';
...

// FILE 'opted_in.dart'.
// SharedOptions=--enable-experiment=non-nullable
// Requirements=nnbd-strong 
...
```

This example has the same issue: `opted_in.dart` is imported and contains SharedOptions and Requirements, and that should not happen.

In https://github.com/dart-lang/co19/commit/8af03f7892e6ed6620d6c59a3758ed6804ec4990, I can see that a number of files have a name of the form `*_lib.dart`, and it is very unlikely that they should contain Requirements or SharedOptions.

This means that we do need to consider this topic one more time, so I'll reopen the issue.

**Comment by sgrekhov** [comment]
@eernstg thank you. Requirements and SharedOptions removed from the libraries which don't have main()

**Comment by eernstg** [comment]
Thanks!
