### ISSUE TITLE
LayoutTests/fast/multicol/vertical-rl/image-inside-nested-blocks-with-border_t01 is incorrect

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/co19#65]
Test expectation checks against a width of 0, but I'm seeing it as 210px (which is what I expected given that it is 300px (end) - (5px * 2) (border) - 80px (contents).

**Comment by sgrekhov** [comment]
Fixed. Please see c2edab1fb2e5ac11931aa39a18078add6253b1fd
