### ISSUE TITLE
Missing compile-time error

### ISSUE THREAD

**Issue by mhausner** [dart-lang/co19#66]
Language/Expressions/Instance_Creation/Const/abstract_class_t01
Language/Expressions/Instance_Creation/Const/abstract_class_t03

These two tests should expect a compile time error. Instantiating an abstract class as a compile-time constant is a compile-time error.

**Comment by sgrekhov** [comment]
Thank you. Fixed. See aa0577044baa1d4845d8fa3d03a87e4cde568b01
