### ISSUE TITLE
A library can't opt out of non-nullable by default, when in nnbd-strong mode

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#661]
The following strong mode tests need to be updated, because they include libraries opted out of NNBD, which is not allowed in anymore:

"Error: A library can't opt out of non-nullable by default, when in nnbd-strong mode."

LanguageFeatures/nnbd/legacy_libraries_A01_t01
LanguageFeatures/nnbd/legacy_libraries_A01_t02
LanguageFeatures/nnbd/legacy_libraries_A03_t01
LanguageFeatures/nnbd/legacy_libraries_A04_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t06
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t12
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t18
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t20
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_ARGS_t24
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t06
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t12
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t18
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t24
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t25
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t26
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t27
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t28
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t29
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t31
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t32
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t33
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t34
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t35
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t36
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t37
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t38
LanguageFeatures/nnbd/overriding/override_checking_A01_CLASSPARAM_t39
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t06
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t12
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t18
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t25
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t26
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t27
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t28
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t29
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t30
LanguageFeatures/nnbd/overriding/override_checking_A01_FIELD_t31
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t20
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_GETTER_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t06
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t12
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t18
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t20
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t24
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t25
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t26
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t27
LanguageFeatures/nnbd/overriding/override_checking_A01_REQ_ARGS_t28
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t20
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_RETURN_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t01
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t02
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t03
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t04
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t05
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t06
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t07
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t08
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t09
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t10
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t11
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t12
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t13
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t14
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t15
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t16
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t17
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t18
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t19
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t20
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t21
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t22
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t23
LanguageFeatures/nnbd/overriding/override_checking_A01_SETTER_t24
LanguageFeatures/nnbd/type-aliases/legacy_libraries_A01_t03
LanguageFeatures/nnbd/type-aliases/legacy_libraries_A01_t04
LanguageFeatures/nnbd/type-aliases/legacy_libraries_A03_t02

**Comment by sgrekhov** [comment]
Already fixed by https://github.com/dart-lang/co19/commit/8af03f7892e6ed6620d6c59a3758ed6804ec4990
