### ISSUE TITLE
Allow trailing commas in argument and parameter lists.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/co19#68]
The language specification in the repository has been changed to allow trailing commas in argument and parameter lists (for functions with optional parameters, the comma is allowed after the final parameter, before the closing `}` or ']`).

The following tests fail when this functionality is implemented:
- Language/Expressions/Function_Invocation/Actual_Argument_List_Evaluation/syntax_t05
- Language/Expressions/Method_Invocation/Ordinary_Invocation/syntax_t05
- Language/Expressions/Method_Invocation/Ordinary_Invocation/syntax_t10
- Language/Expressions/Method_Invocation/Super_Invocation/syntax_t05
- Language/Functions/Formal_Parameters/syntax_t04
- Language/Functions/Formal_Parameters/syntax_t05
- Language/Functions/Formal_Parameters/syntax_t12

**Comment by sgrekhov** [comment]
Will fix it sa soon as official specification is updated

**Comment by whesse** [comment]
The test Language/Functions/Formal_Parameters/syntax_t05 is still failing.  Please check if this is an error in the test or in our implementation.

**Comment by lrhn** [comment]
Looks like a typo in the test:
```dart
void f({var p1, }) {}

main () {
} f(1);
```
The `f` call should be inside the `main` function.

**Comment by sgrekhov** [comment]
I don't see any errors in the test and `f` call outside of the `main() `function. See the latest repository version. https://github.com/dart-lang/co19/blob/master/Language/Functions/Formal_Parameters/syntax_t05.dart
@lrhn where do you see this strange test? Please make sure, that DEPS updated to the latest f05d5aee5930bfd487aedf832fbd7b832f502b15 commit

**Comment by lrhn** [comment]
Ah, yes. Now it's updated.

There is still a correct warning for this test because you are passing a positional parameter to a function expecting only named parameters.

**Comment by sgrekhov** [comment]
Indeed. Thank you. Fixed.
