### ISSUE TITLE
Missing support files for LibTest/collection/... tests

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#72]
The tests 
 co19/LibTest/collection/ListBase/ListBase_class_A01_t01: RuntimeError
  co19/LibTest/collection/ListBase/ListBase_class_A01_t02: RuntimeError
  co19/LibTest/collection/ListBase/listToString_A01_t01: RuntimeError
  co19/LibTest/collection/ListBase/listToString_A02_t01: RuntimeError
  co19/LibTest/collection/MapBase/MapBase_class_A01_t01: RuntimeError
  co19/LibTest/collection/MapMixin/MapMixin_class_A01_t01: RuntimeError

fail on all platforms because they import non-existent files, like
"mapbase.lib.dart"
and 
 "listbase.lib.dart"

**Comment by sgrekhov** [comment]
@whesse which version of co19 test do you use? There are mentioned support filer in the co19 repository. Please see
https://github.com/dart-lang/co19/tree/master/LibTest/collection/MapBase
https://github.com/dart-lang/co19/tree/master/LibTest/collection/ListBase

Therefore all of the test mentioned here work for me

**Comment by whesse** [comment]
The problem is the capitalization.  They are failing on linux, passing on Mac and Windows, because the import statements say "import "listbase.lib.dart";"  and the file is named "ListBase.lib.dart"

**Comment by sgrekhov** [comment]
Thank you! Fixed.  9ba5769

**Comment by whesse** [comment]
That commit deleted one of the files instead of renaming it.

**Comment by sgrekhov** [comment]
Sorry, it was accidentally. 3139f059a685db890d91df767f32d2b678708999
