### ISSUE TITLE
co19/LanguageFeatures/nnbd/flow-analysis/reachability_break/continue_* test incompletely specified feature

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#728]
See https://github.com/dart-lang/sdk/issues/42232 for more details.
@leafpetersen @eernstg We need to make a decision what to do in the spec, implementation, and tests.

**Comment by eernstg** [comment]
@scheglov, @leafpetersen Please take a look at the email 'Flow analysis tests', Jun 10.

**Comment by sgrekhov** [comment]
Seems that the issue was resolved. Closing this
