### ISSUE TITLE
Update pingInterval_A01_t01.test

### ISSUE THREAD

**Issue by zichangg** [dart-lang/co19#733]
I'm working on a fix on `toString()` method of class `Duration`. https://dart-review.googlesource.com/c/sdk/+/151163/

It basically says the `toString()` should follow `HH:MM:SS.mmmmmm` format.

Both pingInterval_A01_t01 and pingInterval_A02_t01 need to be updated. 

https://github.com/dart-lang/co19/blob/37e36e23711c2327d9e2a95ce403367ab31d88e3/LibTest/io/WebSocket/pingInterval_A01_t01.dart#L27

The string should will be changed to "00:00:00.100000" once the cl lands. The compatible change is to check whether output string contains "100000".

**Comment by sgrekhov** [comment]
I'll do the change in the tests once cl lands

**Comment by zichangg** [comment]
@sgrekhov Thanks! I need to hold it for a couple of days(nnbd folder is merging). I'll ping here if it lands.

**Comment by zichangg** [comment]
A friendly ping!

**Comment by davidmorgan** [comment]
Had to revert the change as it breaks some google internal tests https://dart-review.googlesource.com/c/sdk/+/151848

I suggest updating the test to not check the prefix, i.e. to only check for "100000", so it's compatible with both versions. Thanks :)

**Comment by davidmorgan** [comment]
Thanks :)
