### ISSUE TITLE
Isolate tests with intentional type errors are missing @static-warning

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#74]
Many Isolate tests are failing when run on the analyzer, because they contain intentional type errors, and are missing the @static-warning annotation that should be put on tests that will give static warnings.

Here is a list of Isolate tests failing on the analyzer.  It should be checked which of them have intentional type errors, or other errors, and the static warning annotation added to them:

  co19/LibTest/isolate/Isolate/spawnUri_A02_t01: StaticWarning
  co19/LibTest/isolate/Isolate/spawnUri_A02_t06: StaticWarning
  co19/LibTest/isolate/Isolate/spawnUri_A02_t07: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A02_t04: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A02_t05: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A02_t06: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A02_t07: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A04_t01: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A04_t02: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A04_t03: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A04_t04: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A04_t05: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A05_t03: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t01: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t02: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t03: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t04: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t05: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t06: StaticWarning
  co19/LibTest/isolate/Isolate/spawn_A06_t07: StaticWarning

**Comment by sgrekhov** [comment]
Fixed. See bc94595
