### ISSUE TITLE
co19/LibTest/isolate/Isolate/spawn_A04_t03 is trying to ping a possibly dead isolate

### ISSUE THREAD

**Issue by floitschG** [dart-lang/co19#76]
The `spawn_A04_t03` test is doing a ping after every message it receives.
However, once it receives the 'finish' message it cannot assume that the other isolate is still alive. After all, that isolate has no open ports anymore and is allowed to shut down.

An easy work-around is to only ping when the 'data' is not 'finish':
`if (data != "finish") Expect.equals("ping", await ping(isolate, "ping", THREE_SECONDS));`

Also, the test is taking a long time, since it waits 2 seconds before sending the 'finish' message. Unfortunately, because of the ping, it's not possible to decrease that duration significantly.

If the 'ping' is important, then it would be better to shut down the isolate explicitly with a message. This would eliminate all possible flakiness and we could reduce the time for the 'finish' message.

**Comment by alsemenov** [comment]
The idea of the test is to check that the isolate is still alive after its entry function encounter a runtime error. This test focuses on isolate that only sends events. There are two kinds of checks:
  * isolate should respond to ping requests even after runtime error
  * all scheduled tasks should be executed as planned

I think both checks are essential.
Removing the ping check will make the test weaker.
