### ISSUE TITLE
Three tests have dart2js compile time errors - probably test errors

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#77]
The tests  

 co19/Language/Variables/final_t01/01: CompileTimeError
  co19/Language/Variables/final_t02/01: CompileTimeError
  co19/LibTest/isolate/Isolate/spawn_A03_t01: CompileTimeError

all fail with compilation error on dart2js.
Please make sure these tests don't have errors, and if they are correct, file a dart2js or html issue about them.

**Comment by whesse** [comment]
spawn_A03_t01 uses "exit()", which is not declared when running in a browser.  Please rewrite without "exit".

**Comment by sgrekhov** [comment]
co19/Language/Variables/final_t01
co19/Language/Variables/final_t02
Tests are ok, it's dart2js issue. Please see https://github.com/dart-lang/sdk/issues/27226
I think the best way is simply to turn off these two tests in .status files for now. There'll be no this issue in a strong mode. In a strong mode there'll be compile error in analyzer, vm and dart2js, so we've marked it as @compile-error in our strong mode branch

**Comment by alsemenov** [comment]
I also reported issue https://github.com/dart-lang/sdk/issues/27227 to be able to simplify design of co19/LibTest/isolate/Isolate/spawn_A03_t01
