### ISSUE TITLE
Question or bug? Some Future flattening tests don't have a failure case?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#778]
It looks like some of the NNBD Future flattening tests catch errors but don't have any expectations that would fail if the errors don't ever get thrown in the first place.

See:
https://github.com/dart-lang/co19/blob/b17528c6b176856535638840d1ab48f087b8960a/LanguageFeatures/nnbd/future_flattening_A01_t42.dart#L42-L44

If I understand this test correctly it wants an error to be thrown in the async method but if it's not thrown it doesn't look like the test will fail. There are multiple tests with this pattern. Is there a failure case missing?

**Comment by iarkh** [comment]
This is a common practice in co19 testsuite, for example, just grep `asyncEnd()` globally there - most tests look in the similar way.

`asyncStart()` function increases `_asyncCounter` variable and then `asyncEnd()` decreases it.

If finally `_asyncCounter` is not zero, the test is treated as failed.

So in the test example above `_asynСounter` will be 1 (and so the test fails) if exception is not thrown.

**Comment by nshahan** [comment]
I'm just not seeing a consistent failure on all of our backends. If I remove the call to `asyncEnd()` and run the test some backends will report a failure with no error message. Other report no failure and pass the test. 

Looking at the test and the async_utils.dart library I don't see what would cause the test to fail if `_asyncCounter` is not zero. Can you point me to where that is so I can figure out why some of our backends are not performing the check?

**Comment by iarkh** [comment]
Oh, seems like you are correct.
I'll re-check the tests. 
Please sorry for the inconvenience!
