### ISSUE TITLE
LibTest/typed_data/Float32x4List/reduce_A01_t01 is incorrectly typed.

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/co19#78]
```dart
checkConst(list, expected) {
  var l = new Float32x4List.fromList(list);
  var res = l.reduce((prev, cur) => 1);   /// Incorrect to return 1 here, it must be a Float32x4
  Expect.equals(expected, res);
}
```

**Comment by rakudrama** [comment]
Same problem with lastWhere_A02_t01.dart - the orElse parameter on Iterable must return E.

**Comment by sgrekhov** [comment]
@rakudrama how do you get the issue? These two tests work well for me. Tested on dart2js (v 1.20) under windows x64

**Comment by sgrekhov** [comment]
Fixed. d741038414d0a2447e130d3866f4f72c8d9e106b
