### ISSUE TITLE
Renaming problem in Libraries_and_Scripts/URIs

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#8]
The tests in Language/Libraries_and_Scripts/URIs/syntax*
need the references to library1.dart and part.dart to be corrected.

Language/Libraries_and_Scripts/URIs/syntax_t04: RuntimeError
Language/Libraries_and_Scripts/URIs/syntax_t05: RuntimeError
Language/Libraries_and_Scripts/URIs/syntax_t09: RuntimeError
Language/Libraries_and_Scripts/URIs/syntax_t10: RuntimeError
Language/Libraries_and_Scripts/URIs/syntax_t14: RuntimeError
Language/Libraries_and_Scripts/URIs/syntax_t15: RuntimeError

**Comment by alsemenov** [comment]
Fixed with comit 1d96fbbf94c534c9076f90bd4ebce6226169da48
