### ISSUE TITLE
Stream.take(0) doesn't forward errors any more.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/co19#81]
We are fixing a bug in `Stream.take` with a zero count that made it not cancel the subscription immediately. It should, and now it does, which also means that two tests are now failing:

- LibTest/async/Stream/take_A01_t02
- LibTest/isolate/ReceivePort/take_A01_t02

Both seem to assume that `.take(0)` will still propagate an error event, which it now won't.

The description of `Stream.take` was a little confusing, and will also be cleaned up. It did say that the subscription was cancelled after [count] events had been received, which is now true even for `count == 0`.

**Comment by alsemenov** [comment]
I think current description is still confusing:
> Forwards the first n data events of this stream, and all error events, to the returned stream, and ends with a done event.

I conclude that error events are received without any restrictions.
If I understand correctly, the `.take(0) ` works as follows:
```dart
StreamSubscription ss = stream.listen(...);
ss.cancel();
```
Is there a possibility, that between these lines the stream generates some error (in another thread for example) and this error is received?

**Comment by lrhn** [comment]
The current documentation on the bleeding edge branch now says:
> Provides at most the first [count] data events of this stream.
>
> Forwards all events of this stream to the returned stream
> until [count] data events have been forwarded or this stream ends,
> then ends the returned stream with a done event.
>
> If this stream produces fewer than [count] data events before it's done,
> so will the returned stream.
>
> Starts listening to this stream when the returned stream is listened to
> and stops listening when the first [count] data events have been received.
>
> This means that if this is a single-subscription (non-broadcast) streams
> it cannot be reused after the returned stream has been listened to.
>
> If this is a broadcast stream, the returned stream is a broadcast stream.
> In that case, the events are only counted from the time
> the returned stream is listened to.

I believe it will be published with the 1.21 release.
