### ISSUE TITLE
Timing-dependent failure in LibTest/isolate/Isolate/spawnUri_A01_t07

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/co19#83]
This test sometimes fails if the main isolate exits before the other isolate gets to print the success status message expected by the test harness for async tests (e.g. debug mode slow because of assertions)

Maybe the main isolate should explicitly wait for the other isolate to finish? Alternatively, give the other isolate more time to finish.

**Comment by alsemenov** [comment]
Adding synchronization between the isolates will unnecessary complicate the test.
Let's increase the time to finish first.
