### ISSUE TITLE
Inferring void as a function expression return type

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#838]
@eernstg there are also breakages in Flutter. Let me know if it looks like a my bug.

The spec [was changed](https://github.com/dart-lang/language/pull/1092).
[The analyzer change](https://dart-review.googlesource.com/c/sdk/+/154620) breaks following tests:

```
co19_2/LibTest/io/RawDatagramSocket/asBroadcastStream_A02_t02
co19_2/LibTest/io/RawDatagramSocket/asBroadcastStream_A03_t01
co19_2/LibTest/io/RawDatagramSocket/asyncExpand_A01_t01
co19_2/LibTest/io/RawDatagramSocket/asyncMap_A01_t01
co19_2/LibTest/io/RawDatagramSocket/expand_A01_t01
co19_2/LibTest/io/RawDatagramSocket/expand_A02_t01
co19_2/LibTest/io/RawDatagramSocket/expand_A02_t02
```

**Comment by eernstg** [comment]
There should not be any new behaviors without null-safety, cf. https://github.com/dart-lang/language/pull/1092#issuecomment-659232238.
