### ISSUE TITLE
Library name conflict error eliminated

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#853]
Cf. https://github.com/dart-lang/sdk/issues/42481#issuecomment-660991204, the rule that it is an error if two distinct libraries with the same non-empty name are imported or exported is now gone.

So the test `co19/Language/Libraries_and_Scripts/Imports/library_name_t01.dart` must be modified to expect no errors.

**Comment by sgrekhov** [comment]
This is a duplicate of #837 which is already fixed. Closing this issue
