### ISSUE TITLE
Renamed files during the migration of LibTest/async/*?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/co19#886]
It seems like some files were renamed during the migration of `LibTest/async/StreamContoller/*`. We are running scripts on our test results to match failures against the existing failures in the legacy version of the test suite before migration. When the names don't match failures show up as a new failure when they should be a regression (if previously passing) or ignored (if previously failing).

I recognize that sometimes new files need to be created during the migration and that is OK, but if a test already existed before migration it helps that a migrated version of the test gets created with the same name.

Can someone sort out what tests were the source of the following migrated tests and renamed the migrated version to match? It doesn't look like there is a straightforward consistent mapping on all the new names. I gathered some that are confusing me but there could be more throughout the async test suite that need renaming.

```
LibTest/async/StreamController/StreamController.broadcast_A*_t*.dart
LibTest/async/StreamController/StreamController.broadcast_Stream_all_A*_t*.dart
LibTest/async/StreamController/StreamController.broadcast_Stream_all_A*_t*.dart
LibTest/async/StreamController/stream_all_A*_t*.dart
LibTest/async/Stream/Stream.periodic_all_t*.dart
LibTest/async/Stream/Stream.fromIterable_all_t*.dart
LibTest/async/Stream/Stream.fromFutures_all_t*.dart
```

cc @eernstg 

Please excuse this request if the renaming was expected or already documented somewhere.

**Comment by eernstg** [comment]
Thanks, @sgrekhov.

**Comment by sgrekhov** [comment]
@nshahan, I renamed the test that runs bunch of the other test. This bunch of tests usually either tests inherited from superclass  either tests all methods of the current class (create an instance by calling different constructors and then call all of the member tests). So, I renamed them to separate them from other tests. Now they have '_inherited_' or '_all_' in the name. I'm very sorry if this renaming made problems for you.

Below is the full list of the renamed tests

Old name | New name
-- | --
LibTest/async/Stream/Stream.fromFutures_A04_t01.dart | LibTest/async/Stream/Stream.fromFutures_all_t01.dart
LibTest/async/Stream/Stream.fromFutures_A04_t02.dart | LibTest/async/Stream/Stream.fromFutures_all_t02.dart
LibTest/async/Stream/Stream.fromFutures_A04_t03.dart | LibTest/async/Stream/Stream.fromFutures_all_t03.dart
LibTest/async/Stream/Stream.fromIterable_A03_t01.dart | LibTest/async/Stream/Stream.fromIterable_all_t01.dart
LibTest/async/Stream/Stream.fromIterable_A03_t02.dart | LibTest/async/Stream/Stream.fromIterable_all_t02.dart
LibTest/async/Stream/Stream.periodic_A04_t01.dart | LibTest/async/Stream/Stream.periodic_all_t01.dart
LibTest/async/Stream/Stream.periodic_A04_t02.dart | LibTest/async/Stream/Stream.periodic_all_t02.dart
LibTest/async/StreamController/stream_A02_t01.dart | LibTest/async/StreamController/stream_all_A01_t01.dart
LibTest/async/StreamController/stream_A02_t02.dart | LibTest/async/StreamController/stream_all_A01_t02.dart
LibTest/async/StreamController/stream_A02_t03.dart | LibTest/async/StreamController/stream_all_A01_t03.dart
LibTest/async/StreamController/stream_A03_t01.dart | LibTest/async/StreamController/stream_all_A02_t01.dart
LibTest/async/StreamController/stream_A03_t02.dart | LibTest/async/StreamController/stream_all_A02_t02.dart
LibTest/async/StreamController/stream_A03_t03.dart | LibTest/async/StreamController/stream_all_A02_t03.dart
LibTest/async/StreamController/StreamController.broadcast_A09_t01.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t01.dart
LibTest/async/StreamController/StreamController.broadcast_A09_t02.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t02.dart
LibTest/async/StreamController/StreamController.broadcast_A09_t03.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A01_t03.dart
LibTest/async/StreamController/StreamController.broadcast_A10_t01.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t01.dart
LibTest/async/StreamController/StreamController.broadcast_A10_t02.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t01.dart
LibTest/async/StreamController/StreamController.broadcast_A10_t03.dart | LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t01.dart
LibTest/async/Zone/ROOT_A01_t01.dart | LibTest/async/Zone/root_A01_t01.dart
  |  
LibTest/core/Map/allTests_A01_t01.dart | LibTest/core/Map/Map_all_t01.dart
LibTest/core/Set/inherited_tests.dart | LibTest/core/Set/Set_inherited_t01.dart
LibTest/core/List/List_class_A01_t01.dart | LibTest/core/List/List_all_t01.dart
LibTest/core/List/List_class_A01_t02.dart | LibTest/core/List/List_all_t02.dart
LibTest/core/List/List_class_A01_t03.dart | LibTest/core/List/List_all_t03.dart
LibTest/core/List/List_class_A01_t04.dart | LibTest/core/List/List_all_t04.dart
LibTest/core/List/List_class_A01_t05.dart | LibTest/core/List/List_all_t05.dart
LibTest/core/List/Iterable_A01_t01.dart | LibTest/core/List/List_inherited_t01.dart
LibTest/core/Object/Object_class_A01_t01.dart | LibTest/core/Object/Object_all_t01.dart
LibTest/core/RangeError/RangeError_class_A01_t01.dart | LibTest/core/RangeError/RangeError_all_t01.dart
  |  
LibTest/collection/DoubleLinkedQueue/DoubleLinkedQueue_A01_t01_class.dart | LibTest/collection/DoubleLinkedQueue/DoubleLinkedQueue_inherited_A01_t01.dart
LibTest/collection/HashMap/HashMap_class_A01_t01.dart | LibTest/collection/HashMap/HashMap_inherited_A01_t01.dart
LibTest/collection/Queue/Queue_class_A01_t01.dart | LibTest/collection/Queue/Queue_all_A01_t01.dart
LibTest/collection/LinkedHashMap/LinkedHashMap_class_A01_t01.dart | LibTest/collection/LinkedHashMap/LinkedHashMap_inherited_t01.dart
LibTest/collection/IterableBase/IterableBase_class_A01_t02.dart | LibTest/collection/IterableBase/IterableBase_inherited_t01.dart
LibTest/collection/IterableMixin/IterableMixin_class_A02_t01.dart | LibTest/collection/IterableMixin/IterableMixin_inherited_t01.dart
LibTest/collection/HashSet/HashSet_class_A01_t01.dart | LibTest/collection/HashSet/HashSet_inherited_A01_t01.dart
LibTest/collection/LinkedHashSet/LinkedHashSet_class_A01_t01.dart | LibTest/collection/LinkedHashSet/LinkedHashSet_inherited_A01_t01.dart
LibTest/collection/ListQueue/ListQueue_class_A01_t01.dart | LibTest/collection/ListQueue/ListQueue_all_t01.dart
LibTest/collection/MapBase/MapBase_class_A01_t01.dart | LibTest/collection/MapBase/MapBase_inherited_t01.dart
LibTest/collection/MapMixin/MapMixin_class_A01_t01.dart | LibTest/collection/MapMixin/MapMixin_inherited_t01.dart
LibTest/collection/MapView/MapView_class_A01_t01.dart | LibTest/collection/MapView/MapView_inherited_t01.dart
LibTest/collection/SetBase/SetBase_class_A01_t01.dart | LibTest/collection/SetBase/SetBase_inherited_t01.dart
LibTest/collection/SetMixin/SetMixin_class_A01_t01.dart | LibTest/collection/SetMixin/SetMixin_inherited_t01.dart
LibTest/collection/SplayTreeMap/inherited_tests_t01.dart | LibTest/collection/SplayTreeMap/SplayTreeMap_inherited_t01.dart

**Comment by nshahan** [comment]
@athomas Is this mapping between legacy and migrated test names something that can be handled by the query we are using to track null safety progress?

**Comment by athomas** [comment]
Yes, we can handle this mapping.

Something odd I noticed while looking at our test data is that we seem to not have been running these two tests:
```
LibTest/core/Set/inherited_tests
LibTest/collection/DoubleLinkedQueue/DoubleLinkedQueue_A01_t01_class
```

But we are running their migrated counterparts.

**Comment by nshahan** [comment]
@sgrekhov I just want to confirm these tests. Are they new or were they renamed in the migration?

```
LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t03
LibTest/async/Stream/Stream.periodic_all_t03
```

**Comment by sgrekhov** [comment]
@nshahan 
For the `LibTest/async/StreamController/StreamController.broadcast_Stream_all_A02_t03` the old name is `LibTest/async/StreamController/StreamController.broadcast_A10_t03`.
`LibTest/async/Stream/Stream.periodic_all_t03` is the new one
Sorry again that the renaming made troubles for you
