### ISSUE TITLE
Syntax tests contain illegal uses of abstract fields.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#889]
The following tests:
- Language/Variables/syntax_t15.dart
- Language/Variables/syntax_t18.dart

attempt to verify that the keyword `abstract` is permitted in a variable declaration using syntax like this:
```dart
class C {
  abstract var x = 1;
}
```

This doen't work because:
- Abstract fields must be in an abstract class
- Abstract fields must not be initialized.

**Comment by sgrekhov** [comment]
@stereotype441 thank you. I fixed the tests. Please also see
https://github.com/dart-lang/sdk/issues/42979
https://github.com/dart-lang/sdk/issues/42980
https://github.com/dart-lang/sdk/issues/42981

**Comment by stereotype441** [comment]
@sgrekhov thanks for those bug reports!  I'm still working on the implementation of external and abstract fields in the analyzer.  I'll make sure my implementation work fixes those bugs.
