### ISSUE TITLE
Remove obsolete tests related to the use of super in mixins

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#9]
These tests should be deleted, now that the use of super is allowed in mixins and now that mixins may extend a subclass of Object:

Language/09_Mixins/09_Mixins_A01_t01
Language/09_Mixins/09_Mixins_A03_t01

**Comment by sgrekhov** [comment]
The latest version of Dart specification (http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) still contains the following statement (12 Mixins, page 43):

It is a compile-time error if a declared or derived mixin refers to super.
It is a compile-time error if a declared or derived mixin explicitly declares a
constructor. It is a compile-time error if a mixin is derived from a class whose
superclass is not Object.

Is newer version of the spec available?

**Comment by crelier** [comment]
Seth, will a new spec be available with 1.13? Can you provide a link here? Thanks.

**Comment by sethladd** [comment]
The spec we're working off of is https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Accepted/0034%20-%20Less%20Restricted%20Mixins/proposal.md

**Comment by crelier** [comment]
Thanks Seth. The tests are now marked as "Skip" for all implementations. I think it is fine to remove them now.

**Comment by sethladd** [comment]
I don't think we want to Skip them for all implementations quite yet... dart2js doesn't implement this feature, for example.

**Comment by crelier** [comment]
https://codereview.chromium.org/1383923002/ updated many tests to reflect the new behavior and marked them as failing for dart2js where necessary, with a reference to the dart2js issue.
There was no point in putting effort in maintaining several versions of some tests, because dart2js is running behind. I just applied the same reasoning here. It's true that skipping selectively is easier than maintaining several versions, but it is still throw away work. Do we know when dart2js is going to catch up? For 1.13?

**Comment by sethladd** [comment]
dart2js won't have this feature implemented for 1.13. But I believe they intend to do it soon.

cc @sigmundch

**Comment by sigmundch** [comment]
correct - we plan to start on it this quarter, it is not planned for 1.13.

**Comment by sgrekhov** [comment]
Obsolete tests removed from co19 tests. See https://github.com/dart-lang/co19/commit/ff63456159150ce88c500584c827a05646c64b12
