### ISSUE TITLE
U+180E is not always considered whitespace.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/co19#90]
The U+180E character is not considers white-space (category Zs) by recent Unicode versions, and browsers are following the change. Firefox v53 has changed behavior now, Chrome did earlier.

That means that tests cannot assume that U+180E is matched by the RegExp pattern `\s`.
The LibTest/core/RegExp/Pattern_semantics/splitQueryString_A02_t01 test is now failing when compiled by dart2js and run on Firefox.
Also affects: LibTest/core/RegExp/Pattern_semantics/firstMatch_CharacterClassEscape_A03_t01

**Comment by sgrekhov** [comment]
Fixed in main and strong-mode branches
