### ISSUE TITLE
flawed nextRand() in LibTest/core/Duration

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/co19#91]
This pseudo-random number generator has flaws which limit coverage:

```
int seed=1234567;
int nextRand() {
  seed = seed * 199933 + 11;
  return seed&127;
}
```

1. On the VM `seed` becomes a very large bigint number. On dart2js it rapidly becomes a number with zero as the low bits, and then infinity. So the VM and dart2js tests are not the same.
2. The returned value alternates between even and odd. Many tests call `nextRand` an even number of times. This means that some positions test only even values and other positions only odd values.

I suggest modifying the generator to truncate to smaller integers and incorporate feed-back from high bits and avoiding lowest bits to improve the quality of the 'randomness'.

```
int seed=1234567;
int nextRand() {
  seed = 0x3fffffff & ((seed >> 17) + seed * 199933  + 11);
  return (seed >> 5) & 127;
}
```

You will probably (p=100/128) find that the **div** test fails for q==0.  I suggest adding 1 to the quotient:

```
check(nextRand(), nextRand(), nextRand(), nextRand(), nextRand(), nextRand());
```
--->
```
check(nextRand(), nextRand(), nextRand(), nextRand(), nextRand(), nextRand() + 1);
```

Also review other tests for similar flawed test sequences.

**Comment by sgrekhov** [comment]
Fixed in both master and strong-mode branches
