### ISSUE TITLE
Test external and abstract variables

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#912]
Cf. the [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/implementation-plan.md), the addition of external and abstract variables to Dart may require some updates.

In particular, there should be tests for abstract and external variables (feature specification [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/feature-specification.md)), and other tests may need to be adjusted (because it is not a syntax error any more to have `external` or `abstract` in a few locations).

**Comment by sgrekhov** [comment]
@eernstg does the change affect co19_2 tests?

**Comment by eernstg** [comment]
No, external and abstract variables are enabled when and only when null safety is enabled.
