### ISSUE TITLE
Fix computed-style-border-image_t01 expectation

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#92]
The co19 test LayoutTests/fast/css/getComputedStyle/computed-style-border-image_t01

expectation should be 
<url("dummy://IntentionallyMissingFile.png") 12 11 / 1 / 0px repeat stretch>

instead of 

<url(dummy://IntentionallyMissingFile.png) 12 11 / 1 / 0px repeat stretch>

**Comment by sgrekhov** [comment]
Fixed in both master and strong-mode branches
