### ISSUE TITLE
New static analysis of `main`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#924]
The PR https://github.com/dart-lang/language/pull/1146 introduces a new section in the null-safety specification about the static requirements on the `main` function. That section will replace the section `Scripts` in the language specification when null safety is in a stable release, so a comparison between the 'Scripts' section in the language specification and the new section in the null-safety specification may be helpful. We need tests for this new behavior.

**Comment by sgrekhov** [comment]
@eernstg are there implementation issues for the new static analysis of main?

**Comment by sgrekhov** [comment]
@eernstg, is the following an error?
```dart
library main;
...
```
And the second one
```dart
import "some_lib.dart" as main;
...
```

**Comment by eernstg** [comment]
> implementation issues

No, the change was supposed to make the spec track the implementations more closely, not the other way around.

> `library main;`

That is not an error, a libraryName does not introduce its name into any scope.

> `import "some_lib.dart" as main;`

That is also allowed: When `main` is an import prefix it is not exported. It is only an exported `main` which is subject to restrictions.

**Comment by sgrekhov** [comment]
> `import "some_lib.dart" as main;`
> 
> That is also allowed: When main is an import prefix it is not exported. It is only an exported main which is subject to restrictions.

@eernstg, in this case we'll have an error if library has `main()` function
```dart
import "some_lib.dart";
main() { // error - The name 'main' is already used as an import prefix and can't be used to name a top-level element.
}
```
Is this expected?
