### ISSUE TITLE
Left top rule should be reflected in tests

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/co19#936]
There's an upcoming [change](https://github.com/dart-lang/language/pull/1200) to the spec.  Running the tests on the implementation reveals two co19 test that needs updating.

* Line 40 in Language/Generics/typedef_A05_t04.dart needs to be changed to `t1(Object, dynamic);`:

https://github.com/dart-lang/co19/blob/ff08f2965b024a7003456deb6480170d566ace74/Language/Generics/typedef_A05_t04.dart#L40

* Similarly, line 40 in Language/Generics/typedef_A05_t05.dart needs to be changed to `t1(Object, t: null);`:

https://github.com/dart-lang/co19/blob/ff08f2965b024a7003456deb6480170d566ace74/Language/Generics/typedef_A05_t05.dart#L40

**Comment by stefantsov** [comment]
Lines 41 in both files should also be changed, both to the same value `t1(Object);`.

**Comment by sgrekhov** [comment]
Will do the change as soon as the change is landed

**Comment by sgrekhov** [comment]
@stefantsov the [change](https://github.com/dart-lang/language/pull/1200) mentioned in this issue is still not merged. But AFAIU from the context it is already implemented. So is it ok to change the tests now? Please confirm

**Comment by stefantsov** [comment]
Yes, I can confirm that the change is implemented for some time now, and both tests need to be updated in lines 40 and 41 as described above in order to Pass.
