### ISSUE TITLE
Set-literals/type_inference tests need an adjustment

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#937]
A null-safety related change:

The following tests need an adjustment, because they expect a least upper bound of several types to be `Object` in the case where one operand is a type variable with no bound. With null safety, the value of such a type variable can be a top type, so the outcome needs to be `Object?`. https://github.com/dart-lang/language/pull/1195 makes the corresponding adjustment to the specification.

- LanguageFeatures/Set-literals/type_inference_A20_t01
- LanguageFeatures/Set-literals/type_inference_A22_t01
- LanguageFeatures/Set-literals/type_inference_A22_t02
- LanguageFeatures/Set-literals/type_inference_A24_t01
- LanguageFeatures/Set-literals/type_inference_A24_t02

The tests need to expect `Object?` as the type argument in all cases where they currently expect `Object`, e.g., `Expect.isTrue(v is Set<Object?>)` in A20_t01.

It may be useful as well to call the test methods with type arguments that demonstrate that the old expectation could not be guaranteed. For instance, A20_t01 may use `C<int?>().test(null);` to demonstrate that the old expectation `is Set<Object>` would be unsound (if we actually managed to put that null into the set we would have a soundness violation). Similarly, it's perhaps more natural to check `Expect.isFalse(v is Set<int?>)` at the end, in order to reject a few more wrong outcomes.

**Comment by sgrekhov** [comment]
@eernstg please note, that updated tests start to fail on CFE. For example A20_t01 produces
```
Unhandled exception:
type 'Null' is not a subtype of type 'Object' of 'key'
#0      _CompactLinkedHashSet.add (dart:collection-patch/compact_hash.dart)
#1      C.test (file:///D:/work/Google/co19/LanguageFeatures/Set-literals/type_inference_A20_t01.dart)
#2      main (file:///D:/work/Google/co19/LanguageFeatures/Set-literals/type_inference_A20_t01.dart:33:13)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Process finished with exit code 255
```

**Comment by eernstg** [comment]
Yes, the spec change hasn't landed yet, and hence implementation hasn't started. If the enclosing directory hasn't been unskipped yet it would be useful to delay the unskipping until the spec has landed.

**Comment by sgrekhov** [comment]
These tests has been unskipped already. The'll fall after the next roll. Do we have anappropriate implementation issues for analyzer and CFE?

**Comment by eernstg** [comment]
I hope the spec update can be landed today, and then I can create implementation issues.
