### ISSUE TITLE
Tests need updating due to removal of "promotable via initialization" logic

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/co19#939]
In https://github.com/dart-lang/language/commit/b70bb3f90679eb1c67b7ee852e1322046b2e4777, the specification was changed so that assignments of the form `var x; x = value;` no longer trigger type promotion.  That change is being implemented in https://dart-review.googlesource.com/c/sdk/+/163681.

The following co19 tests need to be updated to no longer expect promotion:
```
co19/LanguageFeatures/nnbd/flow-analysis/promotion_via_initialization_A01_t01
co19/LanguageFeatures/nnbd/flow-analysis/promotion_via_initialization_A06_t01
```

**Comment by sgrekhov** [comment]
Will change the tests as soon as CL is merged
