### ISSUE TITLE
Fix expected output of co19 test multicol_t01

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/co19#94]
The co19 test LayoutTests/fast/css-intrinsic-dimensions/multicol_t01 has incorrect expected output in both dart2js and dartium please fix.

Expect.fail('Expected 330 for width, but got 1. ')

**Comment by sgrekhov** [comment]
This test was absolutely wrong. Setting columns property affects text only, not nested elements. Setting columns width set minimum desired width of the column, not the exact width. If widht of the parent element is less than width of all columns then columns are just ignored. Therefore this test was absolutely wrong. Deleted.
