### ISSUE TITLE
Update LanguageFeatures/Simple-bounds tests according to https://github.com/dart-lang/language/pull/1133

### ISSUE THREAD

**Issue by iarkh** [dart-lang/co19#942]
https://github.com/dart-lang/language/pull/1133 has been landed, and this means that any test that expects a compile-time error because of a failing i2b that is caused by a type variable which is invariant or unused should be changed to stop expecting that error. 

Simple-bounds tests should be updated accordingly.

**Comment by eernstg** [comment]
I added a bunch of comments on https://github.com/dart-lang/co19/commit/f07abdd3d496e7c8e4777aa6aeec9cd61265e6c4, having noted that several of the tests need to have their expectations adjsted.

**Comment by eernstg** [comment]
Correction (also mentioned in existing comment threads on the PR): Tests LanguageFeatures/Simple-bounds/static/typedef_l1_t04.dart and LanguageFeatures/Simple-bounds/static/typedef_l1_t14.dart are correct in f07abdd3d496e7c8e4777aa6aeec9cd61265e6c4.

**Comment by iarkh** [comment]
> Correction (also mentioned in existing comment threads on the PR): Tests LanguageFeatures/Simple-bounds/static/typedef_l1_t04.dart and LanguageFeatures/Simple-bounds/static/typedef_l1_t14.dart are correct in [f07abdd](https://github.com/dart-lang/co19/commit/f07abdd3d496e7c8e4777aa6aeec9cd61265e6c4) after all.

I'll go through new comments for https://github.com/dart-lang/co19/commit/f07abdd3d496e7c8e4777aa6aeec9cd61265e6c4 and check it again today. After this update the tests if still it's needed (maybe not)..

**Comment by eernstg** [comment]
Thanks!

**Comment by iarkh** [comment]
Just checked it once again and add a minor change, seems like the tests are OK now...
