### ISSUE TITLE
Disable certain tests on `main` for specific implementations

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#952]
Cf. https://github.com/dart-lang/sdk/issues/43584.

The specification of the constraints on a declaration named `main` which is used as a program entry point [allows each implementation to add its own constraints](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#the-main-function):

> Implementations are free to impose any additional restrictions on the signature of `main`.

For instance, `dart2js` may reject `void main([List<String> args]) {...}` as an entry point.

Tests on `main` should aim to cover the signatures indicated in the specification, but each of those tests may fail on a specific tool, because it violates such an implementation specific constraint.

In that situation, the test should be disabled (for instance, using `SkipByDesign` in a status file, with a reference to this issue) for the relevant implementations.

**Comment by sgrekhov** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/167560
