### ISSUE TITLE
Some multi-tests can be automatically converted to static error framework

### ISSUE THREAD

**Issue by karlklose** [dart-lang/co19#953]
We have a script that converts multi-tests to the static error framework automatically, given that the new test gives the exact same errors as all the multi-test subtests combined.

I have run this script on passing co19 tests and have come up with 254 tests that can be converted.

I have uploaded the change here: https://github.com/karlklose/co19/tree/convert-multitest

There is one issue that is still unclear to me: for the multi-test '/none' (or 'OK') cases, a positive test is generated. The question is whether these should be added and where. For now, these tests have been added under the directory positive_tests with the same name as the text.

**Comment by sgrekhov** [comment]
Comments added to https://github.com/karlklose/co19/commit/9e5d5f996ccb8e53b47a4cc5f6dc640a0e536ece  commit

**Comment by sgrekhov** [comment]
@karlklose as for the `/none` positive tests cases I think we don't need it. `/none` is a sanitizer, if there is an error outside of lines marked as `//# 0X: ...` then test with `//# 01: compile -time error` will give a false positive result (there will be false compile error). And `/none` case catches it. In case of the new syntax if there is aa error in a wrong place it will be reported and test will fail. So we don't need a special positive tests for the `/none`

**Comment by karlklose** [comment]
I have created a pull request for the change at https://github.com/dart-lang/co19/pull/957

**Comment by karlklose** [comment]
Something went wrong with the rebase, I will open a new PR when I have fixed it.

**Comment by karlklose** [comment]
Updated PR in https://github.com/dart-lang/co19/pull/958

**Comment by sgrekhov** [comment]
PR has been merged. Thank you!
