### ISSUE TITLE
co19_2/LibTest/html/Element/isContentEditable_A01_t01 RuntimeError (expected Pass)

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/co19#959]
This test seems flaky.
@athomas Did something change with the test infrastructure?

The tests
```
co19_2/LibTest/html/Element/isContentEditable_A01_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-mac-safari
```

**Comment by sgrekhov** [comment]
@rakudrama how exactly this test fails on safary? Do you have failure logs?

**Comment by athomas** [comment]
https://dart-ci.appspot.com/log/any/dart2js-mac-safari/11891/co19_2/LibTest/html/Element/isContentEditable_A01_t01
