### ISSUE TITLE
Rename null safety execution modes

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#960]
It would be great if you could adjust the terminology in the following about 75 locations in the master branch:

We should use the standard terminology in relation to the execution modes `--sound-null-safety` and `--no-sound-null-safety`. In particular `isWeakMode` and `isStrongMode` should be renamed to `hasUnsoundNullSafety` and `hasSoundNullSafety`.

Apart from that, there are a number of occurrences of `In strong checking mode, ...` (could be `With sound null safety, ...`). Similarly for `in strong checking` (plus `mode` on the next line), `in weak mode` (could be `with unsound null safety`), `in a weak mode`, `in strong mode`. Plus a few extras:

```
Utils/lang_feature_check.dart:31:// Weak/strong mode flags
LibTest/async/Future/catchError_A07_t01.dart:27:    // In strong mode, registering incompatible callback is synchronous error,
LibTest/isolate/Isolate/spawn_A02_t04.dart:25: * Future instance completes with error otherwise. In strong mode compile
LibTest/isolate/Isolate/spawn_A02_t05.dart:26: * strong mode
LibTest/typed_data/Float32List/toList_A02_t02.dart:23:  if (isStrongMode) {
Utils/lang_feature_check.dart:31:// Weak/strong mode flags
Language/Interfaces/Superinterfaces/Inheritance_and_Overriding/inheritance_t07.dart:28: * @description Checks there is a compile error in a strong mode if non-abstract
Language/Types/Parameterized_Types/malbounded_t07.dart:13: * @description Checks that in strong mode, it is a compile error if
```

**Comment by sgrekhov** [comment]
@eernstg please note that [NNBD specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) still uses `In weak checking mode` and `In striong checking mode` terminology

**Comment by eernstg** [comment]
Thanks! We'll take that later.
