### ISSUE TITLE
Wrongly specified bound in test LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21

### ISSUE THREAD

**Issue by crelier** [dart-lang/co19#965]
The intent of the test co19/LanguageFeatures/nnbd/Least-greatest-closure/typedef/typedef_dynamic_t21 is to verify that the inferred bound is `Object?`. However, the test specifies explicitly the bound to be type parameter `X`. The typedef is invoked without type arguments, therefore implicitly passing `dynamic`.

The declaration should be:
```
typedef check<X> = void Function<X1>() Function();
```

Note that this issue was uncovered after fixing issue https://github.com/dart-lang/sdk/issues/44136

**Comment by iarkh** [comment]
Fixed in commit: https://github.com/dart-lang/co19/commit/61d196933cb2de31a667369b98c96883b6411db6
