### ISSUE TITLE
Broken tests on windows because of shared certificates

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#966]
On Windows, some tests are relying on `OtherResources` to pull in checked-in certificates from a parent directory. The test runner normally places resources in a test specific directory but because the relative path contains a `..`, the resources will be placed outside of the test specific directory and are shared between tests. This causes infra failures on windows where the overwrite fails: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8863399471359562464/+/steps/co19_nnbd_tests_in_strong_mode_shard_10/0/logs/task_stdout_stderr:_co19_nnbd_tests_in_strong_mode_shard_10/0

Discovered in the roll https://dart-review.googlesource.com/c/sdk/+/172501.

Affected tests:
https://github.com/dart-lang/co19/search?q=%2Fcertificates

Proposed solution:
Move the certificates directory to LibTest/io/RawSecureServerSocket/certificates, where all the tests needing them are to remove the need for a relative path with `..`.

**Comment by sgrekhov** [comment]
@athomas I'd suggest to abandon https://dart-review.googlesource.com/c/sdk/+/172501 and do a new roll of co19 test
