### ISSUE TITLE
co19/LibTest/io/RandomAccessFile/lock_A03_t03 is failing on Windows

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/co19#977]
`co19/LibTest/io/RandomAccessFile/lock_A03_t03` is failing on [dartkp-weak-asserts-win-release-x64](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8860784068338823584/+/steps/test_results/0/logs/new_test_failures__logs_/0).

```
stdout:
unittest-suite-wait-for-done
   expected:
OS Error:
Client failed, exit code 0
  stdout:
LOCK SUCCEEDED
```

It appears to be isolate to the Windows bot, and I'm not able to replicate it locally on Linux.

I've gone through the CLs in the failing range, but have not been able to find anything that looks like a likely culprit.

**Comment by sgrekhov** [comment]
@cskau-g it's a known issue on Windows. Please see https://github.com/dart-lang/sdk/issues/31557 for details. No anything wrong with the test. Closing this issue
