### ISSUE TITLE
Non-function type aliases and nullability

### ISSUE THREAD

**Issue by scheglov** [dart-lang/co19#988]
1. co19/src/LanguageFeatures/nnbd/type-aliases/syntax_A03_t02.dart
2. co19/src/LanguageFeatures/nnbd/type-aliases/syntax_A06_t02.dart
3. co19/src/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t02.dart
4. co19/src/LanguageFeatures/nnbd/type-aliases/extension_method_resolution_A01_t06.dart

  In these tests `c = new C()` promotes `c` from `C?` to non-nullable `C`, so using `?` is a warning.

**Comment by scheglov** [comment]
I still see `co19/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t02` failing because of warnings, e.g.
```
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=nonfunction-type-aliases --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --format=machine --no-hints /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t02.dart

unexpected analysis errors:
In tests/co19/src/LanguageFeatures/nnbd/type-aliases/null_aware_operator_A17_t02.dart:
- Line 44, column 20: STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR
  The receiver can't be null, so the null-aware operator '?..' is unnecessary.

- Line 49, column 20: STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR
  The receiver can't be null, so the null-aware operator '?..' is unnecessary.
```

I see that the test marks these lines with `/// static type warning`, but it seems still keeps the test failing. Do these comments do something? Are they supported by `pkg/testing`? @eernstg @munificent

**Comment by sgrekhov** [comment]
@scheglov this is an error in the test. The correct expectstion in this case is
` // ^^^`
`// [analyzer] STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR`
We'll fix it, thank you

**Comment by eernstg** [comment]
@scheglov wrote:
> the test marks these lines with `/// static type warning`, but it seems still keeps the test failing

I believe @sgrekhov has already resolved everything, but here's my understanding of the situation: Warnings _are_ supported by the test runner today, using the standard diagnostic expectation syntax. The following works as expected:

```dart
main() {
  int i = 42;
  i?..isEven;
// ^^^
// [analyzer] STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR
}
```

**Comment by scheglov** [comment]
I still see similar failure for `co19/LanguageFeatures/nnbd/weak/type-aliases/null_aware_operator_A17_t02`.
Is this because `co19` has not been rolled yet?

```console
FAILED: dart2analyzer-none release_x64 co19/LanguageFeatures/nnbd/weak/type-aliases/null_aware_operator_A17_t02
Expected: Pass
Actual: StaticWarning

--- Command "dart2analyzer" (took 71ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=nonfunction-type-aliases --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.packages --format=machine --no-hints /Users/scheglov/Source/Dart/sdk.git/sdk/tests/co19/src/LanguageFeatures/nnbd/weak/type-aliases/null_aware_operator_A17_t02.dart

unexpected analysis errors:
In tests/co19/src/LanguageFeatures/nnbd/weak/type-aliases/null_aware_operator_A17_t02.dart:
- Line 44, column 20: STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR
  The receiver can't be null, so the null-aware operator '?..' is unnecessary.

- Line 49, column 20: STATIC_WARNING.INVALID_NULL_AWARE_OPERATOR
  The receiver can't be null, so the null-aware operator '?..' is unnecessary.
<cut>
```

**Comment by leafpetersen** [comment]
What's the status here?  Do we still have known bad tests here?

**Comment by sgrekhov** [comment]
@leafpetersen just fixed the issue above. Fix will be enabled after the next roll
