### ISSUE TITLE
LibTest/io/Process/stderr_A01_t01 should not make assumptions about how byte chunks are split up when reading from a stream

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#998]
The test `LibTest/io/Process/stderr_A01_t01` (maybe other tests as well) contains:
```
  Process.start(command, args).then((Process process) {
    Expect.isTrue(process.stderr is Stream<List<int>>);
    Utf8Decoder decoder = new Utf8Decoder();
    process.stderr.toList().then((List errList) {
      String decoded = decoder.convert(errList[0]);
      Expect.isTrue(decoded.contains("Hi, stderr"), "Actual value: $decoded");
      asyncEnd();
    });
  });
```

This code accumulates all output byte arrays from `process.stderr` and assumes the first such byte array contains the encoded string. This is incorrect, since the operating system can arbitrarily chunk up the bytes written to `stderr` by the child process.

What would be more correct is to

```
  List<String> lines = await process.stderr
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .toList();
```

**Comment by cskau-g** [comment]
`LibTest/io/Process/stdout_A01_t01` has the same issue.

**Comment by mkustermann** [comment]
`LibTest/io/Process/stdin_A01_t01.dart` as well.

These tests cause a lot of flakiness on our continuous integration system. 

@iarkh Do you have a timeline for when this could be implemented?
