### ISSUE TITLE
New test failures: Experiment flags etc.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/co19#999]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8855125729177425456/+/steps/test_results/0/logs/new_test_failures__logs_/0 reports several errors in co19 tests that seem to be caused by missing experiment flags and similar issues:

The following tests do not have `// SharedOptions=--enable-experiment=nonfunction-type-aliases`, but they do use some features that are only available with that experiment enabled:

https://github.com/dart-lang/co19/blob/master/Language/Classes/Superclasses/Inheritance_and_Overriding/inheritance_t07.dart
https://github.com/dart-lang/co19/blob/master/Language/Generics/syntax_t31.dart

The following test uses triple-shift on an `int`, but no such operator has been declared on `int` at this point:

https://github.com/dart-lang/co19/blob/master/Language/Statements/Expression_Statements/syntax_t06.dart

**Comment by eernstg** [comment]
More tests where the experiment flag is missing:

https://github.com/dart-lang/co19/blob/master/Language/Generics/parameter_A01_t03.dart
https://github.com/dart-lang/co19/blob/master/Language/Generics/typedef_A01_t10.dart

**Comment by sgrekhov** [comment]
@eernstg what's wrong with https://github.com/dart-lang/co19/blob/master/Language/Statements/Expression_Statements/syntax_t06.dart? It has triple-shift experiment flag. Seems it is an implementation error if triple-shift operator is not recognized

**Comment by eernstg** [comment]
I think the problem is not the implementation of the tools, it is the fact that there is no declaration of an `operator >>>` in the class `int` in the system libraries. So we're basically waiting for that to happen. Surely there must be a TODO entry (a github issue) somewhere to get that done.

**Comment by sgrekhov** [comment]
Ok. Now this test is turned off in a .status file with the comment that triple shift is not implemented yet (https://dart-review.googlesource.com/c/sdk/+/185082/3/tests/co19/co19-co19.status). So, closing this issue

**Comment by eernstg** [comment]
Ah, just one more comment: That comment in the status file, couldn't it say "not implemented in `int` yet"?

We would then make a distinction between the language feature (which, I believe, has been implemented fully) and the system library declarations (where `operator >>>` in `int` is missing, but could be written any time now, at least if we can force-enable the triple-shift experiment in `int.dart`).

There might be a need to update dart2js such that it generates specialized optimizations around `>>>`, but I don't think we need to worry about that here: It should be working now, and no tests will break just because the program runs a bit slower now and faster later on.

**Comment by sgrekhov** [comment]
> That comment in the status file, couldn't it say "not implemented in int yet"?

Do you mean this particular comment or all ` # Triple shift is not implemented yet` comments in that status file?

**Comment by eernstg** [comment]
The ones that actually depend on the `operator >>>` in `int`. The remaining ones (that only depend on `operator >>>` as a language feature) would presumably not have to be disabled in a status file, but they do need the experiment flag.

**Comment by sgrekhov** [comment]
Ok, I'll check

**Comment by eernstg** [comment]
Thanks! I hope we can test the language mechanism as such (so the typical approach would be to declare an `operator >>>` in some class and then use it), and then the (important but tiny) missing part of adding an `operator >>>` to `int` would be tested when we have such a declaration.

But maybe the tests of `>>>` on `int` should be in `co19/LibTest/core/int`, and that would make it easy to keep track of what's enabled and what is still waiting a bit?
